### ISSUE TITLE
[BUG]级联保存数据时，当前对象与关联对象都没有设置ID或KEY，会导致更新失败

### ISSUE THREAD

**Issue by TokgoRonin** [babyfish-ct/jimmer#10]
常规逻辑，集联保存时，当前对象与关联对象的ID一般情况下是不会有值的，默认是数据库生成，所以我在角色实体Role和权限实体permission上都设置了ID生成策略为GenerationTpye.IDENTITY。
![mmexport1663841001232.png](https://user-images.githubusercontent.com/26754622/191719062-0649ed36-0d6c-4d7a-8026-bbe487aca5a4.png)

但是保存的对象中没有传双方的ID，
![mmexport1663841004608.png](https://user-images.githubusercontent.com/26754622/191719115-3ca04e2f-f392-4d82-aed4-cf5102cbb4d9.png)
即使我设置了setAutoAttachingAll()，指定了SaveMode.INSERT_ONLY
![mmexport1663840978470.png](https://user-images.githubusercontent.com/26754622/191718987-9173c5ff-8802-43ff-a23f-a8864983d2b9.png)
jimmer依旧还要判断ID或KEY，导致报错
![mmexport1663840986068.png](https://user-images.githubusercontent.com/26754622/191719191-c73df094-520d-4758-9712-6db32a266316.png)

我认为在集联保存且指定为insert_only时，不应该进行此ID或KEY判断，否则在保存前需要手动生成一个ID或KEY给当前对象及其关联对象，相当麻烦且不符合常规逻辑。

**Comment by babyfish-ct** [comment]
对于根对象，insert_only可以考虑

但是，对于关联对象没法，关联对象默认upsert，可以设置为upsert，没有insert_only

**Comment by babyfish-ct** [comment]
After discuss, we all agree to close it.
