### ISSUE TITLE
插入关联时可以检查存在性，希望检查存在性单拎出来出个方法

### ISSUE THREAD

**Issue by Enaium** [babyfish-ct/jimmer#103]
```kotlin
sqlClient
    .getAssociations(
        Book::authors
    )
    .batchSave(
        listOf(10L, 11L, 12L),
        listOf(1L, 3L),
        checkExistence = true
    )
```

这是文档中，检查存在性的例子，希望这个`checkExistence`，单独出个方法

**Comment by babyfish-ct** [comment]
Try `0.7.64`

**Comment by Enaium** [comment]
> Try `0.7.64`

我的意思是既然在插入时可以检查关联是否存在，为何不把这一步出个单独的，用于检测关联是否存在的方法

**Comment by babyfish-ct** [comment]
因为在批量量保存中，checkExistence也是批量的。

- 如果单独暴露checkExistence(sourceId, targetId)并返回boolean，就等同于鼓励用户编写细粒度SQL。

- 如果checkExistence返回复杂查询结果以解决批量化问题，就和中间表直接查询重复。
