### ISSUE TITLE
使用spring-boot-devtools时，导致指定FetchBy的ownerType会使ImmutableType不相等

### ISSUE THREAD

**Issue by Enaium** [babyfish-ct/jimmer#109]
https://github.com/babyfish-ct/jimmer/blob/502b0b41e18dd4b4b19e79f15f81e516268da5e5/project/jimmer-client/src/main/java/org/babyfish/jimmer/client/meta/impl/ImmutableObjectTypeImpl.java#L146

**Comment by babyfish-ct** [comment]
Try `0.7.66`
