### ISSUE TITLE
[Feature Request]建议qbe自动忽略掉entity的关联属性

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#110]
![image](https://github.com/babyfish-ct/jimmer/assets/38320937/c06c0fc5-2485-49c3-8917-07bbcf9429cc)
不希望报错

![image](https://github.com/babyfish-ct/jimmer/assets/38320937/5d9156d2-13b4-4a4a-a336-3fe8294fe4e7)
外键的支持请保留
就是那个表的字段都支持，其他表的字段自动忽略

**Comment by babyfish-ct** [comment]
Try `0.7.66`
