### ISSUE TITLE
微服务 + 缓存模式下，无法获取到实体类型

### ISSUE THREAD

**Issue by ffggll** [babyfish-ct/jimmer#111]
SqlClientConfig 类的 preCreateSqlClient 方法中，先调用了 setCaches 方法，后设置了微服务名，导致 setCaches 方法中未获取到微服务名，无法获取微服务下的实体类型，启动报错。
![bb01e4f74f64bbd064024fccd312f4a](https://github.com/babyfish-ct/jimmer/assets/31406551/4103a52c-81cc-445b-8d15-3bf8c23f3cd1)

**Comment by babyfish-ct** [comment]
Try `0.7.66`
