### ISSUE TITLE
建议添加查询、修改、删除的拦截器功能，用来统一做数据权限拦截功能

### ISSUE THREAD

**Issue by zengyufei** [babyfish-ct/jimmer#117]
### 描述（Description）

建议添加查询、修改、删除的拦截器功能，用来统一做数据权限拦截功能

**Comment by Enaium** [comment]
https://babyfish-ct.github.io/jimmer/zh/docs/jimmer-sql/mutation/interceptor/

**Comment by auaa** [comment]
如果是查询的话，有关使用的是过滤器
[https://babyfish-ct.github.io/jimmer/zh/docs/jimmer-sql/advanced/filter](https://babyfish-ct.github.io/jimmer/zh/docs/jimmer-sql/advanced/filter)

**Comment by zengyufei** [comment]
版本: 0.7.77
数据库: postgresql

1 结构

```
Project
|-  Tender
```
2 子类 Tender 实体
```
interface Tender {

    @IdView 
    String projectId(); 

    @ManyToOne 
    Project project();
}
```

3 声明父类
```
@MappedSuperclass
public interface ProjectAware {
    String projectId();
}
```

4.期望：    
    debug成功调用 filter 方法。

```
@Component
public class ProjectFilter implements Filter<ProjectAwareProps> {

    @Override
    public void filter(FilterArgs<ProjectAwareProps> args) {
        args.where(
              args.getTable().projectId().eq("123")
        );
    }
}
```

5 实际：    
    报错 
`Illegal property "tender.projectId", it overrides property of super type, this is not allowed`


6 尝试变更

```
interface Tender {

    // 注释 @IdView 
    // 注释  String projectId(); 

    @ManyToOne 
    Project project();
}
```
    报错 
`ERROR: column tb_1_.project_id does not exist`

实际字段名严格大小写  必须双引号包裹 "PROJECT_ID"

7 二次尝试变更

```
@MappedSuperclass
public interface ProjectAware {
    @Column(name= "\”PROJECT_ID\”")
    String projectId();
}
```

    报错 
`org.babyfish.jimmer.meta.ModelException: Illegal type "tender", the column "PROJECT_ID" is mapped by both "tender.projectId" and "tender.project", it looks like "tender.projectId" should be a property decorated by "@org.babyfish.jimmer.sql.IdView"`

8 三次尝试变更

```
@MappedSuperclass
public interface ProjectAware {
    @IdView("project")
    @Column(name= "\”PROJECT_ID\”")
    String projectId();
}
```
    报错 
`Illegal property "com.pj.common.po.ProjectAware.projectId", the id-view property cannot be decorated by @org.babyfish.jimmer.sql.Column`


9 四次尝试变更

```
@MappedSuperclass
public interface ProjectAware {
    @IdView("project")
    // 注释 @Column(name= "\”PROJECT_ID\”")
    String projectId();
}
```
    报错 
`Illegal property "com.pj.common.po.ProjectAware.projectId", it is decorated by "@org.babyfish.jimmer.sql.IdView" but there is no base property "project" in the declaring type`



接下来，我无好的主意处理该问题，所以来求助作者

**Comment by babyfish-ct** [comment]
```
 @IdView
 String projectId();
 
 @ManyToOne
 @JoinColumn(name= "\”PROJECT_ID\”")
 Project project();
 ```

**Comment by zengyufei** [comment]
已解决！


`@MappedSuperclass
public interface ProjectAware {
    @IdView("project")
    String projectId();
    @ManyToOne
    @JoinColumn(name = “\”PROJECT_ID\“”)
    ProjectPO project();
}`


`interface Tender  extends ProjectAware {

}`

**Comment by babyfish-ct** [comment]
应该不需要@JoinColumn，默认策略就是这样.

https://babyfish-ct.github.io/jimmer/zh/docs/team-work/mapping/base/naming-strategy
