### ISSUE TITLE
entity增加关联映射后运行卡构建

### ISSUE THREAD

**Issue by mtpkiss** [babyfish-ct/jimmer#119]
idea version 2023.1.2
jdk version 1.8.0_202
maven version 3.9.2
jimmer version 0.7.75
若entity中不存在关联映射,项目可以直接启动
增加上关联映射(类似于oneToOne)后.项目启动卡构建,怀疑是jimmer-apt问题

**Comment by babyfish-ct** [comment]
it has been resolved in `0.7.75`
