### ISSUE TITLE
[BUG] When the database dialect is PostgreSQL, the @Serialized annotation handles null values incorrectly

### ISSUE THREAD

**Issue by ClearPlume** [babyfish-ct/jimmer#120]
The entity interface is as follows:

```kotlin
interface Task {
    @Serialized
    val strategyFields: List<StrategyField>?
}
```

The values in this column may be null, and according to common sense, null values will not go through the ScalarProvider process.

But PostgreSQL will wrap null values as follows:
![null PGobject](https://github.com/babyfish-ct/jimmer/assets/18047536/db5509a4-730d-404b-b872-ce6944a4cbe0)

Then this sqlValue itself is not null, so it will enter the ScalarProvider process:
![null in provider process](https://github.com/babyfish-ct/jimmer/assets/18047536/942ef6d7-75fa-47ab-98c7-adbe2cbd3747)

Then the following exception will be thrown:
![exception](https://github.com/babyfish-ct/jimmer/assets/18047536/dd38af0d-033a-4922-847f-8be06d2037c5)

**Comment by babyfish-ct** [comment]
Try untagged version `0.7.76`

**Comment by babyfish-ct** [comment]
Try `0.7.77`

**Comment by ClearPlume** [comment]
Fixed
