### ISSUE TITLE
[Feature Request] Make idview support participation conditions

### ISSUE THREAD

**Issue by ClearPlume** [babyfish-ct/jimmer#122]
Now the IdView property does not support participating in query conditions.

![Not Supported](https://github.com/babyfish-ct/jimmer/assets/18047536/4409045c-c3b6-4c8e-b897-9ae7abc6dbe9)

When the old system is upgraded to a version with IdView, the existing query methods with IdView columns in Repository have to be written manually in sql.

Too troublesome, and the changes are too big.

In addition, this will also limit the conventional query methods of Repository.

**Comment by babyfish-ct** [comment]
Try `0.7.77`

**Comment by ClearPlume** [comment]
Validated.
