### ISSUE TITLE
entity增加关联映射后运行卡构建 

### ISSUE THREAD

**Issue by mtpkiss** [babyfish-ct/jimmer#123]
#119 

打开idea,无任何操作直接运行项目 ,正常
删除entity 部分字段直接运行项目  正常
增加entity 字段 运行项目 卡构建
已尝试如下解决办法

1. 重启idea
2. 清空idea缓存和索引
3. 更换maven版本
4. 更换jdk版本

未解决

https://github.com/babyfish-ct/jimmer/assets/3182367/33ae4806-59cb-43bc-8a48-9dc69db47915

**Comment by babyfish-ct** [comment]
Try `0.7.77`

**Comment by mtpkiss** [comment]
0.7.79正常.没有在出现上述情况
