### ISSUE TITLE
[Feature Request]通过中间表多对多关联时，希望增加可以阻止父对象被删除的配置

### ISSUE THREAD

**Issue by JackyLeeCS** [babyfish-ct/jimmer#126]
建议 `@JoinTable` 注解中增加 `Boolean` 类型的 `preventDeleteSouce` 和 `preventDeleteTarget`属性，分别用来阻止主动表和从动表中的对象被删除

**Comment by babyfish-ct** [comment]
Try `0.7.81`

@JoinTable supports `preventDeletionBySource` and `preventDeletionByTarget`

**Comment by JackyLeeCS** [comment]
`0.7.81` 已支持
