### ISSUE TITLE
java.sql.Date 和 java.sql.Time执行toInstant报错

### ISSUE THREAD

**Issue by draco1023** [babyfish-ct/jimmer#14]
https://github.com/babyfish-ct/jimmer/blob/caeaf547c86142b08aad2dfcfda76df92c25805b/project/jimmer-sql/src/main/java/org/babyfish/jimmer/sql/runtime/Converters.java#L66-L68

java.sql.Date 和 java.sql.Time 都继承自 java.util.Date，但是都不支持 toInstant 方法，67行会报错。本来想提个PR，但是我的IDEA版本是2019.3，工程都无法编译，就放弃了。就是将二者分别转成 LocalDate 和 LocalTime，再转换成 Instant。

**Comment by babyfish-ct** [comment]
0.2.24 is ready

**Comment by draco1023** [comment]
还是不行 Instant.from 会报错
java.time.DateTimeException: Unable to obtain Instant from TemporalAccessor: 2020-02-01 of type java.time.LocalDate

**Comment by babyfish-ct** [comment]
0.2.5 is ready, added unit tests for it

**Comment by draco1023** [comment]
https://github.com/babyfish-ct/jimmer/blob/f1faf50f98b0b6f40b9fa3fb7ba5a1b6b44ddafb/project/jimmer-sql/src/main/java/org/babyfish/jimmer/sql/runtime/Converters.java#L78-L83

Same issue in these lines with version 0.2.24

**Comment by babyfish-ct** [comment]
Please try 0.2.26
