### ISSUE TITLE
怎么映射json等复杂类型字段呢？

### ISSUE THREAD

**Issue by llh4github** [babyfish-ct/jimmer#15]
目前使用postgresql，表中有一个Json字段，如何映射到`@Entity`类中呢？

文档里没看到相关内容，直接用类接收就出现类型转换错误。
`Failed the convert the result value at column $6, the expected type is 'xxxx', but the actual type is 'org.postgresql.util.PGobject'
`

**Comment by babyfish-ct** [comment]
https://babyfish-ct.github.io/jimmer/zh/docs/jimmer-sql/sql-client#scalarprovider

你可以加入Jimmer微信交流群，很热闹（二维码在项目和文档中都有）
