### ISSUE TITLE
[Feature Request]逻辑删除兼容spring-boot-devtools

### ISSUE THREAD

**Issue by mtpkiss** [babyfish-ct/jimmer#183]
springboot项目在启用spring-boot-devtools时候,逻辑删除会出现删除生效,查询不生效的情况
![image](https://github.com/babyfish-ct/jimmer/assets/3182367/a1d8ba0a-8572-41e5-8260-d61731479245)
![image](https://github.com/babyfish-ct/jimmer/assets/3182367/d6515c7c-3bf6-4c56-b00b-4b308a3f9a9c)
log日志如下
![image](https://github.com/babyfish-ct/jimmer/assets/3182367/73c3ff51-6574-4ade-a1bd-4261af301ec5)
如上所示delete生效 查询不生效

**Comment by babyfish-ct** [comment]
Try `0.7.107`

**Comment by mtpkiss** [comment]
When enabling `spring-boot-devtools`, the issue still exists in version `0.7.107`

**Comment by babyfish-ct** [comment]
Try `0.7.109`

**Comment by mtpkiss** [comment]
`0.7.109` 在springboot `2.7.13` 下正常
