### ISSUE TITLE
缓存严重问题

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#190]
![9011688657944_ pic](https://github.com/babyfish-ct/jimmer/assets/38320937/3e98d69b-2741-4317-8a2a-facb2c1b2e44)
这是第一次查询，没有缓存

结果一刷新
![image](https://github.com/babyfish-ct/jimmer/assets/38320937/5734fbf3-f90f-48d5-b26e-be4a2b01af90)
作者没了

**Comment by babyfish-ct** [comment]
Try `0.7.113`

-    Solution: line 206~208 in https://github.com/babyfish-ct/jimmer/blob/main/project/jimmer-sql/src/main/java/org/babyfish/jimmer/sql/fetcher/impl/FetcherTask.java
     ```java
     if (!isImplicit) {
        draft.__show(propId, true);
     }
     ```
     
- UnitTest: https://github.com/babyfish-ct/jimmer/blob/main/project/jimmer-sql/src/test/java/org/babyfish/jimmer/sql/cache/Issue190Test.java
