### ISSUE TITLE
[Feature Reequest] Specify object mapper while using `@Serialized`

### ISSUE THREAD

**Issue by aboutZZ** [babyfish-ct/jimmer#192]
有一个Oauth2授权表，里面存了用户授权时的一些参数
```kotlin
interface OAuth2Authorization {
    @Id
    @GeneratedValue(generatorType = UUIDIdGenerator::class)
    val id: UUID

    @Serialized
    val attributes: Map<String, Any>?

    ... ...
}
```
参考了Spring Security 的做法：出于安全考虑，用户输入的数据被视为是不安全的，因此需要指定一个白名单，其中的类是可以安全地进行（反）序列化（序列化时，存储类名; 反序列化时，只能反序列化指定白名单中的类，否则可能导致**反序列化安全漏洞**）
为此，定义了一个新的`ObjectMapper` 并进行类型混入配置
```java
private ObjectMapper objectMapper = new ObjectMapper();
objectMapper.registerModule(new OAuth2AuthorizationServerJackson2Module());

public class OAuth2AuthorizationServerJackson2Module extends SimpleModule {

	public OAuth2AuthorizationServerJackson2Module() {
		... ... constructor
	}

	@Override
	public void setupModule(SetupContext context) {
                // 类型混入配置
		SecurityJackson2Modules.enableDefaultTyping(context.getOwner());
		context.setMixInAnnotations(Collections.unmodifiableMap(Collections.emptyMap()).getClass(),
				UnmodifiableMapMixin.class);
                context.setMixInAnnotations(Integer.class, IntegerMixin.class);
                context.setMixInAnnotations(Long.class, LongMixin.class);
		context.setMixInAnnotations(HashSet.class, HashSetMixin.class);
		... more ... 
	}

}

// 反序列化时查询白名单，看看类名是否在里面
// See https://github.com/spring-projects/spring-security/blob/72698680e2be0eb7d2ed44256452f687fe5fe28b/core/src/main/java/org/springframework/security/jackson2/SecurityJackson2Modules.java#L269
if (isInAllowlist(className)) {
   // return OK
}
if(isInMixInList(className)) {
  // return OK
}

if(isAnnotatedWithJacksonAnnotation()) {
  // return OK
}

// return ERROR
```
因此想让@Serialized注解可指定自定义的object mapper

**Comment by aboutZZ** [comment]
通过翻看源码发现`@Serialized`使用的是`JsonUtils`类中的`OBJECT_MAPPER`，对此 `ObjectMapper` 进行操作或重新赋值即可。

**Comment by babyfish-ct** [comment]
这种情况下，应该为此属性自定义ScalarProvier，而非@Serialized

**Comment by babyfish-ct** [comment]
由于字节码规范的限制，Java/Kotlin的Annotation的属性只能是基本类型，String, Class以及它们的数组，自定义ObjectMapper这样的信息无法为Annotation所接受。

如果为了让@Serialized支持此特性，必须设计类似于注册scalar provider的代码API，完成自定义object mapper的注册管理代码API，最后把声明方式的@Serialized和代码方式的object mapper结合起来，完成整体功能。最终，这会得不偿失，还不如直接使用scalar provider

**Comment by aboutZZ** [comment]
可否对 `JsonUtils`中的`ObjectMapper` 对外开放，以便可以访问到此类对 `ObjectMapper` 替换或做些配置？ 目前 该类未被修饰为 `public`，且`OBJECT_MAPPER`变量修饰为`final`。

直接序列化对象存储至数据库而不进行任何检查是极度危险的，很容易造成漏洞

**Comment by babyfish-ct** [comment]
全局ObjectMapper可以

**Comment by babyfish-ct** [comment]
Try `0.7.122`.

`JSqlClient.Builder` and `KSqlClientDsl` supports new methods `setSerializedTypeObjectMapper` and `setSerializedPropObjectMapper`. In the end, the relatively complex change of providing more APIs was chosen to solve this problem.
