### ISSUE TITLE
When compiling the project, if an entity's association field is not annotated as ManyToMany, ManyToOne, etc., the error message generated is not explicit enough

### ISSUE THREAD

**Issue by ClearPlume** [babyfish-ct/jimmer#199]
Entity structure is as follows: 

![Entity Structure](https://github.com/babyfish-ct/jimmer/assets/18047536/cd1ef4ed-521f-4304-917c-8de8853073c4)

The field `connector` of `SecurityTag` is not annotated with `ManyToOne`, which produced the following error message:

```
SecurityTag.kt:21: Illegal property "SecurityTag.connector", it is not association property, its target type "Connector" is immutable type, immutable type is not enough, please use @org.babyfish.jimmer.sql.Entity
```

**Comment by babyfish-ct** [comment]
Try `0.7.122`

**Comment by ClearPlume** [comment]
Fixed.

But the error message for collection attributes is still the previous one.

**Comment by babyfish-ct** [comment]
Try `0.7.123`

**Comment by babyfish-ct** [comment]
Try `0.7.123`, `setDefaultSerializedTypeObjectMapper`

**Comment by ClearPlume** [comment]
Fixed.
