### ISSUE TITLE
legacy project support

### ISSUE THREAD

**Issue by lukywong** [babyfish-ct/jimmer#2]
@babyfish-ct really good staff with brilliant idea, i cannot wait to have a bit on it, when i try it within a legacy project, error comes out, it says **_org.babyfish.jimmer.apt.meta.MetaException: Illegal class "com.xxx.model.OrderEntity" immutable type must be interface_**, i know the new "entity" must be interface, but an old-fashion ORM was used, many old **class entities** use the same JPA annotation mechanisim, and they cannot be reformed at once, so is there any way i can ignore those old entities? so that the oldman could work together with jimmer util his retirement, thank you

**Comment by babyfish-ct** [comment]
v0.0.31, is published to resolve it.

tasks.withType(JavaCompile) {
    // Positive configuration
    options.compilerArgs += "-Ajimmer.source.includes=prefix1,prefix2,prefix3..."
    // Negative configuration
    options.compilerArgs += "-Ajimmer.source.excludes=prefix1,prefix2,prefix3..."
}

Prefix can be both package name and full class name.

If v0.0.31 resolve your problem, close it please
