### ISSUE TITLE
自动生成的 Convert 里面少了is 开头的字段

### ISSUE THREAD

**Issue by pot-mot** [babyfish-ct/jimmer#208]
![微信图片_20230805123537](https://github.com/babyfish-ct/jimmer/assets/112872898/9a561a44-5bff-4a20-8b8b-2aee4279ac65)
![微信图片_20230805123537_1](https://github.com/babyfish-ct/jimmer/assets/112872898/b993a25c-6a55-4538-a773-4c06f5382db2)
![input定义](https://github.com/babyfish-ct/jimmer/assets/112872898/43d1f0d4-32b7-4556-b017-d5a09259f113)

**Comment by babyfish-ct** [comment]
Try `0.7.131`
