### ISSUE TITLE
[BUG]  dto 在 id 函数解析时出现问题

### ISSUE THREAD

**Issue by pot-mot** [babyfish-ct/jimmer#220]
这是实体的字段

![实体字段](https://github.com/babyfish-ct/jimmer/assets/112872898/0cce1d0c-4ca2-447f-80a6-4febf9d4b04c)

这是 dto 文件

![dto文件定义](https://github.com/babyfish-ct/jimmer/assets/112872898/47fc2a30-165c-4237-859f-5a7873b11209)

具体出错如下

![1](https://github.com/babyfish-ct/jimmer/assets/112872898/d7d88b5d-5e1e-4aed-abdf-9f791fa2ce83)
![2](https://github.com/babyfish-ct/jimmer/assets/112872898/b38e7560-da15-479c-ad89-8f0a1c4beda4)

具体问题是应该去寻找实体，但是去找了 IdView 属性

![问题出现处](https://github.com/babyfish-ct/jimmer/assets/112872898/c0410d8c-8ac7-4924-b50b-4c516fe29317)

**Comment by babyfish-ct** [comment]
我需要GenAssociation的定义

**Comment by babyfish-ct** [comment]
Try `0.7.132`
