### ISSUE TITLE
这个关联映射真的看不懂 [求帮助]

### ISSUE THREAD

**Issue by winlans** [babyfish-ct/jimmer#227]
1. 这表述确定没有问题吗？感觉有点晦涩。

![image](https://github.com/babyfish-ct/jimmer/assets/16457089/45f29009-1646-442b-a283-1101df2f1bec)

2. 还有个问题， 就是我定义的表都是没有外键约束的，也就是虚拟外键，但是在使用
```java
  @JoinTable(
            joinColumns = @JoinColumn(foreignKeyType = ForeignKeyType.FAKE),
            inverseColumns= @JoinColumn(foreignKeyType = ForeignKeyType.FAKE)
    )
```
指定外键为FAKE貌似没用， 但是直接在配置文件中指定`jimmer.is-foreign-key-enabled-by-default=false` 就是好的。

**Comment by babyfish-ct** [comment]
1. 确定没问题，BookStore种的books是Book.store的镜像，二者对此，Book关联BookStore, BookStore关联Book，彼此关联，两个方向各一个关联属性

2. 这个我空了看看

**Comment by babyfish-ct** [comment]
你也可以参考CSDN上人们对JPA/Hibeernate中mappedBy的讲解（就mappedBy这一个配置而言，Jimmer和它们没区别）

https://blog.csdn.net/qq_29954971/article/details/79088079

**Comment by winlans** [comment]
> 你也可以参考CSDN上人们对JPA/Hibeernate中mappedBy的讲解（就mappedBy这一个配置而言，Jimmer和它们没区别）
> 
> https://blog.csdn.net/qq_29954971/article/details/79088079

之前一直使用mybatis这种， 基本没用过jpa，看了这个真的豁然开朗😊

**Comment by babyfish-ct** [comment]
?

**Comment by babyfish-ct** [comment]
有任何疑问，进入文档资源篇，加群
