### ISSUE TITLE
[Feature Request] DTO 小语言添加对额外自定义字段的支持

### ISSUE THREAD

**Issue by ffggll** [babyfish-ct/jimmer#228]
希望 DTO 小语言可以添加对额外自定义字段的支持，以满足诸如按时间段查询等业务逻辑，而不必手写 imput。

**Comment by babyfish-ct** [comment]
`0.8.5`

**Comment by babyfish-ct** [comment]
`0.8.6` supports annotation

**Comment by ffggll** [comment]
我更新到 0.8.6 版本，发现了一些问题：
1. input dto 中无法直接使用 IdView 注解的属性，只能使用 id(xxx) as yyy 的形式，不加 input 就可以直接使用 IdView 注解的属性
![image](https://github.com/babyfish-ct/jimmer/assets/31406551/745af5de-5c12-440c-9431-fc44cb51b33e)
2. dto 中存在多个 flat 时，生成的 ViewMetadata 里的 flat 属性之间没有换行，导致编译出错，添加换行后错误消失
![image](https://github.com/babyfish-ct/jimmer/assets/31406551/0d95e13c-90b9-45d3-9064-2e5bda22374b)
3. dto 中，注解只能加到自定义字段上？

--------------
我更新到 0.8.7 后，上面的问题仍然存在，并且又发现了新的问题
4. flat 函数与自定义字段同时存在时，生成的代码中的副构造函数调用主构造函数时，flat 字段与自定义字段的顺序错误
![image](https://github.com/babyfish-ct/jimmer/assets/31406551/4d3647a7-630f-4c5c-8969-1819364bc4bf)

**Comment by babyfish-ct** [comment]
Try `0.8.8`

**Comment by ffggll** [comment]
`0.8.8`版本还是有点问题，自定义字段被从构造方法中移除了，但是副构造方法仍然尝试向主构造方法传参
![image](https://github.com/babyfish-ct/jimmer/assets/31406551/2d4ee93b-132f-48a8-8cde-55d0f7f0144d)

**Comment by ffggll** [comment]
而且自定义字段不放到构造函数里的话，Controller 里接收到的参数里的对应字段就没有值

**Comment by ffggll** [comment]
问题已解决
