### ISSUE TITLE
实体nullable字段，通过DTO生成 toEntity 方法时，Update缺失字段失效

### ISSUE THREAD

**Issue by g770728y** [babyfish-ct/jimmer#229]
## Entity 
```
Person {
   id 
   name 
   remark?  // <-- nullable
}
```

## DTO
```
UpdatePersonInput {
    id
    name?
    remark     // <-- 由于Entity的remark 可空, 所以这里不能加?号, 否则报错
}
```

## 生成的代码
```
class UpdatePersonInput{
    public override fun toEntity(): Person = new(Person::class).by {
        val that = this@UpdatePersonInput
        this.id = that.id
        if (that.name !== null) {
            this.name = that.name
        }
        this.remark = that.remark   // <----------  这里, 我希望构造缺失字段, 但被赋值为null了
    }
}
```

## 备注
由于我前台使用了diff, 生成的Update数组没有稳定结构。
构造成的 UpdatePersonInput 可能是这样：
```case0: UpdatePersonInput(id, remark="xxxx")```
也可能是这样：
```case1: UpdatePersonInput(id, name="xx")```
对于case1,  **toEntity 里 this.remark 被赋值为 null** ，导致 调用 
personRepository.update(input.toEntity()) 时 , 数据库的 remark 字段被清空

请问这种情况当如何处理呢？ 不确定是不是什么地方用得不对

**Comment by babyfish-ct** [comment]
![image](https://github.com/babyfish-ct/jimmer/assets/15168900/7bf3600e-2788-4b05-b393-cb79caef5c74)

这本就是文档中详细讨论过的场景。

不鼓励尝试让静态Inpu类型具备动态对象那种特性，更鼓励不同的业务场景有不同Input，静态对象就要像静态对象，而不要像动态对象（否则，支持DTO语言干嘛呢？）。反正DTO语言的支持下，这样做几乎无成本。

**Comment by g770728y** [comment]
感谢这么晚回复!

嗯，这段是我已经注意到的。之所以这样尝试，是因为暂时没找到更好的办法。

业务场景是这样的，麻烦看下这种情况在Jimmer中应该如何处理呢：
1. 前端是一棵树，节点设计数量大约10万，每个节点自身在 0.1K - 100K 间，用index维护节点序
2. 用户希望整个应用 表现得象 本地应用，而且可以断网使用，所以排除 每个操作都即时上传
3. 目前我的做法是 在前端 diff 出 Added/Updated/Removed 三个大数组 上传，在服务端 patch
4. 问题就出在 Updated 上面，对树状结构，用户轻微调序后也会出现大量的 {id, index} 这样的字段，也就是仅 index 发生了变化，所以我不希望 Update 回传整条记录
5. 这样 UpdateInput 就没有固定结构了， 所以我希望利用 Jimmer 的可空特性

总结下： 一个大数组，数组元素可能是 {id, name}, 或 {id, remark}, 或 {id, name, remark}, 希望 Update 自动处理。

目前的做法是自己写了 toEntity 方法，但感觉不太好，不知道有没有什么更好的方式

**Comment by babyfish-ct** [comment]
Input静态类型不定义index即可。就算传了，也会丢弃。

**Comment by g770728y** [comment]
可能我没表达好意思，index不能不定义
这里实际上我需要的确实是 偏动态的类型，需求略奇怪
再次感谢回复了^_^

**Comment by babyfish-ct** [comment]
那就不用input了，既然需求中“动态”如此明确，直接用动态对象接受@RequestBody

【注意：必须验证，确保不想动的字段一定是unloaded的。以保证安全性（这其实也是引入静态input的初衷）】

**Comment by babyfish-ct** [comment]
所以，明白引入静态input的原因，才是最重要的。

当静态input真不合适的时候，只要补足静态input所隐含的约束力，就可以只用动态对象作为输入。
