### ISSUE TITLE
Is Jimmer support SQL Server?

### ISSUE THREAD

**Issue by GMorandi** [babyfish-ct/jimmer#234]
I am trying to use Jimmer in my new project, but after I read the document, I found that the database support is not very clear.

**Comment by SWQXDBA** [comment]
no 
current dialect list is :

org.babyfish.jimmer.sql.dialect.H2Dialect

org.babyfish.jimmer.sql.dialect.MySqlDialect

org.babyfish.jimmer.sql.dialect.PostgresDialect

org.babyfish.jimmer.sql.dialect.OracleDialect

org.babyfish.jimmer.sql.dialect.TiDBDialect

**Comment by SWQXDBA** [comment]
befause ms sql server don't support sql like
where (a, b) in ((3, 4), (8, 13))

**Comment by babyfish-ct** [comment]
Yes, SQL server does not support tuple eq or tuple in. I cannot fix it in
short time, so it is not supported temporarily

You can join wechat group by the information supported by "资源篇"

GMorandi ***@***.***> 于2023年8月22日周二 15:54写道：

**Comment by GMorandi** [comment]
> 
Can "tuple in" be reparsed with the keyword “AND&OR”?
Like SQL“WHERE (a, b) IN ((3, 4), (8, 13))”, it can be rewritten like“WHERE(a = 3 AND b = 4) OR (a = 8 AND b = 13)”.

**Comment by babyfish-ct** [comment]
Yes, it will be replaced in the future, but not now.
