### ISSUE TITLE
[Feature Request]DTO语言建议可以强制指定属性不为空

### ISSUE THREAD

**Issue by JackyLeeCS** [babyfish-ct/jimmer#237]
部分属性在新增的时候是没有的，数据库中也可能是空的，但是在执行某些更新操作的时候是不能为空的，建议在DTO语言中增加类似于`kotlin`中`!`的语法，强制生成不可为空的属性

**Comment by JackyLeeCS** [comment]
`id`属性没办法强制指定为非空。
对我这种Create和Update分开生成dto的来说，其实不需要框架自动将`id`变为可为空的，Create里面我会把id去掉，Update里面id总是不为空的，建议提供可配置的途径

**Comment by babyfish-ct** [comment]
Try `0.8.10`,

input下id属性可以加!

**Comment by JackyLeeCS** [comment]
`0.8.10`可以了
