### ISSUE TITLE
[Help Wanted]修改语句中set的两个参数类型不一致

### ISSUE THREAD

**Issue by JackyLeeCS** [babyfish-ct/jimmer#239]
<img width="777" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/9ce8cc76-4f2c-44e7-8b44-c687075f3fe5">

第一个报错的地方字段是`Int`类型，子查询`count`返回的是`Long`类型；

另一个字段是`String?`类型，值是`String`类型的；

没有找到合适的解决方案，希望能得到帮助。

**Comment by babyfish-ct** [comment]
1. 强转为Int表达式：select(count(table.id) as KNonNullExpression<Int>)
2.强转为Nullable类型：modify.remarks as Type?

**Comment by JackyLeeCS** [comment]
<img width="719" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/de2fbc37-0149-46f0-a8d0-12bec4129257">

第一个可以，只是会有警告

第二个不行，这种转换是无效的

**Comment by babyfish-ct** [comment]
消除Warning的方式，给方法加@Supress("UNCHECKED_CAST")

![image](https://github.com/babyfish-ct/jimmer/assets/15168900/95b5ce75-989d-4829-b621-aa2276282572)
set nullable是可以的，你这边的table.remarks是什么类型？

**Comment by babyfish-ct** [comment]
你说反了吧？table.remarks不能为null吧，应该modify.remarks!!

**Comment by JackyLeeCS** [comment]
没有说反，table.remarks是可以为空的，因为这个字段开始是没有值的；

然后这个更新的方法必须要设置值，所以dto里面是非空的

**Comment by babyfish-ct** [comment]
那就val remarks: String? = modify.remark中转一下

**Comment by JackyLeeCS** [comment]
嗯，目前我也只想到这个方案，暂时先这样处理了。

感谢🌹🌹🌹

**Comment by JackyLeeCS** [comment]
嗯，这种需求应该很少，一般不会出现这种情况

**Comment by JackyLeeCS** [comment]
<img width="788" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/d77f6eab-184a-4fbf-8800-a383f965b76a">

抱歉，第二个问题不存在，是我代码写错了，`String?`和`String`是可以兼容的
