### ISSUE TITLE
[功能]验证功能添加load状态前置

### ISSUE THREAD

**Issue by TokgoRonin** [babyfish-ct/jimmer#24]
当前的验证，如果属性是unload状态的话，是不会经过校验的，但写校验的目的就是确保该属性符合业务要求，例如
```
@Entity
@Table(name = "d_role")
public interface Role {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    int id();

    @Nullable
    String code();

    @NotNull
    String name();
}
```

该实体要求id与name不可为空，然后用于在dao层查询。
现在如果接收参数时，name没有传值，例如：
```
{
    "id": 1
}
```
此时name是unload状态，则不过经过notnull校验，不会报错`'name' cannot be null`。
dao层还要在验证一次isload，不仅代码臃肿，而且也不符合直觉。
是否应该由框架在校验notnull之前先完成isload判断？

**Comment by babyfish-ct** [comment]
此功能属于input的范畴，现提供ImmutableConverter，以后还会有更强的映射。但无论以后如何演化，此功能和动态实体本身无关。
