### ISSUE TITLE
当数据库使用伪外键关联并开启数据库校验为ERROR模式时，外键配置可空但数据库外键字段设置为not null  启动校验不通过

### ISSUE THREAD

**Issue by qinkangdeid** [babyfish-ct/jimmer#244]
# 问题描述

表中有一 伪外键 数据库字段设置为 not null
<img width="766" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/17582522/73485a39-c2d1-4074-ba18-ea92818fa3a3">
文档关于属性 可为空的描述上  https://babyfish-ct.github.io/jimmer/zh/docs/mapping/base/nullity
<img width="1036" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/17582522/3abe95f9-5759-4a27-8d57-63bea0fc78c5">
当配置一对多关系时 伪外键的属性应当设置为可空类型
```kotlin
    @ManyToOne
    @JoinColumn(
        name = "DICT_ID",
        foreignKeyType = ForeignKeyType.FAKE
    )
    val sysDict: SysDict?

```
数据库校验开启ERROR模式:
```yaml
jimmer:
  language: kotlin
  database-validation:
    mode: ERROR
    catalog: xxxx
```
启动报错：SysDictItem.sysDict: The property is nullable, but the database column "DICT_ID" is nonnull

应该是数据库校验 与实体结构不一致报的错
  
# 期望
在数据库结构校验策略上 对伪外键的空值 忽略？
原因是 想保留数据库伪外键的字段在数据库结构层面仍然设计为not null    (希望这个not null起到最后持久化的校验屏障)
ORM层面设置为可空    val sysDict: SysDict?

**Comment by babyfish-ct** [comment]
检查了代码，没有错误，验证模块已经考虑了@ManyToOne(inputNonNull = true)

**Comment by qinkangdeid** [comment]
> inputNonNull

OK  设置
```kotlin

    @ManyToOne(inputNotNull = true)
    @JoinColumn(
        name = "dict_id",
        foreignKeyType = ForeignKeyType.REAL
    )
    val sysDict: SysDict?

```
可以了
