### ISSUE TITLE
怎么使用密封类作为实体列的类型？

### ISSUE THREAD

**Issue by SettingDust** [babyfish-ct/jimmer#245]
如下，想实现当类型为 C 时查中间表获得相应参数自动构建相应实体类，或存为 Json 对象到相应表
对于存 Json，自定义的序列化/反序列化是必须的吗？这种写法会报错列的类型不对
```kt
@Serialized
sealed class A(val name: String)

@Serialized
data object B : A("B")
@Serialized
data class C(val count: Int): A("C")
```

**Comment by babyfish-ct** [comment]
这个功能在JPA中是@Entity之间的继承关系，因为时间关系，当前版本没有，但以后一定会有。

如果和继承相关的信息都是非结构化且能接受无法作为查询条件，则用Jackson对多态的支持即可。

如果不是这样，把所有多态信息合并到一张表，并给表加一个type字段，是一个钟理想的规避方式（本质就是JPA @Entity继承的单宽表实现）
