### ISSUE TITLE
ScalarProvider 与 PGobject 整合问题

### ISSUE THREAD

**Issue by aboutZZ** [babyfish-ct/jimmer#246]
`toScalar`方法使用了 `@NotNull` 注解，导致在kotlin编程中，函数只能返回 `T` 类型，而不是 `T?`。
即使PG数据库中存储的值为`null`，查询得到`PGobject`却不是`null`， jimmer 将会执行 `toScalar`方法，但由于`PGobject.value` 是 `null`，`toScalar`方法无法返回 `T` 类型

**Comment by babyfish-ct** [comment]
Try `0.8.13`
