### ISSUE TITLE
[Feature Request]When converting a dto defined in the dto language to a parameter class, a type with no default values and all nullable parameters is needed for parameter checking.

### ISSUE THREAD

**Issue by ClearPlume** [babyfish-ct/jimmer#250]
Properties defined in the dto language will have a default value when generating the data class, which affects spring's parameter validation logic

![param default value](https://github.com/babyfish-ct/jimmer/assets/18047536/bc7effbe-fc8c-42e8-a75a-760b98fbd6af)

**Comment by babyfish-ct** [comment]
Try `0.8.13`
