### ISSUE TITLE
关于代码生成

### ISSUE THREAD

**Issue by GreenCypress** [babyfish-ct/jimmer#254]
每次用IDEA Plugin生成完实体类等代码，都需要手动maven compile来更新生成的代码文件，觉得很麻烦。
是否有什么方法能在Plugin生成完实体代码后自动生成Draft等代码文件，从而不需要手动执行maven compile，保证实体类等代码文件和jimmer-apt自动生成的代码是同步的。

**Comment by babyfish-ct** [comment]
修改了实体代码后，点击运行按钮，会重新生成代码的。

以后会考虑更理想的Intellij插件，但是，目前没时间资源。

**Comment by Enaium** [comment]
按Ctrl+Shift+F9重新编译
