### ISSUE TITLE
Too many matched tables

### ISSUE THREAD

**Issue by z27teen** [babyfish-ct/jimmer#256]
when I start my app, the below error occurs.

"Too many matched tables"

I use local mysql in my pc, and there are many databases in it. Many dbs has the tables with the same name, for example "sys_user".

So any incorrect setting by me?

**Comment by babyfish-ct** [comment]
https://babyfish-ct.gitee.io/jimmer-doc/docs/configuration/database-validation#%E8%A7%A3%E5%86%B3%E8%A1%A8%E5%86%B2%E7%AA%81
