### ISSUE TITLE
[BUG]kotlin下生成的dto代码与文档不符

### ISSUE THREAD

**Issue by JackyLeeCS** [babyfish-ct/jimmer#258]
<img width="1002" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/0aa174f6-479a-4a0c-8d4c-89d0a5d96436">
<img width="960" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/34682fdd-ac45-45ae-a54f-5bfe5cd7b802">
根据文档描述，`dto`中为`null`的属性也会被赋值给`entity`，但生成的`kotlin`代码，只有不为`null`的才会赋值

**Comment by babyfish-ct** [comment]
Try `0.8.20`

**Comment by JackyLeeCS** [comment]
可以了
