### ISSUE TITLE
Reactive support via R2DBC

### ISSUE THREAD

**Issue by rjaros** [babyfish-ct/jimmer#265]
Any chance of supporting non-blocking / reactive R2DBC instead of JDBC?

**Comment by babyfish-ct** [comment]
This was not in the design goals. There are two reasons:

- Jimmer was created when Java 21 was nearing, and with the help of virtual threads, asynchronous programming ecosystems are no longer a must.

- Jimmer is different from other ORMs, with many advanced features like querying or saving arbitrary shaped data structures with one API. The underlying logic for these advanced features is quite complex, and making them reactive would add complexity. Even if we made these features Kotlin-only (using kotlin coroutines) and gave up Java reactive to simplify, it would still lead to much code duplication (blocking vs non-blocking).
