### ISSUE TITLE
对象抓取器如何忽略id？

### ISSUE THREAD

**Issue by xiaoyoucheng** [babyfish-ct/jimmer#269]
使用对象抓取器是强制查询id吗？
这样如果不想对外公开关联对象的id数据，就只能自定义DTO再度封装了吗？

虽然文档里说了很多是隐式调用，但是还是想知道是否可能不查询id。
![image](https://github.com/babyfish-ct/jimmer/assets/33143581/0e28a137-5a11-42f5-a5e5-7010208b97e6)

**Comment by babyfish-ct** [comment]
对象抓取器无法忽略id，这是层层此次深入的必须条件。

把id送到客户端不是什么坏事，如果非要避免为客户端传id，请使用DTO语言定义Output DTO取代对象抓取器（二者本质相同，其实不存在取代问题）
