### ISSUE TITLE
规范逻辑删除的全局作用行为

### ISSUE THREAD

**Issue by moyuqinsi** [babyfish-ct/jimmer#275]
目前在 Jimmer 0.8.23 版本中逻辑删除存在行为不一致的情况，在 findById 或者通过 id 集合查询实体时会无视逻辑删除的作用，同样情况存在于 join table 及 subquery table 中，希望能统一逻辑删除启用时的行为减少用户开发心智负担，同时还能提供对应查询“已删除”的数据 api 能够实现类似撤回删除的效果

**Comment by qinkangdeid** [comment]
api行为一致很重要 如果要冲破这层访问删除数据 应当使用专用api

**Comment by babyfish-ct** [comment]
Try `0.8.31`
