### ISSUE TITLE
数据库校验 伪外键的 IdView 通不过校验，提示 No foreign key for columns

### ISSUE THREAD

**Issue by pot-mot** [babyfish-ct/jimmer#277]
![6ea31aa97f150c1d45131c63d3e3fbd](https://github.com/babyfish-ct/jimmer/assets/112872898/2cc1eea5-6573-4dd8-8048-10049166fb31)

可以明确原列已添加 @JoinColumn(foreignKeyType = ForeignKeyType.FAKE)

database-validation 配置如下，仅设置 schema 和 mode

![image](https://github.com/babyfish-ct/jimmer/assets/112872898/ec3f3f9f-6beb-4fbe-b39b-92718a7cee60)

**Comment by babyfish-ct** [comment]
Try `0.8.32`
