### ISSUE TITLE
@RequestBody pojo 不能接收到入参

### ISSUE THREAD

**Issue by atom0425** [babyfish-ct/jimmer#28]
场景描述：引入jimmer-apt后，@RequestBody pojo 不能接收到入参。删除jimmer dependency后可以正常解析。
当前版本：0.6.15
依赖：jimmer-spring-boot-starter jimmer-apt。
尝试降级至0.6.10也存在这个问题。其它版本未尝试

**Comment by babyfish-ct** [comment]
无法重现，也无其他人遇到此问题，你再试试（最新版本0.6.21）

**Comment by atom0425** [comment]
新版本中没有再发现这样的问题
