### ISSUE TITLE
Integrate Jimmer with Quarkus

### ISSUE THREAD

**Issue by x80486** [babyfish-ct/jimmer#280]
Was checking for a different library to start a `GraphQL` project and avoid the usual over-fetching / under-fetching problem at the database layer, and I found `Jimmer`.

Looks like there is already a `Spring Boot` starter, but `Quarkus` is getting traction these days.

Would you be interested in contributing to the `Quarkus` extension for `Jimmer`? I think that will be another way to reach a different _audience_.

**Comment by babyfish-ct** [comment]
Jimmer itself has a high degree of technical neutrality, making it easy for developers to combine it with any container management framework (such as Spring, Quarkus, Micronaut). For this reason, even early versions did not have built-in Spring Boot integration.

Considering the growing Quarkus community, there will be a built-in Quarkus integration solution in the future, so the answer to this question is affirmative.

However, the framework itself currently needs some improvement work. Quarkus integration will require a wait, not now. Please understand.

**Comment by flynndi** [comment]
https://github.com/flynndi/quarkus-jimmer-extension @x80486

**Comment by x80486** [comment]
@flynndi, this is great! Would you be willing to [host the extension](https://github.com/quarkusio/quarkus/issues/36308) in Quarkiverse?

**Comment by flynndi** [comment]
@x80486  There are still some functions that have not been completed. I want to wait until most functions are connected

**Comment by x80486** [comment]
That's OK. I just wanted to let you know, in case you were not aware of, that there was a "global" registry for these. It makes sense to submit it once it's stable and near to complete :rocket:

**Comment by babyfish-ct** [comment]
@x80486 A bug of Jimmer's GraphQL implementation has been found, Now it is fixed in `0.8.107`

Please join into jimmer's discord by the link of documentation to make sure no message will be missed.

**Comment by babyfish-ct** [comment]
Now, https://github.com/flynndi/quarkus-jimmer-extension is powerful enough
