### ISSUE TITLE
[Question] GraphQL example stills over fetches data when querying Books

### ISSUE THREAD

**Issue by x80486** [babyfish-ct/jimmer#281]
I'm currently testing `Jimmer`, but I'm more interested in the features that makes it more convenient than other solutions for `GraphQL`.

I ran the `Spring Boot` example, and I placed a query for books:

```javascript
query GetBooks {
  books {
    name
    authors {
      firstName
    }
  }
}
```

...but I got this in the application logs:

```shell
2023-10-05 11:27:41.187  INFO 2529 --- [io-8080-exec-10] o.b.jimmer.sql.runtime.ExecutorForLog    : Execute SQL===>
--- Business related stack trace information ---
org.babyfish.jimmer.sql.example.graphql.business.BookService.books(BookService.java:42)
Purpose: QUERY
SQL: select
    tb_1_.ID,
    tb_1_.CREATED_TIME,
    tb_1_.MODIFIED_TIME,
    tb_1_.TENANT,
    tb_1_.NAME,
    tb_1_.EDITION,
    tb_1_.PRICE,
    tb_1_.STORE_ID
from BOOK tb_1_
order by
    tb_1_.NAME asc,
    tb_1_.EDITION desc
JDBC response status: success
Time cost: 1ms
<===Execute SQL
2023-10-05 11:27:41.189  INFO 2529 --- [io-8080-exec-10] o.b.jimmer.sql.runtime.ExecutorForLog    : Execute SQL===>
Purpose: LOAD
SQL: select
    tb_2_.BOOK_ID,
    tb_1_.ID,
    tb_1_.CREATED_TIME,
    tb_1_.MODIFIED_TIME,
    tb_1_.FIRST_NAME,
    tb_1_.LAST_NAME,
    tb_1_.GENDER
from AUTHOR tb_1_
inner join BOOK_AUTHOR_MAPPING tb_2_
    on tb_1_.ID = tb_2_.AUTHOR_ID
where
    tb_2_.BOOK_ID in (
        ? /* 6 */, ? /* 5 */, ? /* 4 */, ? /* 12 */, ? /* 11 */, ? /* 10 */, ? /* 3 */, ? /* 2 */, ? /* 1 */, ? /* 9 */,
        ? /* 8 */, ? /* 7 */
    )
order by
    tb_1_.FIRST_NAME asc,
    tb_1_.LAST_NAME asc
JDBC response status: success
Time cost: 1ms
<===Execute SQL
```

I was expecting:

- Just one query — instead of two or more, and
- The generated SQL with just `book.name` and `author.first_name` — probably the IDs as well

Is this somehow a bug or am I wrong expecting `Jimmer` to behave in such way? If so, would it be a way to make it work in the way I'm describing this?

**Comment by babyfish-ct** [comment]
Yes, GraphQL is a solution that is not yet fully complete (currently, REST + ObjectFetcher does not have this problem). Jimmer's ORM core itself does not have this problem, because it was designed to solve this problem, but it faced some difficulties when integrating with third-party GraphQL ecosystems and made temporary compromises. A complete solution will be provided as soon as possible in the future.

BTW, if cache is enabled for some entity types, in order to cache useful objects instead of objects needed for specific scenarios, even REST + ObjectFetcher will cache objects with all scalar fields loaded. In this case, there is no problem with this.

**Comment by babyfish-ct** [comment]
After ORM become perfect, it is time to implement new GraphQL mechanism instead of spring GraphQL, but not now

**Comment by babyfish-ct** [comment]
0.8.98 brought qualitative changes to GraphQL.

1. Previous code is compatible. If you just want to keep running, no modifications are required.

2. Use the new feature, better performance will be obtained in non-cache mode.

First, add the new parameter `DataFetchingEnvironment env` to the GraphQL query method in the Controller.

Then, transform the `env` into a Fetcher

- Java: DataFetchingEnvironments.createFetcher(Book.class, env)

- Kotlin: env.toFetcher()

Finally, querying the data layer with this fetcher will get better performance.

Examples

**!!!Be careful!!!** 
**Examples have moved, old examples still exist temporarily to prevent a large number of dead links in the documentation**

- Java: https://github.com/babyfish-ct/jimmer-examples/tree/main/java/jimmer-sql-graphql
- Kotlin: https://github.com/babyfish-ct/jimmer-examples/tree/main/kotlin/jimmer-sql-graphql-kt

**Comment by babyfish-ct** [comment]
![c53cc5c5d1738986bd88d2c547c1a625](https://github.com/babyfish-ct/jimmer/assets/15168900/f4513429-2103-4476-88e6-c9cd305da062)
