### ISSUE TITLE
多数据源的repository问题

### ISSUE THREAD

**Issue by kukume** [babyfish-ct/jimmer#283]
我现在项目中绑定了多个数据源，并根据多个数据源创建了多个sqlClient

那么，每个repository可以指定对应的sqlClient吗？

在文档中发现好像只能指定一个sqlClient

**Comment by babyfish-ct** [comment]
默认情况下，spring boot starter提供的是单数据源。

如果有多数据源需要，可以定义多个SqlClient，但有一些注意事项。

由于工作量和时间的问题，目前文档展示没有书写多数据源的章节，可以从文档资源篇找到二维码，这是用户们曾经讨论过的问题。
