### ISSUE TITLE
[BUG] TypeScript 客户端类型映射存在问题

### ISSUE THREAD

**Issue by pot-mot** [babyfish-ct/jimmer#284]
| Java/Kotlin | TypeScript |
| --- | --- |
| Map<K, V> | 目前映射为 ReadonlyMap<K, V>，但对象实际类型应该为 { [key: K]: V }，即实际是个对象 |
| byte[] / ByteArray | 目前将 byte 映射为了一个单独的无属性对象类型从而映射为 byte[]，实际应该为 Blob |

除以上外希望 ts 客户端可以提供一个配置项调整是否启用 readonly。（在 vue 开发场景下 readonly 约束并无必要）

目前书写了一个简陋的脚本以替换 readonly 与部分接口类型：
```javascript
import fs from "fs";
import path from "path";

// 替换目录路径
const modelPath = 'src/api/__generated/model';
const servicePath = 'src/api/__generated/services';

// 递归遍历目录中的所有文件
function traverseDirectory(directoryPath) {
    const files = fs.readdirSync(directoryPath);

    files.forEach((file) => {
        const filePath = path.join(directoryPath, file);
        const stats = fs.statSync(filePath);

        if (stats.isDirectory()) {
            traverseDirectory(filePath);
        } else if (stats.isFile() && path.extname(filePath) === '.ts') {
            replaceInFile(filePath);
        }
    });
}

// 替换文件中的文本
function replaceInFile(filePath) {
    const fileContent = fs.readFileSync(filePath, 'utf8');
    const updatedContent = fileContent
        .replaceAll("readonly ", "")
        .replace(/ReadonlyArray<(\S+)>/g, "$1[]")
        .replaceAll("ReadonlyMap", "Map")
        .replace(/Map<(\S+), (\S+)>/g, "{ [key: $1]: $2 }");
    fs.writeFileSync(filePath, updatedContent, 'utf8');
}

// 执行替换操作
traverseDirectory(modelPath);
traverseDirectory(servicePath);

```

**Comment by babyfish-ct** [comment]
readonly开关可以加。

Map是翻译成TS的Map还是{}对象也可以加开关。

浏览器端有Blob类型吗？

**Comment by pot-mot** [comment]
此外还有新的问题，dto 中 is 开头的属性生成时会失去 is 前缀，原因是：
![image](https://github.com/babyfish-ct/jimmer/assets/112872898/b052e126-bb7d-4afd-9d37-dd572992bcce)
也许也可以通过全局配置项确认此类属性是否在映射时包含 is

**Comment by pot-mot** [comment]
然后前述的 byte 的较合理处理方式应该就是映射成 number 了，这样仅需要修改 TsCodeWriter 中的此处：
![image](https://github.com/babyfish-ct/jimmer/assets/112872898/c4bbe4ec-45ab-4532-b75a-07fdc3ae2b04)

以及 map 的映射应该需要在 TsCodeWriter 中的此处补充一个转换逻辑了：

![image](https://github.com/babyfish-ct/jimmer/assets/112872898/af426b74-47a8-47ba-b0f9-d450de14a288)

首先是需要 object

```java
code("{ [key: ");
        typeRef(mapType.getKeyType());
        code("]: ");
        typeRef(mapType.getValueType());
        code(" }");
```

然后是需要在 ts 代码中提供 object 至 map 的转换函数（以及比较要命的是 ts 中对象键只能是 string，所有没法整 K 泛型） 

```typescript
export const convertToMap = <V> (obj: { [key: string]: V }): Map<string, V> => {
    const map = new Map<string, V>();

    // 遍历对象中的每个键值对
    for (const key in obj) {
        if (obj.hasOwnProperty(key)) {
            const value = obj[key];
            // 使用 set 方法将键和值添加到 Map 中
            map.set(key, value);
        }
    }

    return map;
};
```

**Comment by babyfish-ct** [comment]
convertMap无法实现，因为没人知道对象的那个部分需要convert

一律翻译为对象，因为无论Java中Map的K是啥，Jackson序列化后key必然是string,  即，key必须为string是JSON格式的限制，Java的Map可以定义K类型无用。

**Comment by babyfish-ct** [comment]
Try `0.8.42`
