### ISSUE TITLE
代码生成问题

### ISSUE THREAD

**Issue by kukume** [babyfish-ct/jimmer#285]
我目前项目是java和kotlin混写，所以我想让java和kotlin代码都可以调用各自的SqlClient进行操作。
但是在代码生成的时候有问题，使用ksp去生成代码时，也会去对java的实体类进行生成而导致报错，翻了半天也没有找到ksp忽略对某些类的生成，而是在插件源代码上进行操作。
所以可以为ksp插件不对java代码进行生成代码操作吗？

**Comment by babyfish-ct** [comment]
抱歉，不支持Java/Kotlin混合编写，这个功能太过复杂。

**Comment by kukume** [comment]
我觉得，代码生成，apt只对应java的实体类生成，ksp只对应kotlin的实体类生成。
然后在调用SqlClient的时候，kotlin使用kotlin的api，java使用java的api。不是很复杂的。

**Comment by babyfish-ct** [comment]
Java实体和Kotlin实体之间并非孤立的，他们之间存在联系。

1. 如果各生成各的，生成后用户也无法使用，除非它们彼此不相呼引用

2. 生成源代码只是最简单的最后一步，在此之前需要分析对象之间的彼此依赖，ORM有太多元信息是单个类的元数据无法分析出来的，也有太多报错验证信息信息必须联合不同类型才能分析出来。所以jimmer-apt和jimmer-ksp的工作绝非lombok那样把每个类都当成孤岛处理就可以实现的，必须通盘考虑所有实体形成的关系模型（将两三个类型联合分析，其富足的是通盘联合分析一样，只要不是孤岛处理，联合处理多少个就不重要了），这就是我之前说的复杂的地方，相比而言，代码生成只是最简单的收尾。
