### ISSUE TITLE
[Bug]dto在编译过程中没有按照预期生成对应的Java类

### ISSUE THREAD

**Issue by s2485523800** [babyfish-ct/jimmer#289]
![b145175698a7e79223279b1d418fc79](https://github.com/babyfish-ct/jimmer/assets/73523505/24c2dbf5-ec08-417a-a420-59f2401652b6)
![09bfb78b9412c27798b8ea4505cf5e7](https://github.com/babyfish-ct/jimmer/assets/73523505/c79dd8ea-d129-4a4d-b1e6-fb1e9ac97b09)
### Java认为Onedrive路径不算目录,导致没有逐层扫描到dto后缀的文件

**Comment by babyfish-ct** [comment]
Try `0.8.32`
