### ISSUE TITLE
多module项目启动失败

### ISSUE THREAD

**Issue by hkhhh** [babyfish-ct/jimmer#29]
版本：0.6.18
详细描述:
在多module的spring boot项目中，尝试使用@EnableJimmerRepositories注解注入Jimmer Repositories，项目启动失败，提示找不到Jimmer Reposiories。
错误信息:
![image](https://user-images.githubusercontent.com/49685894/212249478-3810a150-d778-49ec-892e-34330f8d711a.png)
@EnableJimmerRepositories注解:
![image](https://user-images.githubusercontent.com/49685894/212249324-ed73f527-077a-40ef-b964-fccf2fe0d1dc.png)

**Comment by babyfish-ct** [comment]
0.6.52-0.7-preview
