### ISSUE TITLE
[BUG]在MySQL5.7.x版本中，delete语句别名语法错误

### ISSUE THREAD

**Issue by TokgoRonin** [babyfish-ct/jimmer#290]
jimmer版本0.8.21，MySQL版本5.7.x，使用以下语句创建的删除操作
```
sqlClient.createDelete(table)
```
生成的sql语句中带有别名：` delete from table_name table_alais `，这在MySQL 5.7版本中，会提示语法错误。

注：使用spring data风格的` repository.deleteById() `等方法生成的删除语句没有别名。

**Comment by babyfish-ct** [comment]
我这边没mysql 5.7, 你看看是不是没有设置MySQLDialect.

如果设定了，应该是`delete table_alias from table_name table_alias`

**Comment by TokgoRonin** [comment]
已解决，感谢
