### ISSUE TITLE
[BUG] PG jsonb 操作符被判识别为占位符

### ISSUE THREAD

**Issue by moyuqinsi** [babyfish-ct/jimmer#292]
`Long userCount = client.createQuery(memberTable)
.where(Predicate.sgl( sql: "%e ?& %v",memberTable.role(),  "array['USER']"))select(memberTable.role() .count()) .fetchOne() :`
?& 被识别为其中一个变量

**Comment by babyfish-ct** [comment]
这不是Jimmer的问题，是JDBC的问题。

解决方案：https://stackoverflow.com/questions/14779896/does-the-jdbc-spec-prevent-from-being-used-as-an-operator-outside-of-quotes

PG的JDBC驱动支持用`??`表示`?`，而非JDBC参数
