### ISSUE TITLE
[Feature Request] 复杂查询支持自循环调用检测

### ISSUE THREAD

**Issue by moyuqinsi** [babyfish-ct/jimmer#296]
当前版本：
0.8.23

需求：
当查询一个复杂计算的字段时，如果计算的实现是通过计算字段实体自身引发循环调用会导致出现 UnloadException 
虽然本质是用法存在错误，但是为了更友好的提示应该加入框架的检测提示

**Comment by babyfish-ct** [comment]
Try `0.8.32`
