### ISSUE TITLE
是否可以支持将表关系定义持久化到数据库里？

### ISSUE THREAD

**Issue by ymind** [babyfish-ct/jimmer#3]
提这个问题的时候我似乎意识到这与ksp可能有冲突，但我还是很好奇有没有这种可能性？

我希望将表关系的定义持久化是因为我希望能够在运行时动态配置他们，这样我就有可能实现通用数据访问层了。
进一步地，通过某种手段将查询操作符映射为字符串表达式，那么只要建个表就可以应对大多数的查询场景了。

**Comment by babyfish-ct** [comment]
目前暂无规划，因为jimmer主打强类型SQL DSL.
