### ISSUE TITLE
[BUG] 更新后枚举映射编译失败

### ISSUE THREAD

**Issue by EmyiaEllen** [babyfish-ct/jimmer#303]
目前这种写法编译不通过
![image](https://github.com/babyfish-ct/jimmer/assets/82955455/19482c9e-8f78-40ba-806a-e71ccf3b4b1d)
看了一下更新后的文件，将写法改成这种模式，仍然不通过
![image](https://github.com/babyfish-ct/jimmer/assets/82955455/70ca8d2e-8f27-48ea-a357-b2d672eb964c)
如果去掉引号，就识别为标识符了，而不是常量
![image](https://github.com/babyfish-ct/jimmer/assets/82955455/a2da1980-b262-4137-9156-f9b5134ec177)

----

环境: SpringBoot 3, Java 21, Jimmer 0.8.31

**Comment by babyfish-ct** [comment]
A -> {
   a: 1,
   b: 2
}
