### ISSUE TITLE
dto语言生成idView集合有问题

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#304]
![fa75668abd929cdde4b162a99d39040](https://github.com/babyfish-ct/jimmer/assets/38320937/42a8ed0b-8411-4318-9140-eff7f1bc8d2d)
![2226f0390d06f3043996a266a5047b2](https://github.com/babyfish-ct/jimmer/assets/38320937/f5c4367f-5418-478c-94cc-9e1712a5b6e7)
![caf1348580515cad1ea0710e8a73da9](https://github.com/babyfish-ct/jimmer/assets/38320937/11b35e58-ef7a-4c82-a0ed-18e3db2f2ea2)
![e3a79bf6e1209f75f602d85d3cf2761](https://github.com/babyfish-ct/jimmer/assets/38320937/ad6def5d-08f3-4d4c-94a2-7fb2305e3ddb)

**Comment by babyfish-ct** [comment]
Try `0.8.32`
