### ISSUE TITLE
[Feature]提供saveAll和saveAllCommand

### ISSUE THREAD

**Issue by TokgoRonin** [babyfish-ct/jimmer#308]
希望提供 saveAllCommand()用以批量保存实体。当前版本jimmer内部还是使用循环单条upsert的方式，效率较低，希望提供一个fastInsert/batchInsert，直接批量保存实体。

当前我在项目中的实现方式是手动unload关联对象，然后批量保存孤单对象，再用回填的ID去设置关联对象，再批量保存关联对象。这样的方式在关联层级较深或关联对象比较多时，比较麻烦。

**Comment by babyfish-ct** [comment]
Done
