### ISSUE TITLE
[Bug]只有一个属性的Dto无法正常生成kotlin代码

### ISSUE THREAD

**Issue by JackyLeeCS** [babyfish-ct/jimmer#309]
升级到`0.8.34`版本后，只有一个属性的Dto无法正常生成kotlin代码，以前是可以的
<img width="1192" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/00cf579b-52ba-4959-9c8a-e95763752330">
<img width="302" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/b23259b4-ce2d-4bd3-97a1-b8ffeff44255">

**Comment by babyfish-ct** [comment]
Try `0.8.35`

**Comment by JackyLeeCS** [comment]
可以了
