### ISSUE TITLE
dto语言的 unsafe input在内是空的情况下生成的hashCode方法中hash字段不存在

### ISSUE THREAD

**Issue by yangwulang** [babyfish-ct/jimmer#310]
dto语言的 unsafe input在内是空的情况下生成的hashCode方法中hash字段不存在

![微信图片_20231105103154](https://github.com/babyfish-ct/jimmer/assets/48119455/f5a0a282-028d-48c2-80b9-d58f7048e03e)
![微信图片_202311051031541](https://github.com/babyfish-ct/jimmer/assets/48119455/0ca7fdf0-67ca-437b-b706-021da1025c15)
![微信图片_202311051031542](https://github.com/babyfish-ct/jimmer/assets/48119455/33428c87-cc08-4575-8bf0-dea7f3fa2f1c)

如图

**Comment by babyfish-ct** [comment]
Try `0.8.36`
