### ISSUE TITLE
In the dto language, if an enum-mapping is used, the generated `DtoPropAccessor` has a string splicing error in the throw of its fourth parameter, `setterConverter`

### ISSUE THREAD

**Issue by ClearPlume** [babyfish-ct/jimmer#312]
The generated DtoPropAccessor looks like the following, the correct one should be `Illegal value ${'$'}{$it} for the enum type model.Gender`

![kotlin-dto-enum-accessor](https://github.com/babyfish-ct/jimmer/assets/18047536/22e80528-8609-4e5f-a569-81cb917ca4c1)

**Comment by babyfish-ct** [comment]
Try `0.8.36`
