### ISSUE TITLE
[BUG] 0.8.35 dto 中存在递归时编译失败

### ISSUE THREAD

**Issue by pot-mot** [babyfish-ct/jimmer#313]
dto：

![da762eb8658ea2511976f62163d8d60](https://github.com/babyfish-ct/jimmer/assets/112872898/dfad4ef9-ec97-4e90-9879-4d895a567b6b)

编译生成类：

![e1dd15a5db8a41e17b37757a18b4594](https://github.com/babyfish-ct/jimmer/assets/112872898/a6bed4fc-5428-4b7a-a82e-eae798be183f)

**Comment by babyfish-ct** [comment]
Try `0.8.36`
