### ISSUE TITLE
dto小语言在树递归查询时，只查询到了树的最后一级的上一级

### ISSUE THREAD

**Issue by yangwulang** [babyfish-ct/jimmer#314]
![image](https://github.com/babyfish-ct/jimmer/assets/48119455/3a50943a-6ddc-4091-b3a0-e1c55f63fee7)
![image](https://github.com/babyfish-ct/jimmer/assets/48119455/07c6e75e-ee1b-4cdb-8d4e-28ad7bb619ee)

**Comment by babyfish-ct** [comment]
Try `0.8.37`
