### ISSUE TITLE
[BUG] save 时动态设置 key setKeyProps 检查关联属性出错

### ISSUE THREAD

**Issue by pot-mot** [babyfish-ct/jimmer#319]
![image](https://github.com/babyfish-ct/jimmer/assets/112872898/ff3d89c2-0eec-4922-84de-bc59480d90e7)

![image](https://github.com/babyfish-ct/jimmer/assets/112872898/4e9d0e13-18ab-4cec-a5e4-6771f9b0676e)

```
java.lang.IllegalArgumentException: 'top.potmot.model.GenTable.schema' cannot be key property because it is not a scalar property with storage
```

**Comment by babyfish-ct** [comment]
Try `0.8.40`
