### ISSUE TITLE
何时发布新的Release并更新一下文档

### ISSUE THREAD

**Issue by EmyiaEllen** [babyfish-ct/jimmer#321]
目前 Github 的 release 已经停留在了 `0.8.23`, 但是实际上版本已经更新到了 `0.8.40`, 每次需要手动打开 commit 查看一下更新情况, 并且也不知道版本升级修复/发布了什么。

关于文档, 可以通过查看 commit 记录能够发现已经更新，但是文档页面还是没有变化

这是 doc 目录下有关 LogicDeleted 的一段文档。
![image](https://github.com/babyfish-ct/jimmer/assets/82955455/08832c83-5ff9-4295-b8c4-48ef60df0cd5)

这是文档页面实际所看到的内容
![image](https://github.com/babyfish-ct/jimmer/assets/82955455/87f07ff8-abbd-4aed-88e6-49cbdaf855e0)

其他方面的差别也有很多，基本上整个文档页面还是停留在 0.8.23 以前了

**Comment by babyfish-ct** [comment]
正在编写中，改动太大，稍等一两天
