### ISSUE TITLE
建议逻辑删除字段支持雪花id或者uuid

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#323]

**Comment by babyfish-ct** [comment]
Try `0.8.46`

LogicalDeteled flag可以是long/Long/UUID，是否为null无所谓。如果可null，【未删】值为null，否则，为0或00000000-0000-0000-0000-000000000000

此时LogicalDelete不能指定`value`，但可以执行generatorType或generatorRef，其中UUID可以不指定。
