### ISSUE TITLE
[BUG]SUPER QBE中like查询的^与$无效

### ISSUE THREAD

**Issue by JackyLeeCS** [babyfish-ct/jimmer#324]
jimmer版本：0.8.42
问题：SUPER QBE中like查询的`^`与`$`无效
生成的DTO是对的，但最终SQL中还是两个`%`都加上了

原始DTO:
<img width="207" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/416298da-1559-44ec-9031-be436c86bc91">

生成的kotlin文件：
<img width="880" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/36134fbb-fd0a-447d-8b30-a86e1052519e">

查询日志：
<img width="198" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/52d04505-cf65-4d55-8c44-31b43d5e7030">

**Comment by babyfish-ct** [comment]
Try `0.8.44`
