### ISSUE TITLE
[Feature] ts 生成枚举全部值的数组

### ISSUE THREAD

**Issue by pot-mot** [babyfish-ct/jimmer#329]
目前 ts 客户端生成的枚举是 type enumName = "item1" | "item2" | "item3"，而目前并没有较好的办法直接用 ts 在运行时获取枚举的全部选项，因此希望生成一个类似 const enumNames = ["item1", "item2", "item3"] 的数组。

**Comment by moeshin** [comment]
如果只生成数组，也可以推断出类型。

```ts
const enumNames = ["item1", "item2", "item3"] as const;
type enumName = typeof enumNames[number];
// type enumName = "item1" | "item2" | "item3";
```

**Comment by babyfish-ct** [comment]
Try `0.8.46`
