### ISSUE TITLE
生成ts.zip文件有一些小问题

### ISSUE THREAD

**Issue by auaa** [babyfish-ct/jimmer#33]
调用jimmer生成ts.zip接口时，如果是get请求，ts生成的时候，默认的是无参数的。
如:
```
async list(): Promise<
        List<OrderInfoDto['DEFAULT']>> {
```
spring controller中是有参数的，比如当前页码。
请帮忙看看是我什么地方没有配置正确吗？

**Comment by babyfish-ct** [comment]
缺@RequestParam，目前jimmer不会出处理annotation的参数。

用的参数时简单keyvalue组合形成的对象（目前暂时没支持）？

**Comment by auaa** [comment]
> 缺@RequestParam，目前jimmer不会出处理无annotation的参数。下个版本补上
> 
> 用的参数时简单keyvalue组合形成的对象（目前暂时没支持）？

对象传参数 有计划支持吗？

**Comment by auaa** [comment]
全部改为post请求就可以了。尽量少用get请求
