### ISSUE TITLE
enum如何自定义显示的内容呢？

### ISSUE THREAD

**Issue by auaa** [babyfish-ct/jimmer#34]
enum如何自定义显示的内容呢？

我在代码中只看到了EnumProvider相关的内容，目前应该是只能将数据库中的字段转换为 enum.name();

是否有其他的转换方法呢？

**Comment by auaa** [comment]
只看到案例中有如下代码
```
@EnumItem(name = "M")
    MALE,

    @EnumItem(name = "F")
    FEMALE
```
比如是否可以将F显示为“男”？

**Comment by babyfish-ct** [comment]
枚举并非位字典设计。字典应该是一个很简单的父对象，其它对象用many-to-one关联它，借助于ObjectFetcher，你可以和容易地把字典的所有信息附加在实体对象上返回。

枚举映射只为回答一个所有ORM都必须回答问题，如何把某一些映射成Java枚举，一种在Java IDE下有智能提示的固定选择，至于如何展示，上上层业务的事情。这个功能虽然简单，不符合你的字字典诉求，但直接的枚举映射是所有ORM必须有的简单功能，jimmer也不例外。
