### ISSUE TITLE
[BUG]升级到0.8.46版本后，dto语言在flat中使用id函数时无法正常生成对应的kotlin代码

### ISSUE THREAD

**Issue by JackyLeeCS** [babyfish-ct/jimmer#342]
升级到0.8.46版本后，dto语言在flat中使用id函数时无法正常生成对应的kotlin代码，0.8.42版本是正常的

dto语言：
<img width="401" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/141dd49b-5cf0-4d43-bb71-531cc2ee6839">

生成的代码：
<img width="881" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/f48bd75c-fc90-4dca-a09e-9226eda226b6">

错误信息：
<img width="1594" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/cdb0ac81-a9a1-4de6-b3c2-4b83ceaf2d7e">

**Comment by babyfish-ct** [comment]
试过很多方法，无法重现。但还是建议试试0.8.50（这部分有点变化）
