### ISSUE TITLE
[BUG]dto文件中禁止使用NotNull注解，从实体搬运的NotNull注解也会丢失message信息

### ISSUE THREAD

**Issue by TokgoRonin** [babyfish-ct/jimmer#345]
当前jimmer版本：0.8.11，JDK版本：1.8.351

如题，在dto文件中直接使用`@NotNull`注解会报错`Annotation whose simple name is "NotNull" is forbidden by DTO language`
如果不在dto文件中校验NotNull而采用从实体搬运的方式的话，生成的dto文件中，该注解的message也会丢失
如下：
```java
@Entity
public interface UserSimBind {
    //  已省略其他属性
    @NotNull(message = "ICCID号码不能为空")
    @NotBlank(message = "ICCID号码不能为空字符串")
    @Key
    String iccid();
}
```
dto文件定义
```java
input UserSimBindInput {
    //  已省略其他属性
    iccid
}
```

最终生成的文件：
```java
@Data
public class UserSimBindInput implements ViewableInput<UserSimBind> {
    // 已省略其他属性
    @NotNull
    @NotBlank(
            message = "ICCID号码不能为空字符串"
    )
    private String iccid;
}
```
可以看出生成的文件中，丢失了`@NotNull(message = "ICCID号码不能为空")`的`message`属性

**Comment by babyfish-ct** [comment]
Try `0.8.50`

**Comment by babyfish-ct** [comment]
Try `0.8.51`

注意，之前的问题不是搬运漏message，而是Nullity注解根本就不搬运(因为DTO对nullity有自己的见解)
