### ISSUE TITLE
value 作为实体类的字段时，生成的代码报错

### ISSUE THREAD

**Issue by ffggll** [babyfish-ct/jimmer#35]
版本：0.6.26
详细描述：value 作为实体类的字段时，生成的 Draft 文件里的实现类中的两个 __set 方法存在语法错误，类字段与方法参数重名，需要加上 this。
另外 IllegalArgumentException 里的错误信息，漏了属性名称后面的单引号。

![image](https://user-images.githubusercontent.com/31406551/218913622-c2d5668f-150b-48d3-934e-7abee72bd99b.png)

**Comment by babyfish-ct** [comment]
OK, 下个版本修复，现在，请先换个名字
