### ISSUE TITLE
0.8.51版本的DTO语言的重命名单个属性，生成的代码爆红，运行不了

### ISSUE THREAD

**Issue by mellivorines** [babyfish-ct/jimmer#352]
0.8.16版本DTO语言重命名单个属性运行正常，
0.8.51版本DTO语言重命名单个属性运行异常，
![408371701582147_ pic_hd](https://github.com/babyfish-ct/jimmer/assets/68333104/c21a5d29-e07a-4df5-901a-146a7ff922a7)

**Comment by mellivorines** [comment]
不是bug,0.8.51规范了命名

**Comment by babyfish-ct** [comment]
和#363重复，已经解决
