### ISSUE TITLE
复合字段问题

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#360]
1.加了复合字段后发现save不会diff了，破坏了幂等性
2.复合字段上加@Key会导致save时报错org.babyfish.jimmer.sql.runtime.SaveException: Save error caused by the path: "<root>": Key properties [xxxxxxxx] cannot guarantee uniqueness under that path
，@Key加在复合字段内的单字段上，编译时会报错（无有效日志输出）

**Comment by babyfish-ct** [comment]
经验值，此功能无任何问题。

问题的根源在于现有数据库中key已经出现了冲突（没有唯一性保证）
