### ISSUE TITLE
[BUG] There is a problem with the 'entity to input conversion constructor' in the generated input class when an alias is specified in the input dto

### ISSUE THREAD

**Issue by ClearPlume** [babyfish-ct/jimmer#363]
The input dto:

![input dto](https://github.com/babyfish-ct/jimmer/assets/18047536/a8c98428-96d2-4ca7-9f28-e4b359690dcb)

The generated input class:

![generated input class](https://github.com/babyfish-ct/jimmer/assets/18047536/9874ea57-28c0-4ecf-bfa7-95fdfe15cfd7)

It seems to me that there should be no need to convert from entity to input for the input dto to be correct.

**Comment by babyfish-ct** [comment]
Try `0.8.64`
