### ISSUE TITLE
IDEA: Cannot resolve configuration property `jimmer.client.openapi.properties`

### ISSUE THREAD

**Issue by moeshin** [babyfish-ct/jimmer#377]
![1e060245bfc773de5fcb7c5dbb5ac863](https://github.com/babyfish-ct/jimmer/assets/28248888/9283c6be-a211-4a5e-b32c-3f30e2afaaf3)

**Comment by moeshin** [comment]
好像是缺了构造方法

**Comment by babyfish-ct** [comment]
Try `0.8.79`, 一来没有安装spring插件，而来有点事要外出，自己验证一下
