### ISSUE TITLE
复合字段的ts可空性不对

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#380]
![84F614CE10EAEF035902EB738C5EA4D1](https://github.com/babyfish-ct/jimmer/assets/38320937/6196362b-ebc6-4dcb-9bf6-c2c67cb7d6a7)
![B5A9BC729D0DC8A2BDC3297EA211932D](https://github.com/babyfish-ct/jimmer/assets/38320937/f051e95f-6fe5-44cf-bb67-6fbe537548e1)

**Comment by babyfish-ct** [comment]
这个字段可以为null，但是，默认情况话，和TS更搭的是undefined.

如何要同时支持null和undefined，可以jimmer.client.ts.null-render-mode = NULL_OR_UNDEFINED
