### ISSUE TITLE
[Feature Request] Support sql array types

### ISSUE THREAD

**Issue by a8t3r** [babyfish-ct/jimmer#381]
Postgresql (and h2 partially) supports [arrays](https://www.postgresql.org/docs/current/arrays.html) data type:
```sql
create table book_store(
    id bigint primary key,
    author_ids  bigint[] not null
);
```

Association between `Book` and `Author` can be implemented without intermediate table:
```kotlin
@Entity
interface Book {
  
  // as bigint[] postgres type
  val authorIds: List<Long>
  
  @ManyToMany
  @JoinSql("(%target_alias.ID)=ANY(%alias.AUTHOR_IDS)")
  val authors: List<Author>
}

**Comment by babyfish-ct** [comment]
Code is changed as your suggestion, try `0.8.81`
