### ISSUE TITLE
多模块项目下，dto代码生成出错

### ISSUE THREAD

**Issue by llh4github** [babyfish-ct/jimmer#382]
多个模块里都存在dto文件夹，生成代码时出错。

![EM FY3FL2ZG`A~~X7LA8_HY](https://github.com/babyfish-ct/jimmer/assets/61351434/9584f6f9-7667-4f4d-a3a0-2d85fa3b4ac7)
User.dto(2)生成出错。

不太标准的多模块demo代码如下：
[demo2.zip](https://github.com/babyfish-ct/jimmer/files/13928830/demo2.zip)

**Comment by babyfish-ct** [comment]
扩展名不能dto2哦

**Comment by llh4github** [comment]
dto2 是测试只有一个模块有dto文件的情况，截图的时候忘了改。

demo里两个模块都是dto后缀。

新项目第一次好像能正常编译过，clean后再编译就出现问题了。

**Comment by babyfish-ct** [comment]
项目结构错误，多工程项目结构中，根项目只是一个容器，没有src。只有其下具体的子subproject才具备src，请参见标准例子jimmer-sql-kt

再次在正确的项目结构下验证多个工程生成DTO，无误
