### ISSUE TITLE
启用`org.gradle.caching=true`后，dto文件变化后不会重新编译

### ISSUE THREAD

**Issue by llh4github** [babyfish-ct/jimmer#384]
```
jdk = "21"
kotlin = "1.9.20"
ksp = "1.9.20-1.0.14"
springBoot = "3.2.1"
```

应该是gradle编译缓存功能造成的。

这个问题只能通过关闭缓存来解决吗？

**Comment by babyfish-ct** [comment]
是的，在不装IDEA插件的情况下，至少需要配套改变一个kt文件（文档已经说明，目前无法解决）。

所及，建议安装Intellij插件

**Comment by Enaium** [comment]
可以使用这个插件https://github.com/Enaium/jimmer-gradle
