### ISSUE TITLE
希望 openapi 文档可以定制统一的请求前缀，比如 `/api`

### ISSUE THREAD

**Issue by dejavuhuh** [babyfish-ct/jimmer#386]
比如在 Spring Boot 中可以通过如下方式给所有 `@RestController` 加上统一的请求前缀 `/api`
![f57b061aace07dd9d27a162cc245659d](https://github.com/babyfish-ct/jimmer/assets/65352984/985cff75-054a-459b-8bcb-a5f30b3c73af)
此时，希望生成的 openapi.yml 文档里面也能加上统一的请求前缀
![56482f2d092ff9066c4f34fbf64e06e0](https://github.com/babyfish-ct/jimmer/assets/65352984/947cc1ca-0c56-406d-8876-2cfd416f6dfb)

**Comment by babyfish-ct** [comment]
Try `0.8.81`

```
jimmer:
  client:
    url-prefix: /api
```
