### ISSUE TITLE
[Feature Request] Annotations in the dto language whose arguments do not support the class type of kotlin

### ISSUE THREAD

**Issue by ClearPlume** [babyfish-ct/jimmer#388]
Using annotations with kotlin kclass parameters in the dto language and their error reporting

![enum arg error in kotlin) 7{IDIKHW](https://github.com/babyfish-ct/jimmer/assets/18047536/3a0e89af-6bdf-48d6-a0a4-04b43a662d42)

Generated class

![Generated class](https://github.com/babyfish-ct/jimmer/assets/18047536/07a565c5-fdc4-44a5-90cf-8c3bf4011823)

I don't have a java jimmer project on my side, so I'm not sure what this usage is in java

Hopefully the dto language will add support for annotated kclass type parameters

**Comment by babyfish-ct** [comment]
Try `0.8.81`, 

The DTO plugin must be changed too, please view Dto.g4

```
classSuffix
    :
    '?'? ('.' | '::') 'class'
    ;
```

1. Both java style `.` and kotlin style `::` are supported

2. `?` can only be used by primitive type. For example `Int::class` means java's `int.class`, `Int?::class` means java's `Integer.class`

**Comment by ClearPlume** [comment]
Will do
