### ISSUE TITLE
现在没有配置枚举映射方式(name or ordinal)的选项，在普遍使用ordinal的情况下会比较麻烦

### ISSUE THREAD

**Issue by ClearPlume** [babyfish-ct/jimmer#39]
如下图所示，我需要对每一个枚举都用`EnumType`注解，对其中每一个值都使用`EnumItem`注解
> 枚举上的`EnumType`注解
![枚举上的`EnumType`注解](https://user-images.githubusercontent.com/18047536/221748045-3d7eda5c-46df-4af5-8684-3b337fad77e4.png)

> 枚举值上的`EnumItem`注解
![枚举值上的`EnumItem`注解](https://user-images.githubusercontent.com/18047536/221748118-c336c6ae-0453-40e6-83ff-7722c6f001c0.png)

**Comment by babyfish-ct** [comment]
0.7.9, 两种办法

1. SqlBuilder.setDefaultEnumStrateey
2. jimmer.defaultEnmumStrategy in application.yml
