### ISSUE TITLE
[Feature Request] Partial native query support

### ISSUE THREAD

**Issue by a8t3r** [babyfish-ct/jimmer#397]
When writing native queries, the documentation suggests:

> * For report queries that are not closely related to ORM, users expect to write complete Native SQL, then JdbcTemplate can be used directly, because Jimmer's transaction management is exactly the same as JdbcTemplate's.
>
> * For Jimmer's ORM-style queries, inject [Native SQL](https://babyfish-ct.github.io/jimmer/docs/query/native-sql) expressions in strongly typed SQL DSL.

The first method forces the user to duplicate functionality, for example in supporting dynamic filters, which is a very strong side of the jimmer that you don’t want to lose.
So I'm trying to reuse the predicate functionality:
```kotlin
val query = sql.createQuery(Book::class) {
            where(
                table.name.like("Eff"),
                table.authors {
                    firstName.like("Ev")
                }
            )
            select(value(1))
        }

val astContext = AstContext(sql.javaClient)
val sqlBuilder = SqlBuilder(astContext)

val impl = (ReflectionUtils.getFieldValue(query::class.java, "_javaQuery", query)
    .get() as ConfigurableRootQueryImpl<*, *>)

impl.baseQuery.applyVirtualPredicates(sqlBuilder.astContext)
impl.renderTo(sqlBuilder)

val where = sqlBuilder.build()._1.substringAfter("where ")
val finalQuery = nativeQuery + where + groupBy
jdbcTemplate.query(finalQuery, ...)
```
My suggestion is to make this a piece of code on the library side, for example:
```
KSqlClient.prepareQuery(entityType, block): SqlBuilder
```

But it would definitely be better to have support at the dsl level:
```kotlin
sql.createNativeQuery(Book::class,
    """
    select array_agg(tb_1_.name), count(distinct m.author_id)
    from book tb_1_
    join lateral (select author_id from book_author_mapping where tb_1_.id =book_id) m on true
    """) {
  where(
      table.name.like("Eff"),
      table.authors {
          firstName.like("Ev")
      }
  )
  select(
    table.fetch(BookAggregationView::class)
  )
}
```

**Comment by babyfish-ct** [comment]
This feature has been discussed by previous users and is not suitable for the current Jimmer.

This feature actually requires Jimmer to embed a small native sql framework, and the cost is disproportionate to the benefit. At present, Jimmer still has too many dreams to realize in the field it is good at, and it feels like there is really too little time, and it will be possible to consider this kind of feature after Jimmer is more complete and successfully promoted, not now.

JdbcTemplate is not sharp enough, the latest Spring Boot JDBC Client is recommended, it is more user-friendly than JdbcTemplate, and can better handle report-related NativeSQL tasks, you can try.
