### ISSUE TITLE
JdbcColNameTest Wrong?

### ISSUE THREAD

**Issue by VonSkiXD** [babyfish-ct/jimmer#4]
https://github.com/babyfish-ct/jimmer/blob/bfcf582e5cc794f74629aa4cb319f111951c1dd7/benchmark/src/main/java/org/babyfish/jimmer/benchmark/jdbc/JdbcDao.java#L52
看不懂为啥要一直setValue1
而且jdbcData并没有实际放入list?

而且建议有个discord,QQ群之类的讨论组

**Comment by babyfish-ct** [comment]
谢谢，观察仔细。

嗯，复制粘贴的锅。不过对性能没影响。

QQ群和其他交流方式今天之内到位

**Comment by babyfish-ct** [comment]
已修复，由于对性能没有影响，报告不用更新

**Comment by babyfish-ct** [comment]
哦，还忘了放进list

**Comment by babyfish-ct** [comment]
反复跑了两次，结果几乎没有影响，不用更新报告

**Comment by nanakura** [comment]
> 

请问qq群号是多少

**Comment by babyfish-ct** [comment]
是微信群，项目和文档上都有二维码

WanderRabbits ***@***.***> 于2022年9月12日周一 00:41写道：
