### ISSUE TITLE
可否将实体接口的注释搬到生成的DTO最终类当中

### ISSUE THREAD

**Issue by qinkangdeid** [babyfish-ct/jimmer#405]
# 版本

jimmer：0.8.84
开发语言：kotlin 1.9.22
构建工具：maven3

# 问题描述

目前通过openapi的形式可以给前端优秀的接口描述 
<img width="1343" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/17582522/d2c6fc3b-f34b-4dea-8494-495b4801a982">

接口文档虽说都可以提供前后端查看   有没有可能方便后端不看文档 

在项目里点击DTO生成的类直接查看注释
目前在dto文件里写的注释会搬到DTO最终生成类上   
 
 可否做到不在DTO文件里写注释的时候直接提取实体接口里的注释？

如果返回jimmer动态对象可以点击到实体接口 很方便 
但是使用dto生成类的时候没有注释 不够极致的方便 例如：
<img width="706" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/17582522/34b462f1-7c0e-4d69-94cb-136cbbbf7392">

可以生成注释 
<img width="649" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/17582522/6fd6534a-c0d7-4405-8529-1f013ba97376">

**Comment by babyfish-ct** [comment]
Try `0.8.90`
