### ISSUE TITLE
缺少生成Api文档路径错误

### ISSUE THREAD

**Issue by mtpkiss** [babyfish-ct/jimmer#407]
当@RequestMapping 注解加到class上,并且路径前没有/时候生成的文档出错

如下图所示

![e64fdffc3f2f67e619ab8a177867b354](https://github.com/babyfish-ct/jimmer/assets/3182367/46082e61-71f8-4c80-a6d4-73c3078866fd)
![b618d2a9a785c71ed9ab830db31c9afe](https://github.com/babyfish-ct/jimmer/assets/3182367/e348f9e7-bd9c-4807-ac28-22200677dfd9)

**Comment by babyfish-ct** [comment]
可以修复，修复前规避方式是写成/index

**Comment by babyfish-ct** [comment]
![image](https://github.com/babyfish-ct/jimmer/assets/15168900/ee7fb66f-d17c-4329-bfe2-61a59def6250)

一般而言，Spring MVC习惯如图所示。所以，即便问题修复后，也可以不用改回来，仍然/index

不过，这的确是个问题

**Comment by babyfish-ct** [comment]
Resolved very earilly, forgot the close it, Try newest version
