### ISSUE TITLE
实体中属性名定义为isDraft或draft会造成error

### ISSUE THREAD

**Issue by Xspana** [babyfish-ct/jimmer#411]
# 相关依赖版本

Jimmer：0.8.75
JDK：17.0.5

---

# 问题详细说明

在实体Article中定义了一个名为isDraft的属性，编译后会产生错误：**java: 不兼容的类型: com.eedt.entity.ArticleDraft无法转换为boolean**

Article.java

```java
@Entity
public interface Article {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    int id();

    //其它属性已省略

    /**
     * 是否为草稿
     */
    boolean isDraft();
}
```

经过Jimmer编译后的 ArticleDraft.java 中的内部类MapStruct：

ArticleDraft.java

```java
class MapStruct {
  private Integer id;

  private Boolean draft;

  public MapStruct id(Integer id) {
      this.id = id;
      return this;
  }

  public MapStruct draft(Boolean draft) {
      this.draft = draft;
      return this;
  }

  public MapStruct isDraft(Boolean draft) {
      return draft(draft);
  }

  public Article build() {
      return ArticleDraft.$.produce(draft -> {
          if (id != null) {
              draft.setId(id);
          }
          if (draft != null) {
              draft.setDraft(draft);  //问题出在这一行
          }
      });
  }
}
```

## 原因

实体Article中的属性isDraft在MapStruct被命名为**draft**（Boolean类型），而方法`ArticleDraft.$.produce`的参数中lambda表达式中的参数也为**draft**（ArticleDraft类型），于是就产生了冲突，在调用`draft.setDraft(draft)`时，传进去的并不是方法所需的Boolean类型的draft，而是lambda表达式中的ArticleDraft类型的draft，类型不一致，引发错误

![image-20240128151812525](https://github.com/babyfish-ct/jimmer/assets/105101580/21ea2f68-ac4c-4c32-94cb-6f2a7e02b3b1)

无论Article实体中的属性被命名为isDraft还是draft，都会被编译为draft，都会引发这个error

## 解决方案

生成代码时为变量添加this：

![image-20240128151733905](https://github.com/babyfish-ct/jimmer/assets/105101580/bf025141-4f7f-4643-b4d6-96c6be0641b1)

**Comment by babyfish-ct** [comment]
谢谢反馈和建议，目前在开发一个大功能，请先行换个名字规避，请稍等下个版本。

**Comment by Xspana** [comment]
好的 ，作者加油✊

**Comment by babyfish-ct** [comment]
Try `0.8.90`

**Comment by Xspana** [comment]
好的
