### ISSUE TITLE
openapi 接口类Controller的注释是否可以也生成

### ISSUE THREAD

**Issue by qinkangdeid** [babyfish-ct/jimmer#417]
# 版本
Jimmer：0.8.86
开发语言：kotlin  1.9.22
springboot：2.7.18
构建工具：maven3

# 问题描述

openapi 接口类Controller的注释是否可以也生成
目前生成的openapi Controller是没有注释的     

类：
```kotlin

/**
 * 角色管理
 *
 * @author qinkangdeid
 */
@RestController
@RequestMapping("roles")
class RoleManagedController(private val roleService: RoleService) {
    /**
     * 返回当前用户的树形菜单集合
     * @param query
     * @return
     */
    @GetMapping
    fun list(): DataResponse<List<@FetchBy("SIMPLE_FETCHER") Role>> =
        ok(roleService.list(SIMPLE_FETCHER))

    companion object {
        val SIMPLE_FETCHER = newFetcher(Role::class).by {
            allScalarFields()
        }
    }
}

```

生成的文档

<img width="483" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/17582522/2975abf8-4e69-495e-add0-b04989213cd6">

可否能把RoleManagedController的注释替换到类名？

**Comment by babyfish-ct** [comment]
OpenApi不支持类级别注释，你想替换的那个叫tag，是swagger用来分组的，不是注释。

且不论文档注释很长时取第一个非空白行这种骚操作，如果多个方法的tags想同，那么将会被分为同一组（事实上，这种分组就是模拟类）
