### ISSUE TITLE
[fr]建议在保存长关联时，对抢夺其他主记录的子对象的行为进行防御

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#425]
如：在保存bookstore时，会把其他bookstore相同name、edition相同的book抢夺过来。
1.长关联保存的子对象，一般是不可移交的
2.开发人员可能疏忽，忘记在多对一的关联上加@Key会导致此问题
3.此问题发生全程无感，难以察觉

**Comment by babyfish-ct** [comment]
save-comand重构完后加此功能更有性价比，现在加性价比超低

**Comment by babyfish-ct** [comment]
Try `0.8.158`
