### ISSUE TITLE
希望客户端异常类的 message 参数是可选的

### ISSUE THREAD

**Issue by dejavuhuh** [babyfish-ct/jimmer#427]
如下图所示，客户端异常对象的 message 字段是必填的：
<img width="514" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/65352984/b10deee8-f291-4e61-93d0-b41a0fee65c1">
而实际在基类上是可选的：
<img width="1512" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/65352984/8f1192c6-9692-49fd-be8e-84088eb6a97f">
希望这两处的定义保持一致

**Comment by babyfish-ct** [comment]
Try `0.8.94`
