### ISSUE TITLE
关于客户端生成的 TypeScript 代码的一些问题

### ISSUE THREAD

**Issue by dejavuhuh** [babyfish-ct/jimmer#428]
### 问题1：对于返回类型为`List<T>`的接口，在 TypeScript 中会被映射为`ReadonlyArray<T>`类型
<img width="1185" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/65352984/f5587c51-0571-4de3-8463-62016e844584">

由于`ReadonlyArray<T>`类型无法赋值给`Array<T>`类型的变量，导致在使用时，无法将接口的返回值传递给前端的展示组件。以常见的`Table`组件为例，考虑以下代码：

```typescript
function Demo() {
  const data: ReadonlyArray<any> = []
  return <Table data={data} />
}
```
会产生如下编译报错：
<img width="345" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/65352984/7c326a5f-a850-4da7-a963-aa8545828c2a">
<img width="969" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/65352984/463b92a0-d369-4016-81c4-1ab13760f967">
改成`Array<T>`类型后就可以了：
<img width="283" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/65352984/d6a86948-7724-4c92-8b12-470fa1e192e5">
> 当然，从`Table`组件的职责来考虑，其入参`data`定义为`ReadonlyArray<T>`类型其实是更为严谨的（因为理论上`Table`只负责展示，而不应该修改原数组），但现实情况是，大部分前端组件库在类型定义上并不会如此严苛，基本上都是定义为`T[]`或`Array<T>`类型，所以这个事情还挺尴尬的😓
### 建议：从`ReadonlyArray<T>`改为`Array<T>`
---
### 问题2：调用 API 的函数被定义为 class 的**成员函数**而非**箭头函数**，会导致`this`上下文丢失的问题
如下图所示，在成员函数中使用了`this`
<img width="1184" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/65352984/1f3eee7a-65bc-4e63-9ab7-adde2c19bb0f">
假如在其他地方将这个函数赋值给另外一个变量`fn`，并调用`fn`
<img width="375" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/65352984/bd1a9f6e-e806-4e98-bbbe-ba4d0d018a07">
就会导致`this`上下文丢失，从而引发报错：
<img width="418" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/65352984/70f51ab6-2b41-48f2-93b9-0beee10744fb">
同样的，在使用[TanStack/Query](https://github.com/TanStack/query)框架时，若直接将成员函数传递给`queryFn`，也会引发相同的问题：
<img width="386" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/65352984/b7b31683-44ee-4515-8590-d848996f773f">
改为`ES6`的箭头函数后，就可以了：
<img width="1177" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/65352984/703aa83e-e75a-4b53-8a02-9c265321aa5c">
### 建议：从 class 成员函数改为`ES6`的箭头函数

**Comment by pot-mot** [comment]
关于取消 Readonly 可以在后端设置参数：
```yml
jimmer:
  client:
    ts:
      path: /ts.zip
      mutable: true
```

**Comment by pot-mot** [comment]
关于 this 指向问题我一般如此声明：
```
const fn = () => api.xxxController.function
fn()
```

**Comment by babyfish-ct** [comment]
第一个问题 @pot-mot 已经回答

第二个问题在0.8.94解决。不过用途好小，只有无参数函数才用用，有参数的的还是要如下编写

```
const const [options, setOptions] = useImmer(...);

const { isLoading, data, error, refetch } = useQuery({
       queryKey: ["Books", options],
       queryFn: () => api.bookService.findBooks(options) 
});
```
