### ISSUE TITLE
Self-referential update of ARRAY field

### ISSUE THREAD

**Issue by ReBlast** [babyfish-ct/jimmer#430]
Hi, I'm new to this framework.
I have defined a `guilds` table in a Postgres database with a field of type `ARRAY` here:

```kt
@Table(name = "guilds")
@Entity
interface Guild {
  @Id
  val id: Long
  
  // ...
  
  val appsBlacklist: LongArray
}
```

```sql
CREATE TABLE guilds(
    id BIGINT NOT NULL PRIMARY KEY,
    apps_blacklist BIGINT[] NOT NULL DEFAULT '{}'
);
```

And I’d like to insert a value into the array. I could as well accomplish this by first querying the record and then updating it with the modified value. However, I’m wondering if there’s an equivalent to the following SQL statement in Jimmer:

```sql
UPDATE guilds SET apps_blacklist = apps_blacklist || ARRAY[data...]
```

**Comment by babyfish-ct** [comment]
Please use native expression: https://babyfish-ct.github.io/jimmer-doc/docs/query/native-sql

**Comment by ReBlast** [comment]
How would I use it with the save command?

**Comment by babyfish-ct** [comment]
https://babyfish-ct.github.io/jimmer-doc/docs/quick-view/save/

The real example is here: example/kotlin/jimmer-sql-kt, example/kotlin/save-command

**Comment by ReBlast** [comment]
Uh, I still couldn't manage to use native expressions in the save command. Do you happen to have a Discord account/server?

**Comment by babyfish-ct** [comment]
https://discord.com/channels/1016206034827743283/1154480714268540929

I created it, but I don't know whether is valid because nobody tried.

Limited by English ability, I can't make wonderful English videos, so I've been running the Chinese community (in fact, the effect is not as good as the English community, the Chinese community lacks thinking, and is deeply poisoned by MyBatis). Now it's time to build an English-language community.

Welcome to become my first Discord user.

Of course, I'm not familiar with discord, so let me know if I can't join if I'm building it wrong.

**Comment by ReBlast** [comment]
Hey! I'm really sorry to hear about the trouble you've been having with the Chinese community. When I discovered Jimmer, I was very impressed by the performance improvements that Jimmer provides compared to the rest of the frameworks. I believe this project deserves more recognition.
And regarding the server, the link you provided isn't the right one. Please follow these steps to get a valid invite link:

- Right-click on your server's logo.
- Choose `Invite People` highlighted in blue.
- A modal will show up with your invite link, which starts with `discord.gg/...`. That's the one you need.
- If you want to make sure the link never expires, click on `Edit invite link` and change `Expire After` to `Never`.

![invite](https://github.com/babyfish-ct/jimmer/assets/92883017/bb678a09-1110-486a-a293-d8c679037ebd)

I hope the new server will soon have its own supporting community!

**Comment by babyfish-ct** [comment]
Please try https://discord.gg/4ayWmpqjhm
