### ISSUE TITLE
关于不可变实体Entity的一些疑问

### ISSUE THREAD

**Issue by Heming9** [babyfish-ct/jimmer#432]
jimmer查询的实体都是不可变的，请问遇到下面的场景中该如何使用？

比如查询Post实体时怎么实现根据contentPurview设置的值决定能否返回content呀？ 通常的做法不是查询Post后根据字段条件将content置空或其他处理吗，但是查询出来的实体不可变时该怎么处理呢? 目前想到的办法一个是创建新实体，或者两次查询，请问有更好的办法吗?

伪代码: 
```
Post实体 {
    id: Long
    title: String
    content: String
    contentPurview: 公开 | 仅自己 | 粉丝
}
```

**Comment by pot-mot** [comment]
如果仅这种场景下需要缺失部分字段的话，可以使用工具类 unload 掉部分字段。
以及不可变对象并不意味着不能编辑，使用xxxDraft.produce 这样的标准途径即可。

**Comment by Heming9** [comment]
> 如果仅这种场景下需要缺失部分字段的话，可以使用工具类 unload 掉部分字段。 以及不可变对象并不意味着不能编辑，使用xxxDraft.produce 这样的标准途径即可。需要注意的是，经过produce后确实创建了一个新对象。
> 
> 具体文档请参考这篇：[操作可变 Draft](https://babyfish-ct.gitee.io/jimmer-doc/docs/object/tool#%E6%93%8D%E4%BD%9C%E5%8F%AF%E5%8F%98draft)

原来是这样，非常感谢回复
