### ISSUE TITLE
0.8.98 中 根据DataFetchingEnvironment收集查询字段时,应排除不在实体中的字段

### ISSUE THREAD

**Issue by aikin-vip** [babyfish-ct/jimmer#441]
![9a57b340cef9b45960127af0c6937091](https://github.com/babyfish-ct/jimmer/assets/64122272/d0f53404-5d6f-4485-942c-e912d06678cd)

![173b58feae97386fa9f20ce1db706448](https://github.com/babyfish-ct/jimmer/assets/64122272/81a05fe2-bca0-4221-94e3-2755bd4b7d8b)

![fd65e65d79ee47144d0dc60bf78304ee](https://github.com/babyfish-ct/jimmer/assets/64122272/47f5f639-f2b9-4494-82a9-5f8921e5397f)

![20d0904873ae99d53ce96370619929e5](https://github.com/babyfish-ct/jimmer/assets/64122272/9ac7c6c5-6aaa-4c51-ad3f-3b604eba35ac)

**Comment by babyfish-ct** [comment]
Try `0.8.99`

**Comment by babyfish-ct** [comment]
Try `0.8.100`
