### ISSUE TITLE
[Feature Request] 希望可以支持 OpenApi 的 tag description

### ISSUE THREAD

**Issue by dejavuhuh** [babyfish-ct/jimmer#452]
从官方的 [Swagger Editor](https://editor.swagger.io/) 中可以看到，tag 可以附带一段 description
<img width="1459" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/65352984/679de558-3001-498b-b0ed-ac2cd927d090">

**Comment by babyfish-ct** [comment]
Try `0.8.105`, using documentation comment
