### ISSUE TITLE
Json column doesn't correctly updated with H2

### ISSUE THREAD

**Issue by belovaf** [babyfish-ct/jimmer#456]
Some databases requires special syntax to update json columns.
For example, for h2:
```
update my_table set json_col = ? format json
```

Currently jimmer generates updates to h2 without this syntax which leads to a double-quoted string in DB.

**Comment by babyfish-ct** [comment]
I added unit test

- DDL & DML(With `format json`)
  ```
  create table medicine(
      id bigint not null primary key,
      tags json(200) not null
  );

insert into medicine(id, tags) values(
      1,
      '[{"name": "tag-1", "description": "tag-description-1"},{"name": "tag-2", "description": "tag-description-2"}]' format json
);
  ```
- Entity: https://github.com/babyfish-ct/jimmer/blob/dev/project/jimmer-sql/src/test/java/org/babyfish/jimmer/sql/model/json/Medicine.java

- Query: https://github.com/babyfish-ct/jimmer/blob/dev/project/jimmer-sql/src/test/java/org/babyfish/jimmer/sql/json/H2QueryTest.java

- Mutation: https://github.com/babyfish-ct/jimmer/blob/dev/project/jimmer-sql/src/test/java/org/babyfish/jimmer/sql/json/H2SaveTest.java

There is no problem, did you forget to decorate the json property by `@org.babyfish.jimmer.sql.Serialized`?

**Comment by belovaf** [comment]
Root problem is generated query:
in h2 every json column expresion must contains `format json`:
https://www.h2database.com/html/datatypes.html#json_type

**Comment by babyfish-ct** [comment]
Yes, you're right, H2 save it a string, WTF...

**Comment by belovaf** [comment]
You can look how hibernate solves this problem.
It has individual jdbc-type implementation for many databases.

For example:
https://github.com/hibernate/hibernate-orm/blob/b75f173318df22ed0af2179814059d7b8f0cfa7d/hibernate-core/src/main/java/org/hibernate/type/descriptor/jdbc/H2FormatJsonJdbcType.java#L20

**Comment by babyfish-ct** [comment]
Try `0.8.108` please
