### ISSUE TITLE
文档勘误

### ISSUE THREAD

**Issue by SWQXDBA** [babyfish-ct/jimmer#457]
项目介绍中-》
![image](https://github.com/babyfish-ct/jimmer/assets/76103126/453ac405-9e12-499e-81a0-615fc8749e99)

**Comment by Enaium** [comment]
https://github.com/babyfish-ct/jimmer-doc

这个是文档的仓库，可以在这里改

**Comment by babyfish-ct** [comment]
Change, please wait for next documentation publishing
