### ISSUE TITLE
[bug] Embeddable objects can't have @Serialized properties

### ISSUE THREAD

**Issue by belovaf** [babyfish-ct/jimmer#464]
```
@Embeddable
interface MyEmbeddable {
    @Serialized
    val someValue: Map<String, String>
}
```

MyEmbeddable.kt:10: Illegal property "MyEmbeddable.someValue", it cannot be decorated by @org.babyfish.jimmer.sql.Serialized because the declaring type "MyEmbeddable" is not decorated by [org.babyfish.jimmer.sql.Entity, org.babyfish.jimmer.sql.MappedSuperclass]

**Comment by babyfish-ct** [comment]
Try `0.8.110`
