### ISSUE TITLE
[fr] Add support to disable optimistic locking for save command

### ISSUE THREAD

**Issue by belovaf** [babyfish-ct/jimmer#469]
JPA supports `LockMode.NONE`.
In some cases it is desirable to completely disable any locking.

The syntax can be like this:
```
sql.save(case) {
  setLockType(AUTO | NONE | OPTIMISTIC | PESSIMISTIC)
}
```

**Comment by babyfish-ct** [comment]
Try `0.8.112` please, the configuration of save command provides `setLockMode`
