### ISSUE TITLE
[documentation] Provided link to Trigger Classification is broken

### ISSUE THREAD

**Issue by sudoHackIn** [babyfish-ct/jimmer#475]
On the page - https://babyfish-ct.gitee.io/jimmer-doc/en/docs/quick-view/standard-demo/ the link [Trigger Classification] https://babyfish-ct.gitee.io/jimmer-doc/en/docs/quick-view/standard-demo/#:~:text=Trigger%20Classification - is not working

**Comment by babyfish-ct** [comment]
OH...Thanks

English documentation should use github, not gitee

**Comment by babyfish-ct** [comment]
Fixed
