### ISSUE TITLE
[bug] Jimmer doesn't honor setAppendOnlyAll() if associated entity contains @Key

### ISSUE THREAD

**Issue by belovaf** [babyfish-ct/jimmer#483]
If an associated ToMany entity contains @Key `setAppendOnlyAll()` is ignored and jimmer always tries to select the association.

**Comment by babyfish-ct** [comment]
Try `0.8.117`

1. `setMergeMode` and `setAppendOnly` are deleted, there are replaced by `setAssociatedModeAll` and `setAssociatedMode`

2. shortcut function `merge` is NOT changed.

3. and new function shortcut function `append`(Forget one thing, now it is `upsert root + insert associated objects`, in next version, it will be changed to `insert root + insert associated objects`)
