### ISSUE TITLE
[BUG]openapi模型的可空性丢失了

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#490]
![MEZ1CRHTQG8Z2EWRZPTN8L8](https://github.com/babyfish-ct/jimmer/assets/38320937/aa948e79-8ba5-4e57-8980-158b9ee0dedf)
![H{G}$WOUAP{1SP( H 5_@$H](https://github.com/babyfish-ct/jimmer/assets/38320937/7d525bdb-f859-4922-96f1-f6cd63568ee1)

**Comment by babyfish-ct** [comment]
这根本不是BUG，这是类型定义(靠nullable = false)，不是参数定义(靠required = true)

反而是另外一个问题，这个雷只是spring boot代码阻止需要，不应该进入OpenApi，此类型应该从OpenAPI中去掉

Try `0.9.116`
