### ISSUE TITLE
0.8.116 openapi有问题

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#497]
<img width="742" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/38320937/1f4e51aa-5b49-4610-af90-2939c363bc68">
<img width="984" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/38320937/27500d23-8fe7-4a6d-bdf6-ed16703d8b62">

**Comment by babyfish-ct** [comment]
Try `0.8.117`
