### ISSUE TITLE
How to deal with JavaEE Universal Response under kotlin

### ISSUE THREAD

**Issue by flynndi** [babyfish-ct/jimmer#502]
JavaEE's response has an attribute that is parsed to kotlin.array by Jimmer's openApi under kotlin

Response like
```
public abstract class Response implements AutoCloseable {
        public abstract Locale getLanguage();
}
```

Locale is a property whose type resolves to kotlin.array in a kotlin environment
This causes Jimmer's openapi to fail to parse
I wonder how this should be solved

Report code
https://github.com/flynndi/quarkus-jimmer-extension-example

Visit the website
http://localhost:9001/openapi.html

**Comment by babyfish-ct** [comment]
Try `0.8.119`, new request/response will be ingored

**Comment by flynndi** [comment]
![1608802417](https://github.com/babyfish-ct/jimmer/assets/129767847/f99cb1aa-f6c3-4c56-92e0-16ac4144c10f)

The problem seems to persist

**Comment by flynndi** [comment]
![1608802417](https://github.com/babyfish-ct/jimmer/assets/129767847/ad5efab1-96dc-4d26-a763-20db9e454cb8)


![1608802417](https://github.com/babyfish-ct/jimmer/assets/129767847/e5b0622c-c535-41b5-b6d7-d87046687fca)

The problem seems to persist
