### ISSUE TITLE
[feature request] 希望在database-validation中对错误提示更明确的指出数据库名表名

### ISSUE THREAD

**Issue by xflcx1991** [babyfish-ct/jimmer#504]
构造一个这样的例子，Entity定义用Integer，而表中用not null，此时报错没有指出表名
![image](https://github.com/babyfish-ct/jimmer/assets/3775351/dc88cd00-2a7f-4209-a3bc-9493889778ff)

能不能如绿色字显示的那样加上数据库表名呢，因为全限定类名已经提供了，再提供表名能更明确的让使用者知道自己表名映射
![image](https://github.com/babyfish-ct/jimmer/assets/3775351/d4a66306-cb2c-4237-926d-654b61d97e79)

**Comment by babyfish-ct** [comment]
Try `0.8.121`

**Comment by xflcx1991** [comment]
> Try `0.8.121`
0.8.122 生效了
![图片](https://github.com/babyfish-ct/jimmer/assets/3775351/120709d7-ada4-4ca0-8973-f0119c7c45f9)
