### ISSUE TITLE
抓取“关联属性”的“计算属性”没有返回

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#507]
![ab96a86bb71883fb1e472a8e92a1c528](https://github.com/babyfish-ct/jimmer/assets/38320937/65747f3f-5f13-4deb-ac33-4d2fdbef331b)
![ea719ec7c24703119310292e8dd1de2d](https://github.com/babyfish-ct/jimmer/assets/38320937/2073961d-fa1d-4625-a37b-84991bd2884b)
![287bbf7cffa67eabf62ee7da6424f5d3](https://github.com/babyfish-ct/jimmer/assets/38320937/7847a0cd-4c3f-4abb-9642-ae91794ef2fc)

**Comment by sunshio** [comment]
确认是开启缓存后出现的（并没有开启计算缓存）

**Comment by babyfish-ct** [comment]
Try `0.8.122`
