### ISSUE TITLE
建议repository根据返回类型决定返回值

### ISSUE THREAD

**Issue by Enaium** [babyfish-ct/jimmer#51]
![](https://user-images.githubusercontent.com/32991121/228140531-57aeb8a1-25f5-4480-88a8-48103472dd16.png)
当返回值是null的时候，返回类型只能是集合，希望根据返回值类型为Optional或kotlin返回可空时，返回Optional或者null
![](https://user-images.githubusercontent.com/32991121/228141455-541fae95-3612-423b-98fe-b16370bcf78d.png)

**Comment by babyfish-ct** [comment]
Try 0.7.15

**Comment by Enaium** [comment]
好了
