### ISSUE TITLE
[fr] Support embeddable types as top level classes in DTO language

### ISSUE THREAD

**Issue by belovaf** [babyfish-ct/jimmer#511]
It is very common to accept a part of entity from a controller, save it to a db, and then show it from another controller.
In such cases embeddable objects are perfect fit.
Unfortunately for now embeddable objects can't be safely used as input dto because they may have unloaded fields (if such fields are absent in json).
It would very convenient to create input dtos for embeddable objects with jimmer dto language to reduce mapping boilerplate.

**Comment by babyfish-ct** [comment]
Try `0.8.122`
