### ISSUE TITLE
[BUG] Specifation 中 associatedIdEq 无法正常应用

### ISSUE THREAD

**Issue by pot-mot** [babyfish-ct/jimmer#513]
[DtoPropBuilder.java](https://github.com/babyfish-ct/jimmer/blob/dev/project/jimmer-dto-compiler/src/main/java/org/babyfish/jimmer/dto/compiler/DtoPropBuilder.java) 自 218 行开始的 switch 缺少了对 associatedIdEq 的校验和break，因此导致出现 `the function name of specification type must be …` 的报错

**Comment by Enaium** [comment]
确定不是`associatedIdEq`？
