### ISSUE TITLE
使用@Serialized映射postgresql的json字段，更新出错

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#517]
<img width="1068" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/38320937/66bc336b-e140-4194-ab71-b180ccefa859">
是Array形式的json

**Comment by sunshio** [comment]
ERROR: column "xxx" is of type json but expression is of type character varying

**Comment by sunshio** [comment]
> PG下，序列化字段类型请用JSONB

![be81c3a2a21711e76446cb16dc83eccb](https://github.com/babyfish-ct/jimmer/assets/38320937/02080826-b077-4e4b-953b-0c6323d94515)
已解决

**Comment by babyfish-ct** [comment]
但是把PG字段类型设置成JSONB仍然是更好的选择，推荐

- 即使绕过Jimmer，底层数据库也可以拒绝非法录入

- 可以使用Natvie SQL，发挥PG操作Jimmer内部字段的能力，而非仅仅把JSON作为一个黑盒整体。
