### ISSUE TITLE
文档错误extends ScalarProvider应为implements ScalarProvider

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#518]
<img width="721" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/38320937/55937ded-f1a6-4bd7-9864-4f7d306e09a4">

**Comment by belovaf** [comment]
Now we have `AbstractScalarProvider` which can be used in such simple cases.
Just replace `ScalarProvider` with `AbstractScalarProvider`.
