### ISSUE TITLE
[fr]重要！希望解决input dto空字段导致的丢数据风险

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#519]
而我确信这可以做到,可以加fr了

一方面, 让静态input dto拒绝接受残缺的反序列化，提示客户端要么把所有值上传，要么改用动态input dto. 让jimmer能够发现这种问题

另外一方面, 如果使用了jimmer的ts自动生成, 在编译层面强迫前端这么干

**Comment by babyfish-ct** [comment]
Try `0.8.123`
