### ISSUE TITLE
[fr] Optimize all queries with `in` predicate with array parameter (if supported by DB)

### ISSUE THREAD

**Issue by belovaf** [babyfish-ct/jimmer#521]
For example on postgresql we can optimize query
`select * from my_entity where id in (?,?,?,?)` like this:
`select * from my_entity where id = any(?)` where the single array parameter is set with `PreparedStatement::setArray`.

**Comment by belovaf** [comment]
While this can eliminate a hard parsing it can work slower.
I think it should be benchmarked before implementation.
Here is a good article about this problem and some outdates benchmarks:
https://blog.jooq.org/sql-in-predicate-with-in-list-or-with-array-which-is-faster

**Comment by babyfish-ct** [comment]
Try `0.8.129`
1. Single column in-collection predicate
2. Use dialect whose `isAnyArraySupported` returns true such as Postgres
3. The property returns long/Long, or the `sqlType` or @Column is specified
