### ISSUE TITLE
关于默认脱钩行为的文档错误

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#523]
![image](https://github.com/babyfish-ct/jimmer/assets/38320937/c383f87e-07b4-498d-902c-784a5367f977)
实际测试默认为true

**Comment by sunshio** [comment]
![image](https://github.com/babyfish-ct/jimmer/assets/38320937/256a637a-d687-40fa-9441-e5313aff7fc9)

**Comment by babyfish-ct** [comment]
Changed, please wait for next documentation release
