### ISSUE TITLE
[fr] Add concise syntax for creating ToMany associations in save command

### ISSUE THREAD

**Issue by belovaf** [babyfish-ct/jimmer#532]
Very often I have some collection and I need to map it and add to ToMany association property.
Currently I have 2 options:
1) map the collection to entities directly and assign it
2) programmatically call addBy for each collection element

I think it would be very convenient to have an overloaded method, which takes any collection and a draft as a receiver.

```
val bookDtos = listOf(...)

val store = BookStore {
  books(bookDtos) {
    name = it.name
    price = it.price
  } 
}
```

**Comment by babyfish-ct** [comment]
No, this manual mapping which is conflict with DTO language.

It should be 
```
val store = BookStore {
   books(bookDtos, BookDTO::toEntity)
}
```

**Comment by belovaf** [comment]
Ok.
