### ISSUE TITLE
希望可以支持List<whereObject>的批量查询

### ISSUE THREAD

**Issue by zxzf1234** [babyfish-ct/jimmer#534]
有个业务场景是前端传参是List<whereObject>， whereObject有name、nameCode、nameNo等字段
如果只用mysql，需要将List<whereObject> 放入临时表 tmp_table(name, nameCode, nameNo)
然后执行sql  select * from tableA inner join tmp_table on tableA.name =  tmp_table.name AND tableA.nameCode=  tmp_table.nameCode and tableA.nameNo=  tmp_table.nameNo

前端无法传tableA的主键，因为name、nameCode、nameNo等字段是从tableB表上获取的，目前只能一条条执行

**Comment by babyfish-ct** [comment]
1. Convert where object to Tuple3
```
private static Tuple3<String, String, String> toTuple(WhereObject wo) {
     return new Tuple3<>(wo.getName(), wo.getNameCode(), wo.getNameNo());
}
```

2. Implement simple query by list checkin of SQL
```
ATable table = ATable.$;
List<A> entities = sqlClient
     .createQuery(table)
     where(
        Expression.tuple(
            table,name(), 
            table.nameCode(), 
            table.nameNo())
    ).in(
       whereObjects
          .stream()
           .map(MyClass::toTuple)
           .collect(Collectors.toList())
    )
    .select(table)
    .execute();
```

**Comment by zxzf1234** [comment]
如果WhereObject 有字段是LocalDateTime类型的，mysql和java都有可能是null，执行会报错，这个该怎么处理？

**Comment by babyfish-ct** [comment]
方法二

ATable table = ATable.$;
List<Predicate> predicates = new ArrayList<>(); //Preicate of Jimmer, not jdk
for (WhereObject wo : whereObject) {
    predicates.add(
        Predicate.and(
           Predicate.sql(
               "case when %e is null then %v is null else %e = %v", 
               table.name(), 
               wo.getName(), 
               table.name(), 
               wo.getName()
            )
        ),
        Predicate.sql(同上，如法炮制nameCode),
        Predicate.sql(同上，如法炮制nameNode)
    );
}
Predicate finalPredicate = Predicate.or(predicates.toArray(new Predicate[0]));

List<A> entities = sqlClient
     .createQuery(table)
     where(finalPredicate)
    .select(table)
    .execute();

**Comment by babyfish-ct** [comment]
方法一，建议对三个字段coalesce结构的形成的tuple建立函数索引。

正常数据都应该有，MySQL特殊，从8开始支持
