### ISSUE TITLE
dto中的注解编译报错

### ISSUE THREAD

**Issue by JackyLeeCS** [babyfish-ct/jimmer#537]
1. 注解的值为数组时，编译后的java代码多了一层括号导致报错，同样的代码在111版本是可以正常工作的
<img width="545" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/93ae321b-cdde-40c4-bd7d-f35f39b12dfe">
<img width="774" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/b8a3cf97-d796-4358-a30e-42beca861854">
<img width="991" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/ec16658a-328a-4317-bffa-5ab830dfed1a">

2. 注解编译后的kotlin代码中，加了`@property`导致报错
<img width="456" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/64f7971c-20f6-41ea-837f-eb18e15b96ab">
<img width="508" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/e18350a6-ae57-4117-8b1b-f98fbc4c97b7">
<img width="992" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/c3ff3753-bb2b-48d2-80b2-bffaf2aff6d7">

**Comment by Enaium** [comment]
你是在kotlin项目编译JavaDTO?,在Java项目上复现不了不了

**Comment by JackyLeeCS** [comment]
> 你是在kotlin项目编译JavaDTO?,在Java项目上复现不了不了

是个纯kotlin项目，报错的java文件是在编译的临时目录下
<img width="1331" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/78f84418-c9ea-4d4e-beb5-9d0d0d9a71f8">

**Comment by Enaium** [comment]
> > 你是在kotlin项目编译JavaDTO?,在Java项目上复现不了不了
> 
> 是个纯kotlin项目，报错的java文件是在编译的临时目录下
> <img width="1331" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/78f84418-c9ea-4d4e-beb5-9d0d0d9a71f8">
> 

纯kotlin项目怎么还用jimmer的apt

**Comment by JackyLeeCS** [comment]
> > > 你是在kotlin项目编译JavaDTO?,在Java项目上复现不了不了
> > 
> > 
> > 是个纯kotlin项目，报错的java文件是在编译的临时目录下
> > <img alt="image" width="1331" src="https://private-user-images.githubusercontent.com/8992971/324157820-78f84418-c9ea-4d4e-beb5-9d0d0d9a71f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1OTM2MTAsIm5iZiI6MTcxMzU5MzMxMCwicGF0aCI6Ii84OTkyOTcxLzMyNDE1NzgyMC03OGY4NDQxOC1jOWVhLTRkNGUtYmViNS05ZDBkMGQ5YTcxZjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjBUMDYwODMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTBjZjRkZmVlODg0NmE5NmQ0ZDQ1ZTk4NTI3YWQyM2JhNzdiZWRjYmU0NzgwYjVmNGJjZGFlMjk3MDhmNjM4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KD53rFxQeL7pzB7owOCT0SvaGQVykDa4yT2r6yr-zfc">
> 
> 纯kotlin项目怎么还用jimmer的apt

jimmer的依赖只有这两个
<img width="931" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/71d87971-d6ab-45f9-b891-29005089fabd">

**Comment by Enaium** [comment]
看gradle build文件

**Comment by JackyLeeCS** [comment]
没有加apt依赖
<img width="949" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/5db4f106-376b-4c87-a41c-37dc63faae9a">

**Comment by Enaium** [comment]
> 没有加apt依赖
> <img width="949" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/5db4f106-376b-4c87-a41c-37dc63faae9a">
> 

util项目呢

**Comment by JackyLeeCS** [comment]
都没有加，到111版本也是正常的

<img width="711" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/b114c67c-975e-4c5b-a68d-3ee785734442">

**Comment by Enaium** [comment]
> > 你是在kotlin项目编译JavaDTO?,在Java项目上复现不了不了
> 
> 是个纯kotlin项目，报错的java文件是在编译的临时目录下 <img alt="image" width="1331" src="https://private-user-images.githubusercontent.com/8992971/324157820-78f84418-c9ea-4d4e-beb5-9d0d0d9a71f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1OTU4MzMsIm5iZiI6MTcxMzU5NTUzMywicGF0aCI6Ii84OTkyOTcxLzMyNDE1NzgyMC03OGY4NDQxOC1jOWVhLTRkNGUtYmViNS05ZDBkMGQ5YTcxZjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjBUMDY0NTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjMwZWUzZmE4MjhiMDg0YTg1Zjc1ZTNjNWZhOTk4NWE3ZGVhZjMwNzM3NDBmYWVlYTlhODIzMmRiZmE2OWZmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Gq0VTYETUBmsnLEBfcNpV14lN-34aY0LWq9I0YYEvfw">

只有这个一个dto是java的还是所有的dto都有java的

**Comment by JackyLeeCS** [comment]
都会生成，找到原因了，用了kapt插件以后就会生成这些java文件，去掉以后就正常了
<img width="597" alt="image" src="https://github.com/babyfish-ct/jimmer/assets/8992971/259f3c2c-463a-4d3e-bdf0-ddc03e50f7a6">

**Comment by Enaium** [comment]
jimmer的starter会带apt，排除一下也行

**Comment by JackyLeeCS** [comment]
> jimmer的starter会带apt，排除一下也行

好的，第2个`@property`的问题还是存在，想用`Eacyexcel`里的注解就会报错

**Comment by babyfish-ct** [comment]
Try `0.8.127`
