### ISSUE TITLE
数据库一对多多对一数据库未建外键，findAll报错

### ISSUE THREAD

**Issue by jumper-developer** [babyfish-ct/jimmer#55]
![ba903d0b2fe87f6f767e660c5a5b238](https://user-images.githubusercontent.com/45511151/230753617-0f240461-bd97-4b2f-a8ed-2d7858cfca83.png)
![1e62fc0d589210ee84023d9e57737b0](https://user-images.githubusercontent.com/45511151/230753643-250aa3db-a29f-4c7b-9581-244940859dba.png)
![3df45bf781627903909581ee99040da](https://user-images.githubusercontent.com/45511151/230753656-3440cb18-5a7d-47e9-9ea3-32f079a773f5.png)
![d032054bacbeaa405164de69388d30b](https://user-images.githubusercontent.com/45511151/230753659-40e10380-324b-48bf-9023-4b0f9582ce2a.png)

**Comment by jumper-developer** [comment]
organization_rel表跟本次issue没关系，忽略

**Comment by jumper-developer** [comment]
当前版本不报错的写法 
![image](https://user-images.githubusercontent.com/45511151/230753992-362a3e71-0c8d-4826-8d58-1c215f2f7752.png)

**Comment by jumper-developer** [comment]
查询parent一直显示为null，实际上应该有值
![image](https://user-images.githubusercontent.com/45511151/230754163-8aa5c6e4-dde1-4251-bb78-22761792f859.png)

**Comment by babyfish-ct** [comment]
Try 0.7.29
