### ISSUE TITLE
[Feature Request] exclude specific fields from default `allScalars`

### ISSUE THREAD

**Issue by ArgonarioD** [babyfish-ct/jimmer#550]
## Overview

I am reaching out to propose an enhancement for the `User` entity class that focuses on securing the `password` field. The objective is to ensure that the `password` field is not retrievable or exposed in common operations. This precaution should extend across various layers, including DTOs, Swagger UI, and client-side code generation.

In my opinion, if the `password` field could be treated like the logical deletion strategy, where it remains invisible and inaccessible during default `allScalars` queries and data handling processes, it would be beneficial in similar contexts.

**Comment by belovaf** [comment]
This is already supported.

You can extract a `@MappedSuperclass UserNonSecureFields` and use it in a DTO language:
```
User {
  #allScalars(UserNonSecureFields)
}
```

**Comment by ArgonarioD** [comment]
> This is already supported.
> 
> You can extract a `@MappedSuperclass UserNonSecureFields` and use it in a DTO language:
> 
> ```
> User {
>   #allScalars(UserNonSecureFields)
> }
> ```

You’re right, that approach could indeed achieve a similar outcome. However, I personally think that if the features I mentioned above could be implemented, it would make the usage much more convenient and elegant, and make Jimmer more wonderful.

**Comment by babyfish-ct** [comment]
Try `0.8.129`

The annotation is `@ExcludedFromAllScalars`
