### ISSUE TITLE
[Feature Request] Enhance exception messages for client-side generation

### ISSUE THREAD

**Issue by ArgonarioD** [babyfish-ct/jimmer#551]
Currently, the client-side generation process (including OpenAPI and TypeScript code generation) lacks comprehensive error messaging when metadata is absent, such as in cases where api methods lack public permissions.

I recommend that, in addition to improvements at the aforementioned points, debugging directions could also be outlined in the documentation.

**Comment by babyfish-ct** [comment]
Try `0.8.129`
