### ISSUE TITLE
[bug] openApi网页不RequestBody 显示的接口

### ISSUE THREAD

**Issue by realreus319** [babyfish-ct/jimmer#554]
将 RestController 和ResponseBody 的Dto写在一个文件中，会导致这个接口不在openApi上展示出来
![image](https://github.com/babyfish-ct/jimmer/assets/108124249/7b2abad7-fc31-441c-91fb-5a93714fb86a)

**Comment by babyfish-ct** [comment]
Try `0.8.131`
