### ISSUE TITLE
[fr]考虑一下生产环境下路径会被转的场景

### ISSUE THREAD

**Issue by realreus319** [babyfish-ct/jimmer#560]
当接口被上游转发时，会导致openapi.html找不到openapi.yml，请考虑生产环境下路径会被转的场景
![LT%6ST_U@50URL36UDD}(YI](https://github.com/babyfish-ct/jimmer/assets/108124249/22cd549f-9aa5-42e1-8a79-8428e7883fae)

**Comment by babyfish-ct** [comment]
Try `0.8.131`

- `jimmer.client.openapi.path` can be relative path without the the prefix '/'
- `jimmer.client.openapi.ref-path` is supported, it can be used specify the link path in html
