### ISSUE TITLE
[Bug] DTO `as` nested, generated fields is different

### ISSUE THREAD

**Issue by moeshin** [babyfish-ct/jimmer#562]
![f9eba97ae3c9e313000eef8f79afdc73](https://github.com/babyfish-ct/jimmer/assets/28248888/8681f74d-7347-42d2-9c78-042760234641)
![c98a4c351a972a8d547021add9c4da95](https://github.com/babyfish-ct/jimmer/assets/28248888/6ede3b24-91ca-4476-907c-7d989cf8cfe3)

**Comment by babyfish-ct** [comment]
Try `0.8.131`
