### ISSUE TITLE
这套框架能否实现类似mybatis plus acticerecord模式的效果

### ISSUE THREAD

**Issue by 1741432465** [babyfish-ct/jimmer#563]
例如 Book book
book.insert()
book.update()
book.delete()

文档：https://baomidou.com/pages/49cc81/#activerecord-%E6%A8%A1%E5%BC%8F

**Comment by aboutZZ** [comment]
既然换ORM了，而且还是一个革命性的ORM, 思维方式是否应该变一变呢

**Comment by 1741432465** [comment]
嗯嗯抱歉，这么提issue有点不礼貌了，小白单纯好奇提个问，没有让大佬契合个人需求的意思，群里大佬已经解释过了，感谢
