### ISSUE TITLE
UUID to varchar conversion problem

### ISSUE THREAD

**Issue by a8t3r** [babyfish-ct/jimmer#566]
Model primary key defined as `UUID`:
```kotlin
@Entity
interface UserAttribute {

    @Id
    val id: UUID
...
}
```
But database type is `varchar(36)`.
I defined property based scalar provider and select queries work as expected, but update queries became broken because `SqlBuilder.variable(Object value)` use only `typeScalarProviderCache` and ignores `propScalarProviderCache`. `Column(sqlType="???")` also doesn't work.

![Screenshot from 2024-05-14 16-34-00](https://github.com/babyfish-ct/jimmer/assets/2035647/48d2caeb-d72c-497c-b3b7-7ffe4761faaf)

I don't want provide type scalar for entire client, because there exist different models with valid db mapping.
I would like solution based on column annotation:
```kotlin
    @Id
    @Column(sqlType = java.sql.Types.VARCHAR)
    val id: UUID
```

**Comment by babyfish-ct** [comment]
Now, scalar provider is the only one choice.

The `sqlType` of @Column is very youg feature which is only used by in-list predicate optimization for H2 and PG. it is not common&old features for everything thing include scalar provider gussing.

Next, the `@Column.sqlTypes` can become bigger so that it can be used by more other features. But now, the most important job is save command reactor, pelease wait

**Comment by babyfish-ct** [comment]
Try `0.8.132`

**Comment by a8t3r** [comment]
@babyfish-ct Doesn't work.
Your [patch](https://github.com/babyfish-ct/jimmer/commit/885e68096e66070fef8f4e25c515b28913f01c20#diff-850e7fadd6c50de16adbce4b2115e9e58855c67c289d5565f157dd91b3bfd340) applies on properties, not types.

**Comment by babyfish-ct** [comment]
Of course, it can only be guessed for the metadata of property which tells the UUID is binary of text.

**Comment by babyfish-ct** [comment]
Please specify the `@Column.sqlType` explicitly, No metadata, no guessing.

**Comment by a8t3r** [comment]
![Screenshot from 2024-05-20 10-20-23](https://github.com/babyfish-ct/jimmer/assets/2035647/46341b27-af7e-43a1-bc95-06292249d32e)
This is my execution stack. When rendering variables, it looks up the scalar provider by type:
```kotlin
ScalarProvider<Object, Object> scalarProvider =
            ctx.getSqlClient().getScalarProvider((Class<Object>) value.getClass());
```

**Comment by a8t3r** [comment]
I write [simple test](https://github.com/babyfish-ct/jimmer/compare/main...a8t3r:jimmer-copy:uuid_conversion_test) to reproduce the issue

**Comment by babyfish-ct** [comment]
Currently, Jimmer is undergoing a major refactor, so the problem that can be solved by one statement code will be delayed.
