### ISSUE TITLE
如何能在拦截器DraftInterceptor获取到当前操作的表对象的表信息？

### ISSUE THREAD

**Issue by qinkangdeid** [babyfish-ct/jimmer#567]
## 版本

jimmer：0.8.131

## 问题描述

我写了一个 公共字段的填充拦截器 ，填充逻辑有一些策略，我想在填充拦截器里打印点 debug日志，能够打印 表名  表字段 表字段值之类的信息，查看draft没有查看到有表信息相关的

请问 我能通过什么途径获取到当前操作表的表信息？

![43d13dc8f1b9f6ecd51cc6bb685b5087](https://github.com/babyfish-ct/jimmer/assets/17582522/0d63424c-54ef-480b-810a-103909426019)

**Comment by babyfish-ct** [comment]
1. 首先，或取sqlClient，这一步小心spring循环引用的问题

2. `ImmutableType.of(Book::class)`可以获得类型，可以遍历属性。和Java反射类似，事实上这就是ORM的反射

3. `ImmutableType.getTableName`取表名，`ImmutableProp.getStorage`取列或中间表。所需MetadataStrategy参数，1中得到的sqlClient可以提供
