### ISSUE TITLE
DTO equals() does not properly compare arrays

### ISSUE THREAD

**Issue by runningjustin** [babyfish-ct/jimmer#568]
I have a property defined in my Entity like this:

`@Column(sqlElementType = "text") override val countryCode: Array<String>`

This is brought in to the DTO with `#allScalars`

The generated equals() function compares arrays by address, not by contents, which is causing comparisons to fail:

```kotlin
    public override fun equals(o: Any?): Boolean {
        ...
        countryCode == _other.countryCode &&
        ...
    }
``` 

I believe the right way to compare would be:
```kotlin
    public override fun equals(o: Any?): Boolean {
        ...
        countryCode.contentEquals(_other.countryCode) &&
        ...
    }
```

**Comment by babyfish-ct** [comment]
Try `0.8.132`
