### ISSUE TITLE
能不能加入跨服务实体抓取数据？

### ISSUE THREAD

**Issue by 1013785085** [babyfish-ct/jimmer#57]
比如，A实体在S1服务中，B实体在S2服务中，我在A服务中定义B类型属性时告诉它是远程数据对象，在抓取B数据时候就访问约定的远程访问接口

**Comment by babyfish-ct** [comment]
早已实现，请参考例子`example/java/jimmer-cloud`或`example/kt/jimmer-cloud-kt`

**Comment by 1013785085** [comment]
![image](https://user-images.githubusercontent.com/15832933/233110802-2cf16b10-dc17-4ec6-b7e9-e651e348942a.png)
远程实体是不是不支持字段查询和修改？

**Comment by babyfish-ct** [comment]
是的，没法支持

**Comment by 1013785085** [comment]
从感觉上好像可以将上面的SQL解析成2个SQL：本地 select store_id from book where id = 1，远程 update book_store set name = "test" where id in (1);  这样拆解有问题吗？

**Comment by babyfish-ct** [comment]
论述这种极简的特殊案例没价值。来看普适的案例。

- 为什么不支持远程修改？
   
   无论是update语句还是save指令，都可能一条指令导致多个服务数据被改，尤其是save-command。这就是分布式一致性了。在乎一致性吗？如果在乎一致，同步还是异步？如果异步，是本地表重试MQ，还是Rocket MQ事务队列。如果同步，用什么分布式事务方案呢？不同服务之间的一致性，不同的公司有不同的选择，难以统一。
   
   即使就这种极端简单的情况，即一条命令只改一个服务的数据，实现了以也没价值，因为这个简单的功能不可能是业务的全部，只可能是业务的一部分，照样会陷入分布式一致性问题。只不过从“一条命令修改多个服务的数据”变成“多条命令修改多个服务的数据”，本质还是一个业务要改多个服务的数据。
   
   相反，每个服务自己提供修改API，各自隐藏数据操作细节，是几乎所有分布式一致性的实施基础。
 
 - 为什么不支持跨服务join？
 
    例如`from a inner join b .... inner join c whera a.region = b.region and b.value between c.min and c.max`. 
    
    其中a. b, c隶属于不同的服务。实际情况可能是这样的，a, b, c join起来并用sql条件后数据量很小，但割裂开，单独限定a, b或c，数据量是海量的，谁执行谁死机。
    
    这就是为什么跨服务join是微服务的头号难题，比分布式一致性还绝望，需要用很多复杂的技巧来规避。
    
 - 总结
 
   微服务是一个复杂的而庞大的技术话题，只有夸服务提取数据是可以通过轻量封装简化的，其他的，是整个行业的难题。企图通过远程关联的简单抽象企图让微服务架构的复杂性消失，变得和单体应用开发一样简单，就是做梦。
