### ISSUE TITLE
DraftInterceptor not being called on update

### ISSUE THREAD

**Issue by runningjustin** [babyfish-ct/jimmer#570]
I've got a draft interceptor patterned after the one in the docs to update the updatedAt timestamp. Calls to createUpdate(...).execute() don't seem to be hitting the interceptor's beforeSave(). The interceptor is initialized, which is confirmed by seeing that it gets invoked on save().

Let me know if you need more info.

**Comment by babyfish-ct** [comment]
Yes, `createUpdate` is used to execute fast batch updating without draft interceptor.

Eg: update x set y = y + 1; Only execute it in fastest way, no interceptor, no optimistic lock
