### ISSUE TITLE
java: 来自批注处理程序 'org.babyfish.jimmer.apt.JimmerProcessor' 的受支持 source 版本 'RELEASE_8' 低于 -source '21'

### ISSUE THREAD

**Issue by lhl-github** [babyfish-ct/jimmer#572]
java: 来自批注处理程序 'org.babyfish.jimmer.apt.JimmerProcessor' 的受支持 source 版本 'RELEASE_8' 低于 -source '21'

请问什么时间 支持高版本的jdk

**Comment by babyfish-ct** [comment]
未实验升级这里是否会对Java8有影响

**Comment by babyfish-ct** [comment]
我们的大环境，你懂的，“管你怎么折腾，我永远Java8”。

有空的话，可以帮我做个实验, 写一个最简单的apt, apt本身按java8编译，但这里SOURCE接受21，看APT本身认不认。再用一个Java8使用apt，看认不认。

**Comment by babyfish-ct** [comment]
This will be handle in future, not now
