### ISSUE TITLE
[bug] 升级kotlin与ksp2.0.0之后实体使用default注解编译报错，切换回1.9.23之后正常。

### ISSUE THREAD

**Issue by langbiantianya** [babyfish-ct/jimmer#577]
![8ede4cde313d8b5962362daaabbe523e](https://github.com/babyfish-ct/jimmer/assets/56261889/bd5d05d6-ffd2-4f59-90d9-744637b3fbcb)

**Comment by babyfish-ct** [comment]
Try `0.8.133`
