### ISSUE TITLE
Nullability on logical deletion

### ISSUE THREAD

**Issue by a8t3r** [babyfish-ct/jimmer#589]
I add logical deletion for [example test](https://github.com/babyfish-ct/jimmer/compare/main...a8t3r:jimmer-copy:nullability-on-logical-deletion?expand=1):
```kotlin 
@Entity
interface Course {
    @LogicalDeleted("true")
    val deleted: Boolean
}

@Entity
interface LearningLink {
    @ManyToOne
    @OnDissociate(DissociateAction.DELETE)
    val course: Course
}
```
Test fails on `AbstractDataLoader:167`:
```
org.babyfish.jimmer.sql.runtime.ExecutionException: Cannot apply filter "ExportedCacheableFilter{filters=[org.babyfish.jimmer.sql.filter.impl.LogicalDeletedFilterProvider$DefaultFilter@178f268a]}" 
for "org.babyfish.jimmer.sql.kt.model.link.LearningLink.course" because that property is not nullable
```
I'm guessing that the sub-entity should be deleted while the root entity is being deleted, so the link cannot exist without a course, so nullability is not required.

**Comment by babyfish-ct** [comment]
Of course, No problem.

Even if the foreign key in data base is non-null, but the associated object still may be hidden by filter, so filtered associated object must be nullable.

**Comment by a8t3r** [comment]
What do you think of this patch?:
```kotlin
AbstractDataLoader:167
< if (prop.isReference(TargetLevel.ENTITY) && !prop.isNullable()) {
> if (prop.isReference(TargetLevel.ENTITY) && !prop.isNullable() && prop.isInputNotNull()) {
```
`inputNotNull` describes exactly the case you cited.

**Comment by babyfish-ct** [comment]
No, input not-null means validation of writing, like non-null constraint of foreign key. 

For reading, it still may be nullable.

**Comment by babyfish-ct** [comment]
What is filter? To hide data.

There is non-null reference, but it is invisible, so I can still see nothing.
