### ISSUE TITLE
[fr] Support strong consistency while using a cache with some kind of locks

### ISSUE THREAD

**Issue by belovaf** [babyfish-ct/jimmer#599]
Currently jimmer supports only eventual consistency.
As an example implementation we can look at hibernate [CacheConcurrencyStrategy](https://github.com/hibernate/hibernate-orm/blob/main/hibernate-core/src/main/java/org/hibernate/annotations/CacheConcurrencyStrategy.java).
`READ_WRITE` variant provides some information about implementation details.

**Comment by babyfish-ct** [comment]
Try `0.8.147`
