### ISSUE TITLE
[BUG] Associating Formula Properties with List<String> in the DTO language express an unexpected result

### ISSUE THREAD

**Issue by WackyGem** [babyfish-ct/jimmer#601]
问题描述:
1. 在Book实体中添加计算属性authorFullNames，返回结果类型是** `List<String>` **
2. 在Book.dto 中创建一个FullNameView，关联该计算属性authorFullNames，执行ksp
3. 生成FullNameView中的authorFullNames属性类型是**` List<List<String>>`** 不符合预期

复现步骤：

- 参考例子工程代码：https://github.com/WackyGem/jimmer-examples/commit/2893dc0a8cbc329e3e9d1a276dacbc4e5586fdbb#
- 在Book实体中添加计算属性authorFullNames

https://github.com/WackyGem/jimmer-examples/blob/2893dc0a8cbc329e3e9d1a276dacbc4e5586fdbb/kotlin/jimmer-sql-kt/model/src/main/kotlin/org/babyfish/jimmer/sql/example/kt/model/Book.kt#L48-L50

- 在Book.dto中创建一个FullNameView

https://github.com/WackyGem/jimmer-examples/blob/2893dc0a8cbc329e3e9d1a276dacbc4e5586fdbb/kotlin/jimmer-sql-kt/service/src/main/dto/Book.dto#L67-L70

- 生成的DTO如下

![image](https://github.com/user-attachments/assets/e419002a-f425-4c90-a58e-3026f11d72f2)

**Comment by babyfish-ct** [comment]
Try `0.8.147`
