### ISSUE TITLE
[fr] Support to-one associations update without neither id or key

### ISSUE THREAD

**Issue by belovaf** [babyfish-ct/jimmer#605]
For example if `Car` has `engine_id` foreign key to `Engine` it should be possible to save a following DTO:
```
Car {
  id
  engine {
    // many properties, but no id
  }
}
```

**Comment by babyfish-ct** [comment]
Save command is being refactored now

**Comment by babyfish-ct** [comment]
Please pull the branch `save-command-rafactor` and use `AssociatedSaveMode.VIOLENTLY_REPLACE`
