### ISSUE TITLE
当生成策略为USER时，必须指定另外一个属性"生成器" 给用户一个可读性更好的异常

### ISSUE THREAD

**Issue by VonSkiXD** [babyfish-ct/jimmer#61]
![4d35b8892b328a6485c4e31498f9aff](https://user-images.githubusercontent.com/49237774/233570982-7af4ee1c-7be9-4946-8249-950188d6f23e.png)
![03b4ac6f3d632efc418e05f1bf2d58a](https://user-images.githubusercontent.com/49237774/233571054-a4edd6c1-d3a0-4609-8631-a22d9338705b.png)

**Comment by babyfish-ct** [comment]
Try 0.7.45
