### ISSUE TITLE
openapi.yml  报501

### ISSUE THREAD

**Issue by lhl-github** [babyfish-ct/jimmer#610]
Resolved [java.lang.ClassCastException: class org.babyfish.jimmer.client.runtime.impl.TypeVariableImpl cannot be cast to class org.babyfish.jimmer.client.runtime.SimpleType (org.babyfish.jimmer.client.runtime.impl.TypeVariableImpl and org.babyfish.jimmer.client.runtime.SimpleType are in unnamed module of loader 'app')]
2024-07-26 15:13:14.120 DEBUG 136496 --- [nio-9987-exec-9] o.s.web.servlet.DispatcherServlet        : Completed 501 NOT_IMPLEMENTED

请求 http://127.0.0.1:9987/openapi.html
                   http://127.0.0.1:9987/openapi.yml    501 Not Implemented

![image](https://github.com/user-attachments/assets/b935d195-d1e3-4eda-8ec4-191019a44638)

![image](https://github.com/user-attachments/assets/6a9a601d-c1b8-48eb-9585-5a616c0fab15)

**Comment by Enaium** [comment]
看你哪个接口是不是写的有问题，排除一下是哪个

**Comment by lhl-github** [comment]
总共三个 Controller  都使用ApiIngore 修饰了 也不行
[demo2_.zip](https://github.com/user-attachments/files/16397937/demo2_.zip)
源码这样的 maven的

**Comment by lhl-github** [comment]
![image](https://github.com/user-attachments/assets/090b638f-1839-4eb3-9509-03ca2aaabda1)
我发现是这个泛型如果写成模糊的  就不行了  改成明确的泛型类型就可以了

**Comment by babyfish-ct** [comment]
OK, 有线索了

**Comment by babyfish-ct** [comment]
既然你的工作不受影响了，我这边还有优先级更高一堆事，优先级先放放

**Comment by lhl-github** [comment]
![image](https://github.com/user-attachments/assets/80afa657-9774-4bcc-ad18-256677a9057b)
![image](https://github.com/user-attachments/assets/09c79bfb-39aa-45b1-ba66-f0d5c9a03e20)
三个类只扫描到两个  这是为什么    感谢大佬指点

**Comment by lhl-github** [comment]
![image](https://github.com/user-attachments/assets/def8e6d3-7a16-4059-81b5-9af7daac3f64)
似乎是不支持静态内部类 当我删除 入参的时候就能扫描到了  ,   大佬什么时候能支持下静态内部类入参  这个比较 常用,  wps的sdk好多都是静态内部类入参 出参     不可避免的会使用静态内部类来传参

**Comment by Enaium** [comment]
> ![image](https://private-user-images.githubusercontent.com/46683017/352706165-def8e6d3-7a16-4059-81b5-9af7daac3f64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNzMxMTgsIm5iZiI6MTcyMjA3MjgxOCwicGF0aCI6Ii80NjY4MzAxNy8zNTI3MDYxNjUtZGVmOGU2ZDMtN2ExNi00MDU5LTgxYjUtOWFmN2RhYWMzZjY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDA5MzMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YWFiMzQyMWFiM2YwNDIwODM0NDY4YjkxNWIzN2VmMGNjNDFlYzc1YjRkZjg4MzdlMjQ3N2M4MTNmZWY1NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.de9ce-KR8lnd3f1cPbJJcUFJgRTUAdax_v4-6i4ie_c) 似乎是不支持静态内部类 当我删除 入参的时候就能扫描到了 , 大佬什么时候能支持下静态内部类入参 这个比较 常用, wps的sdk好多都是静态内部类入参 出参 不可避免的会使用静态内部类来传参

我试了一下这么写没问题

**Comment by lhl-github** [comment]
大佬 你的图看不到     我用静态内部类时  哪个接口就不在文档中了

**Comment by lhl-github** [comment]
![image](https://github.com/user-attachments/assets/9a05545b-8b2d-4c2a-8165-ad44f7d455ba)

![image](https://github.com/user-attachments/assets/c7c95ed4-bf97-4c8b-b28b-2fd82b49ed4f)
这个对比就明显了

**Comment by Enaium** [comment]
![](https://github.com/user-attachments/assets/a95d3ba0-88f2-4524-8408-e6cfa27ae85b)
![](https://github.com/user-attachments/assets/d47aaee3-a155-449d-9427-e30180094d84)

这边没问题

**Comment by babyfish-ct** [comment]
Try `0.8.150`

**Comment by lhl-github** [comment]
换到 0.8.150正常了  感谢
