### ISSUE TITLE
[BUG] 集合 IdView 经 dto 生成的类型错误

### ISSUE THREAD

**Issue by pot-mot** [babyfish-ct/jimmer#614]
当我从 0.8.140 升级至 0.8.149 时，直接使用集合`IdView`转换的类型从`List<Int>`变成了`Int`。

属性如下，`ManyToOne`和`IdView`：
![image](https://github.com/user-attachments/assets/ef9304c8-43ef-4d99-afc7-2d2e80d889f7)
在 dto 中使用该`IdView`：
![image](https://github.com/user-attachments/assets/ae83ac4f-3883-4ba0-9a02-a14a78de1d4e)
此时生成的 dto 中该 IdView 类型为`Int`，实际需要为`List<Int>`：
![image](https://github.com/user-attachments/assets/fead620c-6cf0-4a24-a7e3-c89bbfd70b97)

**Comment by babyfish-ct** [comment]
This issue has been fixed by PR #612
