### ISSUE TITLE
[fr] Support to-many associations replace without neither id or key

### ISSUE THREAD

**Issue by belovaf** [babyfish-ct/jimmer#616]
For example if `Root` has many `Items` it should be possible to save a following DTO (all items should be replaced).
I think it is a good idea to introduce new association mode for such behaviour.

```
Root {
  id
  items {
    // simple properties, but no id, no key
  }
}
```

**Comment by babyfish-ct** [comment]
Please pull the branch `save-command-rafactor` and use `AssociatedSaveMode.VIOLENTLY_REPLACE`
