### ISSUE TITLE
一些小体验问题

### ISSUE THREAD

**Issue by Atomzzm** [babyfish-ct/jimmer#628]
<img width="643" alt="6a8fc5409c02130730a0985d3c83d8c7" src="https://github.com/user-attachments/assets/a7a40938-6c0e-4d8d-bf09-4800695ef3eb">

<img width="323" alt="24821546fcfe5643cb697041d664b066" src="https://github.com/user-attachments/assets/bd73383c-8e68-49f3-b74a-8d097b19e8c8">

- 指定ID非空了，但生成类里还是可为空的。
- updateById和deleteById的重载返回bool。不知道是否会更好用一些
-  Repository要是能增加个updateEntitys的批量更新就更好了
-  分页的起始页是从0开始的，能否从1开始。或者提供个配置项。目前使用的element-plus vue写死从1开始了
-  查询sql日志打印行数

**Comment by babyfish-ct** [comment]
指定ID非空了，但生成类里还是可为空的。
> 版本过低
updateById和deleteById的重载返回bool。不知道是否会更好用一些
> 高版本返回int
Repository要是能增加个updateEntitys的批量更新就更好了
> 支持saveEntitiesCommand可以配置参数，为防止API过分爆炸，批量特例操作
分页的起始页是从0开始的，能否从1开始。或者提供个配置项。目前使用的element-plus vue写死从1开始了
> 配置会导致代码有歧义难以阅读，后续非spring data repository提供无歧义API
查询sql日志打印行数
> spring配置开启`jimmer.pretty-sql=true`即可打印影响行数
