### ISSUE TITLE
[Feature Request] Map json column type

### ISSUE THREAD

**Issue by aboutZZ** [babyfish-ct/jimmer#63]
希望可以简化数据库 json 列的映射。
目前来说，将数据库表中 json 列映射至 entity，需要自定义 `ScalarProvider` 来进行列的序列化反序列化，但是每有一个这种列，都要定义一个`ScalarProvider`。希望可以有一个 Json 相关通用的处理。例如 （参考 [hypersistence-utils](https://github.com/vladmihalcea/hypersistence-utils)）：
```java
// 加入 @Type注解，指定该列为 JsonType，即可自动(反)序列化，无需定义 ScalarProvider
@Column(columnDefinition = "jsonb")
@Type(JsonType.class)
private ApiAccessRequestParam requestParams
```

**Comment by babyfish-ct** [comment]
Try 0.7.45

`@Serialized` can be used to decorate both class *(Repleace global scalar provider)* and property *(Replace property level scalar provider)*, now developers need not implement scalarprovider.

When `@Serialized` is used with `PostgresDialect`, `PGobject` will be used to handle jsonb column of posgresql.
