### ISSUE TITLE
redis集成序列化问题

### ISSUE THREAD

**Issue by Atomzzm** [babyfish-ct/jimmer#630]
[序列化问题.zip](https://github.com/user-attachments/files/16668070/default.zip)
测试工程包 只需看下redissonClinet是哪的兼容问题导致的失败。 redisTemplate和saToken应该是配置问题...但我也没找到哪个配置问题... 用注入的objectMapper就可以。用自己new ObjectMapper 注册ImmutableModule就不行...
<img width="829" alt="e16671f45b279849b361a6f7cdba2bcd" src="https://github.com/user-attachments/assets/4c687261-118b-4946-88c1-26afa3c37a8f">

**Comment by babyfish-ct** [comment]
jimmer和Sa-Token配合的确有问题，但犯错方是sa-token，原因如下

1. sa-token没意识到jackson的强大，内部固化object mapper
2. redissio codec为了屏蔽干扰，copy了object mapper(reddison的做法没错，但是导致你例子中tricky努力无效）

方案：
1. 折腾方案（不推荐）：实现sa-token dao，想办法替换SaTokenDaoRedissonJackson
2. 不知疼方案（推荐）：使用DTO语言查询身份相关的信息，和sa-token交互DTO而非entity
