### ISSUE TITLE
1对1的多态映射

### ISSUE THREAD

**Issue by Atomzzm** [babyfish-ct/jimmer#633]
假如有价格、商品（@MappedSuperclass）西瓜、葡萄 三个实体。价格跟商品关系为1对1。在价格实体里怎么设置跟西瓜、葡萄实体的关系呢？我看了中间表过滤器 是不是只适用于多对一，多对多

**Comment by babyfish-ct** [comment]
中间表有类别鉴别字段功能，此功能较新，忘了上文档
