### ISSUE TITLE
input自定义字段List<Long>编译报错

### ISSUE THREAD

**Issue by Atomzzm** [babyfish-ct/jimmer#634]
<img width="1088" alt="d38d1b70104bb1d510aa9d9b8b5e6a04" src="https://github.com/user-attachments/assets/7bc4de68-a9a7-4bb7-a869-aa2859538b4a">

**Comment by babyfish-ct** [comment]
请使用`List<Int?>`，报错信息需要改进

**Comment by babyfish-ct** [comment]
Try `0.8.1.60` to get readable & helpful error message

**Comment by babyfish-ct** [comment]
Previous fixing affected kotlin. rollbacked.

New fixed dose not change DTO language, you can still use `List<Long>`, not `List<Long?>`, it only changes Java DTO Generator
