### ISSUE TITLE
jimmer不能关闭某个Repository的sql日志吗

### ISSUE THREAD

**Issue by Atomzzm** [babyfish-ct/jimmer#635]

**Comment by TokgoRonin** [comment]
**Two possible solutions:**

1. **Within each method:** Use `sql().executor(DefaultExecutor.INSTANCE)`
2. **In the repository interface:** Create a global `SqlClient` instance:
   ```java
   JSqlClient sqlClient = JSqlClient.newBuilder().setExecutor(DefaultExecutor.INSTANCE).build();
   ```
   This approach requires you to manually inject any necessary interceptors or other components into your project (if applicable).
