### ISSUE TITLE
当字段出现is_xxx会有bug

### ISSUE THREAD

**Issue by yejunyu** [babyfish-ct/jimmer#636]
### 属性截图
<img width="294" alt="image" src="https://github.com/user-attachments/assets/342a629a-d78c-45aa-87bf-53f0c679ac9f">

### 查询代码
<img width="498" alt="image" src="https://github.com/user-attachments/assets/b086c749-2043-46f6-a04c-46328f6b3e9e">

### 报错
![122b23b8dda548a2e28066e851542405](https://github.com/user-attachments/assets/404b1e24-78ab-4106-90b7-c2775f9a2455)

**Comment by babyfish-ct** [comment]
Try `0.8.161`
