### ISSUE TITLE
有关于 DTO specification 的一些疑问

### ISSUE THREAD

**Issue by zhengchalei** [babyfish-ct/jimmer#643]
```
BookView {
    id(authors) as authorIds   // List<Long> authorIds
}

input BookInput {
    id(authors) as authorIds   // List<Long> authorIds
}

specification BookSpecification {
    id(authors) as authorIds   // Long authorIds
}
```

从前两个 View 和 Input 来看, 都是符合直觉的,
specification 来说, 有点突然, 这里应该也是和 View / Input 一样返回List<Long> 
这里单独使用一个关键字, 来区分 Long /  List<long> 是不是更合适

**Comment by babyfish-ct** [comment]
Try `0.8.161`

`id` is forbidden in specification, `associatedIdEq` must be used.
