### ISSUE TITLE
[Feature Request] Add Upsert Support for Entities with Only ID and No Key Definitions

### ISSUE THREAD

**Issue by ArgonarioD** [babyfish-ct/jimmer#652]
In some scenarios, developers need to design entity models with no keys that have actual business meaning. In such cases, when executing the save command, if the id of this type of entity aggregate root object is unloaded, it should behave as an insert; if it is loaded, it should behave as an update.

Since version 0.8.160, Jimmer no longer supports the upsert function for such entity models. This issue **DOES NOT** aim to disrupt the behavior consistency between the aggregate root object and the associated objects during save. Instead, it seeks to restore this feature in some other form.

It would be cool if Jimmer could cover more reasonable scenarios.

**Comment by babyfish-ct** [comment]
Try `0.8.166`, SaveMode.NON_IDEMPOTENT_UPSERT
