### ISSUE TITLE
[BUG] Not possible to set the key field for the entity via the interceptor

### ISSUE THREAD

**Issue by ClearPlume** [babyfish-ct/jimmer#653]
In the current version 0.8.167, it is not possible to set the key field for the entity using an interceptor. The initial diagnosis suggests that an exception being thrown in this loop is the likely cause.

![$ASKSR6AC`715@L8G$X$JR7](https://github.com/user-attachments/assets/3d1a7dc2-3460-433c-9c04-11287b159284)

**Comment by babyfish-ct** [comment]
Try `0.8.168`

**Comment by ClearPlume** [comment]
The problem still persists. I have attached a minimal reproducible example for review.

[partial-key-mre.zip](https://github.com/user-attachments/files/16884156/partial-key-mre.zip)

**Comment by lyingd** [comment]
0.9.48版本好像也存在此问题，saveInputs时，若元素缺失key字段（如租户id），预期在DraftInterceptor中补全，但在进入DraftInterceptor前，已经抛出异常
