### ISSUE TITLE
[bug] SaveException.NotUnique not working with postgres

### ISSUE THREAD

**Issue by belovaf** [babyfish-ct/jimmer#654]
Postgres does't support an execution of any query in the current transaction after any SqlException.
Jimmer tries to investigate a unique constraint problem with an additional query in the same transaction.
This works for other databases (h2, oracle), but doesn't work for postgres and leads to another exception:
`org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block`

Possible solutions:
1) Support postgresql savepoints and create a new savepoint before any insert (not the best option in my opinion)
2) Use `insert on conflict do nothing` and do additional query in case of no rows was updated.

**Comment by babyfish-ct** [comment]
Try `0.8.168`
