### ISSUE TITLE
[Feature Request] Option to Enable/Disable Identification of Error Points Using SavePoint Mechanism for SQL Updates in PostgreSQL

### ISSUE THREAD

**Issue by ClearPlume** [babyfish-ct/jimmer#656]
The SavePoint mechanism in PostgreSQL provides the capability to roll back to a stable state for error analysis when an SQL update fails. However, it requires that a transaction be present in the current context, which is not feasible in some projects.

**Comment by babyfish-ct** [comment]
Try `0.8.170`
