### ISSUE TITLE
PostgreSQL 方言SQL语句显式指定其类型

### ISSUE THREAD

**Issue by aboutZZ** [babyfish-ct/jimmer#66]
## 问题描述
对于 PG 数据库 json 列，我定义了一个 ScalarProvider，toSql 方法中将对象转为 json，插入数据库时报错：
`column "params" is of type jsonb but expression is of type character varying `
## 原因
PG 数据库在插入 `json` 列时，需要将字符串显式转为 `json` / `jsonb` 类型

插入语句：`insert into ... values ( '[1,2,3]')`
期望插入语句：`insert into ... values ( '[1,2,3]'::jsonb)`
## 问题
toSql 方法中怎样显式指定其为 jsonb 类型呢?
相关的issuee： #63

## 可能的解决方案
See https://stackoverflow.com/a/35845278/5357696

`preparedStatement`中设置使用`PGObject`包裹：`preparedStatement.setObject (index, PGobject)`

**Comment by aboutZZ** [comment]
For those who want to mapping jsonb column, see [my code snippet](https://gist.github.com/aboutZZ/c0d6963c0fe3ae48e82b2fb631558e69)

**Comment by babyfish-ct** [comment]
ScalarProvider的SqlType指定为PGobject即可，例如

```
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import org.babyfish.jimmer.sql.runtime.ScalarProvider
import org.postgresql.util.PGobject

class PointProvider : ScalarProvider<Point, PGobject>() {

    override fun toScalar(sqlValue: PGobject): Point =
        MAPPER.readValue(sqlValue.value, Point::class.java)

    override fun toSql(scalarValue: Point): PGobject =
        PGobject().apply {
            type = "jsonb"
            value = MAPPER.writeValueAsString(scalarValue)
        }

    companion object {

        @JvmStatic
        private val MAPPER = jacksonObjectMapper()
    }
}
```
