### ISSUE TITLE
[Bug]多数据源本地事务模式，指明TransactionManager后依然报错

### ISSUE THREAD

**Issue by yangpanda** [babyfish-ct/jimmer#662]
![02f86a9fdcbfa2808ec8446b761221e3](https://github.com/user-attachments/assets/f0bb4deb-c9de-4c4c-8f08-07b34bc1080e)
![4f90134b3c9692b33df749b1f4366ddf](https://github.com/user-attachments/assets/c556f677-8461-45ae-92e7-1efbf4a8be4f)

**Comment by babyfish-ct** [comment]
Try `0.8.172`
