### ISSUE TITLE
`ScalarProvider` should not annotated as `NotNull`

### ISSUE THREAD

**Issue by aboutZZ** [babyfish-ct/jimmer#67]
https://github.com/babyfish-ct/jimmer/blob/cd61baa0b6e439a73e0211157876e1b56ffaff74/project/jimmer-sql/src/main/java/org/babyfish/jimmer/sql/runtime/ScalarProvider.java#L59-L64

`ScalarProvider` 类中，`toScalar` 及 `toSql` 方法中参数及返回值不应当注解为`NotNull`。因为数据库中的值、用户传入参数的确可能为`null`
此问题主要是略微影响了 `kotlin` 代码的编写，`toScalar / toSql` 方法参数及返回值必须为 `T` 不能是 `T?`，否则编译器会报错，不能 override 父类方法

**Comment by babyfish-ct** [comment]
没有问题，就是为了改善kt开发体验而加。

对于null，Jimmer不会走ScalarProvider，一旦走了ScalarProvider，就一定非null
