### ISSUE TITLE
[Feature Request] 当mysql表名命中的数据库关键字时(例如group表名)，生成的sql执行报错

### ISSUE THREAD

**Issue by xiaoquanidea** [babyfish-ct/jimmer#670]
我在mysql数据库中有一张表叫group，在另外一个entity中引用了Group实体
<img width="1425" alt="image" src="https://github.com/user-attachments/assets/1fab3d63-c1e4-489d-9be9-26bfa1bd0984">
，生成的sql触发了mysql的关键字group，查询报错：
![cd8977b997349206b7c98e092dcd799b](https://github.com/user-attachments/assets/cfc24e55-d72c-47ce-84a0-12db65efc325)
，我修改了Group表上的注解@Table("`group`")，也启动报错，因为我开启了数据库约束校验，关闭校验之后查询正常。

大佬给出的建议：
<img width="633" alt="image" src="https://github.com/user-attachments/assets/b2806a3c-61cf-4b53-becd-0258ca5f33b0">

**Comment by babyfish-ct** [comment]
Try `0.8.177`

**Comment by xiaoquanidea** [comment]
> Try `0.8.177`

非常感谢大佬
