### ISSUE TITLE
[Feature Request]当前dto语言是否支持字段复合ID平铺？

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#671]
![image](https://github.com/user-attachments/assets/29a6d573-4839-4290-80e4-fb2dfd8b3ef7)
![image](https://github.com/user-attachments/assets/56c7311c-2c6f-4e35-aecb-2c085e001ecd)

**Comment by babyfish-ct** [comment]
Try `0.8.177`
