### ISSUE TITLE
[Bug] Deserialisation error using FetcherCompiler

### ISSUE THREAD

**Issue by Madeoke** [babyfish-ct/jimmer#672]
Easy Way To Reproduce using jimmer-sql-kt

1. Add Custom Dto to Book.dto `ImplicitSerialisationBugBook {
    storeId
    authors {
        #allScalars(this) // or #allScalars(Author)
        -id // Remove id
    }
}`

2. Add CommandLineRunner to App.kt and implement run method with `	override fun run(vararg args: String?) {
		val fetcher = DtoMetadata.of(ImplicitSerialisationBugBook::class.java).fetcher.toString()
		val fetcherFromStr = FetcherCompiler.compile(fetcher)
}`

Expected: FetcherCompiler deserialized fetcherString successfully 

Actual: Got exception on run Caused by: org.babyfish.jimmer.sql.fetcher.compiler.FetcherCompileException: Cannot compile fetcher(line: 1, position: 106): token recognition error at: '@'

**Comment by babyfish-ct** [comment]
Try `0.8.178`
