### ISSUE TITLE
[BUG]逻辑删除默认情况下中间表的数据被删除了

### ISSUE THREAD

**Issue by LanXa7** [babyfish-ct/jimmer#673]
![c3b6f1b7cb0c31094da7b99f0f9058b1](https://github.com/user-attachments/assets/34acae1e-3067-4002-a9e3-a54d2d42ed75)
![50b8c2663c70ca15d930efff741e935b](https://github.com/user-attachments/assets/9725b34d-8474-432e-a981-22c522e1d76d)
![fba21ae463ffb4fc7657209427e8824e](https://github.com/user-attachments/assets/33fc5bf0-a94b-49f8-b519-19eb77e2dc87)
![b6623a7158442873d666961ae57ecb4d](https://github.com/user-attachments/assets/47a707e0-8048-4986-9d16-404eb0e05cb5)
![b11de33700cb0fa38c32e33d60a16f0a](https://github.com/user-attachments/assets/f08af983-3275-4b83-856b-1588dd41cb70)

2024-09-19T21:00:05.786+08:00  INFO 16568 --- [nio-8100-exec-4] o.b.jimmer.sql.runtime.ExecutorForLog    : Execute SQL===>
Purpose: MUTATE
SQL: delete from user_role_mapping
where
    role_id = ? /* 6 */
Affected row count: 1
JDBC response status: success
Time cost: 78ms
<===Execute SQL
2024-09-19T21:00:05.849+08:00  INFO 16568 --- [nio-8100-exec-4] o.b.jimmer.sql.runtime.ExecutorForLog    : Execute SQL===>
Purpose: MUTATE
SQL: delete from role_permission_mapping
where
    role_id = ? /* 6 */
Affected row count: 0
JDBC response status: success
Time cost: 63ms
<===Execute SQL
2024-09-19T21:00:05.913+08:00  INFO 16568 --- [nio-8100-exec-4] o.b.jimmer.sql.runtime.ExecutorForLog    : Execute SQL===>
Purpose: COMMAND
SQL: update sys_role set DELETED = ? /* 1 */ where ID = ? /* 6 */
Affected row count: 1
JDBC response status: success
Time cost: 63ms
<===Execute SQL

实现逻辑删除了 但是中间表的数据被删除了 按照这里的说法如果不配置的话默认应该是不会被处理的

**Comment by babyfish-ct** [comment]
Try `0.8,179`
