### ISSUE TITLE
拦截器 IdView点不出来

### ISSUE THREAD

**Issue by 36k** [babyfish-ct/jimmer#676]
jimmer :0.8.176  kotlin环境下
**MappedSuperclass超类型**
<img width="185" alt="a1b7687ba260121e2558bdaca4c2ceff" src="https://github.com/user-attachments/assets/dd058052-d675-4e0b-82f4-9cb69ebfd024">
Filter类无法点出idView
<img width="639" alt="e5f3246393c973312d6629bd333869d2" src="https://github.com/user-attachments/assets/d9b948ae-f414-4ae3-a68d-a77412dab9c2">

**Comment by babyfish-ct** [comment]
无法重现，是否修改实体后忘记编译/运行一次？

**Comment by babyfish-ct** [comment]
无法重现无反馈，关闭
