### ISSUE TITLE
[Bug] 递归查询和权限过滤在一起时，递归查询失效

### ISSUE THREAD

**Issue by 36k** [babyfish-ct/jimmer#677]
![9683252f-42d7-4d7a-b671-f79a1c1d417c](https://github.com/user-attachments/assets/65e65fe4-cd9f-4c80-ad21-b6d3897cb0ef)
![90035dd55ffddb24deb58e17e695501e](https://github.com/user-attachments/assets/5b2e7e03-4487-428c-9ce6-55193b15f920)
![2bc04007eedef5211016618b6a1e16dc](https://github.com/user-attachments/assets/e2bf1e82-060f-4e27-8e88-259fcc25a460)

**Comment by babyfish-ct** [comment]
Try `0.8.181`
