### ISSUE TITLE
[fr] Allow to customize jimmer aggregate functions return type

### ISSUE THREAD

**Issue by belovaf** [babyfish-ct/jimmer#679]
In complex cases I want to be able to customize aggregate functions return type.
For example, `sum(table.intProp)` can easily exceed `int` limit, so I want to define this expression type as `long`.

It would be great if I could define some reusable aggregate functions by myself.
Currently aggregate expression classes are internal.

**Comment by babyfish-ct** [comment]
Try `sumAsLong`
