### ISSUE TITLE
[BUG] 计算属性非空设置了getDefaultValue()覆盖返回返回非null 缓存为却为null 导致报错

### ISSUE THREAD

**Issue by LanXa7** [babyfish-ct/jimmer#681]
![image](https://github.com/user-attachments/assets/16a1daa8-32d9-4359-8e52-6268b5e28c27)
我的返回的Map的长度小于ids参数传入的集合长度，根据文档里说的这表示部分数据没有计算结果，其中每一个数据对应的计算值将会被视为null
![image](https://github.com/user-attachments/assets/3ed56381-81ff-4f82-8dac-92acd67d6aff)
此时报错
![image](https://github.com/user-attachments/assets/75e01250-bf80-430d-a5a3-d924f0ec98ca)
查看redis缓存发现存储的值为null 而非默认值0
![image](https://github.com/user-attachments/assets/4fa48266-6df8-4a17-ad93-e425c815d375)

**Comment by babyfish-ct** [comment]
Try `0.8.182`
