### ISSUE TITLE
[Bug] sqlClient.update(input: Input<E>) 方法在 Key 冲突时，不会抛出 SaveException.NotUnique 异常

### ISSUE THREAD

**Issue by dejavuhuh** [babyfish-ct/jimmer#689]
### 问题描述
如下图所示，在调用 `sqlClient.update(input: Input<E>)` 方法时，如果存在 Key 冲突，会抛出原始的 `SQLException`，而不是 Jimmer 封装的 `SaveException.NotUnique` 异常：
<img width="1150" alt="image" src="https://github.com/user-attachments/assets/55089edd-cc9a-421e-b148-ac17c8ee71f5">
这里的 input 对象是由 dto 文件生成的：
<img width="490" alt="image" src="https://github.com/user-attachments/assets/003892f6-a19a-4fd3-883d-2559e3b0ba3d">
对应的实体定义如下：
<img width="296" alt="image" src="https://github.com/user-attachments/assets/32ec43e1-387a-430c-8cfc-90cb079e58b5">
### 问题初步排查
`EntityInvestigator` 类的 `translateAll` 和 `translateOne` 方法存在差异：

translateAll() 这里的 if 条件是 shape.getIdGetters().isEmpty()，在 update 时为 fasle：
<img width="878" alt="564a6a568483013293ff4e6df16502e3" src="https://github.com/user-attachments/assets/2914d3e8-c15b-4409-b983-a1ec49e94094">

而 translateOne() 这里的 if 条件是 entity.__isLoaded(idPropId)，在 update 时为 true：
<img width="881" alt="41bcba34d68a091f195e171b385a1a96" src="https://github.com/user-attachments/assets/683c8c07-637e-4190-9673-5660b7f85229">

**Comment by babyfish-ct** [comment]
Try `0.8.185`
