### ISSUE TITLE
`Draft` 中属性赋值时错位

### ISSUE THREAD

**Issue by aboutZZ** [babyfish-ct/jimmer#69]
**UPDATE**
导致BUG原因：`AbstractEntity`的派生类所生成的Draft类`XXXDraft`中，`Implementor.__get(prop: Int): Any?`方法中字段下标顺序与基类`AbstractEntityDraft`字段下标顺序不一致

## 问题描述
定义了`AbstractEntity`基类，其中有 `createTime` 和 `updateTime`属性。定义 `DraftInterceptor`, 当插入表数据时自动设置`createTime`为当前时间:
```kotlin
@MappedSuperclass
interface AbstractEntity {
    val createTime: LocalDateTime
    val updateTime: LocalDateTime
}

class BaseEntityDraftInterceptor : DraftInterceptor<AbstractEntityDraft> {
    override fun beforeSave(draft: AbstractEntityDraft, isNew: Boolean) {
        if (isNew && !isLoaded(draft, AbstractEntity::createTime)) {
            draft.createTime = LocalDateTime.now()
        }
    }
}
```
期望结果：`createTime` 被设为当前时间
实际结果：`updateTime` 被设为当前时间，插表的 INSERT SQL语句字段也只有 `updateTime`没有`createTime`

## 原因分析猜测
框架代码里面可能有涉及到 entity 属性的索引下标（例如： 0,1,2）但是索引下标错位，或者是根据类查找字段（因为这几个字段都是 `LocalDateTime`），导致赋值错误。

为了证实不是个例，我在 AbstractEntity 中，在 `createTime`和`updateTime`中穿插添加了几列`columnA、B、C`
```kotlin
@MappedSuperclass
interface AbstractEntity {
    val columnA: LocalDateTime
    val createTime: LocalDateTime
    val columnB: LocalDateTime
    val updateTime: LocalDateTime
    val columnC: LocalDateTime
    val createBy: String?

    val updateBy: String?
}
```
再次运行代码，结果是`columnC`被赋值为当前时间（调试结果见下图）
生成的 INSERT 语句为（没有 `createTime` ）：
```SQL
insert into sys_api_access_log(COLUMN_C, USER_ID, USER_TYPE, REQUEST_METHOD, REQUEST_URI, REQUEST_PARAMS, IP, USER_AGENT, START_TIME, DURATION, STATUS_CODE, CODE, MESSAGE) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
```
![image](https://user-images.githubusercontent.com/15063761/233826717-cfb9606f-eae2-4d32-a213-ba5bd48d43f4.png)

**Comment by babyfish-ct** [comment]
我这边不知如何重构，把你的基接口、派生接口，以及二者的Draft，打个压缩包，附带在本issue上。

**Comment by aboutZZ** [comment]
[code.zip](https://github.com/babyfish-ct/jimmer/files/11339073/code.zip)

`AbstractEntityDraft.kt#L70` 以及 `ApiAccessLogDraft.kt#L104` 顺序不一致

**Comment by babyfish-ct** [comment]
![image](https://user-images.githubusercontent.com/15168900/235907600-dc0ae0ff-aa3a-492b-8c83-1020855ef5c9.png)

我用你附件中的实体实测，没问题

**Comment by aboutZZ** [comment]
该问题出现于多模块项目。下面的附件是一个简单的样例工程代码，用于复现该问题。`AbstractEntity`位于`data`公共模块，`ApiAccessLog`位于`app`业务模块。
[jimmer-issue-69-recurrence.zip](https://github.com/babyfish-ct/jimmer/files/11392339/jimmer-issue-69-recurrence.zip)

**Comment by babyfish-ct** [comment]
哦

**Comment by babyfish-ct** [comment]
是不是data重新生成代码了而app没有？

如果是这个问题，解决办法：报错，基本类型被修改，派生类项目需要重新生成代码（虽然它的代码没有变）。

**Comment by aboutZZ** [comment]
> 是不是data重新生成代码了而app没有？
> 
> 如果是这个问题，解决办法：报错，基本类型被修改，派生类项目需要重新生成代码（虽然它的代码没有变）。

执行`gradle clean`确保所有生成代码被清除，然后重新build，问题存在。

PS：你可以试下我提供的那个工程。
PS：个人猜测此问题出现的原因是`data`被编译成`jar`包后被`app`引用，而编译成的`jar`包中字段顺序是按照字段名排序。因此在生成`ApiAccessLogDraft`代码时，要读取`AbstractEntityDraft #__get`方法中的字段顺序，而不是`AbstractEntity`中的字段顺序。

**Comment by babyfish-ct** [comment]
懂了

**Comment by babyfish-ct** [comment]
It is closed by github automatically, reopen it.

Try `0.7.51` please.
