### ISSUE TITLE
maven进行install的时候报的错

### ISSUE THREAD

**Issue by CreaksD** [babyfish-ct/jimmer#691]
Cannot invoke "org.babyfish.jimmer.client.meta.TypeName.isPrimitive()" because the return value of "org.babyfish.jimmer.client.meta.impl.TypeRefImpl.getTypeName()" is null

**Comment by babyfish-ct** [comment]
How to reproduce it? can you give a minimized reproduction package?

**Comment by babyfish-ct** [comment]
长时间无反馈，关闭

**Comment by CreaksD** [comment]
同这个错误，但是maven install之后 或者是compile之后就好了

**Comment by babyfish-ct** [comment]
元数据更新依赖apt/ksp，编译时生成很多辅助数据。

实际开发中，触发apt/ksp最简单的办法，点击Intellij的运行按钮(mvn compile和gradlew build太慢)。所以，如果修改了API原数据，用Intellij再次运行即可
