### ISSUE TITLE
[bug] H2 and Postgresql returns different updated row count on merge

### ISSUE THREAD

**Issue by belovaf** [babyfish-ct/jimmer#696]
The problem is that currently jimmer uses a simplified merge statement which always updates all matched and unmatched rows.
Postgresql uses `insert on conflict do nothing` which doesn't touch matched rows.

H2 supports more advanced merge syntax, which can work exactly as postgresql `insert on conflict do nothing`:
```
MERGE INTO TARGET T USING (VALUES (1, 4), (2, 15)) S(ID, V)
    ON T.ID = S.ID
    WHEN NOT MATCHED THEN INSERT VALUES (S.ID, S.V);
```

More examples can be found here:
https://www.h2database.com/html/commands.html?highlight=mergeUsing&search=merge#merge_using

**Comment by babyfish-ct** [comment]
Done, please pull
