### ISSUE TITLE
[Feature Request] Add an API to get the count directly

### ISSUE THREAD

**Issue by TokgoRonin** [babyfish-ct/jimmer#7]
Pagination Query are too cumbersome now. 
```
TypedRootQuery<Long> countQuery = query
    .reselect((q, t) ->
        q.select(t.count())
    )
    .withoutSortingAndPaging();

int rowCount = countQuery.execute().get(0).intValue();
List<Book> books = query
    .limit(rowCount / 3, rowCount / 3)
    .execute();
```
I wish it could be simplified to an API to get the count directly, like this
```
long count = query.getCount();
```
Because I think the specific implementation details should be understood as source code and should not appear in everyday use. It is much easier and faster to use only one API to get the results.

**Comment by babyfish-ct** [comment]
0.2.4.

Examples are also changed.
