### ISSUE TITLE
建议移除KRepository中findById的Optional返回，改为Kotlin的可空类型

### ISSUE THREAD

**Issue by Enaium** [babyfish-ct/jimmer#70]
虽然有了`findNullable`方法是Kotlin的可空类型，但`findById`这个方法名比`findNullable`更明确是使用ID来查询的，所以我希望`findById`使用Kotlin的可空类型

**Comment by ClearPlume** [comment]
那就有一个问题，Java下没有可空类型

**Comment by babyfish-ct** [comment]
findById->Optinal是spring的基接口CrudRepository接口强迫的，无法改变。
