### ISSUE TITLE
jimmer还有大量不合理的依赖，需要清理和梳理

### ISSUE THREAD

**Issue by thegenius** [babyfish-ct/jimmer#701]
169K  antlr-runtime-3.5.3.jar
  1.3M   antlr4-4.13.0.jar
  319K   antlr4-runtime-4.13.0.jar
3.1M     kotlin-reflect-1.9.25.jar
1.6M     kotlin-stdlib-1.9.25.jar
961B    kotlin-stdlib-jdk7-1.9.25.jar
967B    kotlin-stdlib-jdk8-1.9.25.jar
尤其是这堆antlr和kotlin的依赖，是在使用java的运行态包中依然有依赖，这对项目打包大小有非常不利的影响，
随着项目逐渐走向成熟，这里是需要做的清理工作。
另外，我在搭建一个通用脚手架项目，默认选择了jimmer作为ORM，有兴趣可以试用看看
https://github.com/open-halo/halo-starter

**Comment by babyfish-ct** [comment]
Jimmer天生Java/Kotlin一体，即使最基础的能力也是双重考虑，所以Kotlin依赖无法除（其实不重要，反正jimmer-spring-boot-starter包含jimmer-sql-kotlin，除非不用starter纯手工构建java项目，否则去了也没用）

antlr已经去除，请尝试`0.9.3`
