### ISSUE TITLE
是否可以考虑对quarkus的支持

### ISSUE THREAD

**Issue by tzxylao** [babyfish-ct/jimmer#702]
这部分对原生代码不使用springcloud，而使用quarkus的团队来讲不够友好，不过这对作者来讲可能是小众需求了，希望有时间精力的时候可以考虑支持

**Comment by babyfish-ct** [comment]
完善的支持：https://github.com/flynndi/quarkus-jimmer-extension
生态：https://babyfish-ct.github.io/jimmer-doc/zh/docs/resource/ecosystem
