### ISSUE TITLE
[BUG]超级QBE打上!之后生成的代码依旧可空

### ISSUE THREAD

**Issue by LanXa7** [babyfish-ct/jimmer#705]
![303bcaac00f750bad2de6b49bac205f1](https://github.com/user-attachments/assets/1341ea22-fbf1-42b2-8475-821020d7b187)
![cfe2a5bebc09ee8166aa5b5243ef6439](https://github.com/user-attachments/assets/22f6bdf5-7ece-4fa4-84fc-5c288392f3f6)

**Comment by babyfish-ct** [comment]
Try `0.8.187`
