### ISSUE TITLE
[BUG] kotlin draft 生成时语句过长导致代码换行在错误的位置

### ISSUE THREAD

**Issue by pot-mot** [babyfish-ct/jimmer#707]
当前workaround: 缩短变量名称以减小语句

![31f0fda080f39ff13dbf1eb66c44dcea](https://github.com/user-attachments/assets/e1f1acdb-206f-4997-8b98-c5cbfb0c08e9)
![346c0b962014386b0fea9bf4c3da98a9](https://github.com/user-attachments/assets/3a709ed3-aa3c-4230-8efa-98b77038d272)

**Comment by babyfish-ct** [comment]
Try `0.8.187`
