### ISSUE TITLE
[Feature Request]复杂计算属性支持泛型类型为非实体的ID类型

### ISSUE THREAD

**Issue by Enaium** [babyfish-ct/jimmer#714]
`KTransientResolver<UUID, Xxx>` 
目前复杂计算属性只能像这么写或这么写，计算的结果为有泛型的类型，比如List，泛型的类型只能是实体ID的类型，比如UUID
`KTransientResolver<UUID, List<UUID>>`
实体属性
```kotlin
@Transient(XxxResolver::class)
val xxxs: List<Xxx>
```
但不能这么写，`Yyy`不是实体
`KTransientResolver<UUID, List<Yyy>>`
实体属性
```kotlin
@Transient(YyyResolver::class)
val yyys: List<Yyy>
```
要想解决这个问题现在只能写一个包装类解决
```kotlin
data class YyyList(val yyys: List<Yyy>)
```

**Comment by babyfish-ct** [comment]
Try `0.9.1`
