### ISSUE TITLE
[FR]建议将所有配置相关的API单独拿出来放到一个config里

### ISSUE THREAD

**Issue by TokgoRonin** [babyfish-ct/jimmer#715]
SqlClient的顶层API中有相当多的一部分是配置相关的API，例如：`sqlClient.fiters()`、`sqlClient.executor()`等，建议抽取出来放到一个config里，例如：
```java
sqlClient.config(it -> it.fiters() .executor())
```
这样看起来会更清晰一点，功能划分更明确

**Comment by babyfish-ct** [comment]
1. Java下会导致lambda嵌套，cfg一层，filter一层，就如同最早期saveCommand.configure(...)一样丑
2. 这些功能filters, caches, executor，虽然都由sqlClient提供，功能大相径庭，一起组合使用概率低
