### ISSUE TITLE
oracle方言有兼容性问题：where     (tb_1_.CODETYPE, tb_1_.CODECODE) = (?, ?), variables: [UserCode, 1100000187]] with root cause  oracle.jdbc.OracleDatabaseException: ORA-00920: 无效的关系运算符

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#728]
Oracle 11g
![image](https://github.com/user-attachments/assets/0d6c3cce-d1b1-496a-9300-c87d305c2d1d)

联合主键，findById
![image](https://github.com/user-attachments/assets/457408f6-a29c-4d20-85d0-0a585142780a)

**Comment by sunshio** [comment]
联合主键，findById
![image](https://github.com/user-attachments/assets/457408f6-a29c-4d20-85d0-0a585142780a)

**Comment by babyfish-ct** [comment]
无Oracle环境，请实验，是否支持Multiple Column In

**Comment by sunshio** [comment]
经实验：
1、(tb_1_.CODETYPE, tb_1_.CODECODE) = ('UserCode', '1100000187') 不行
2、(tb_1_.CODETYPE, tb_1_.CODECODE) in ('UserCode', '1100000187') 不行
3、(tb_1_.CODETYPE, tb_1_.CODECODE) in (('UserCode', '1100000187')) 可以

**Comment by sunshio** [comment]
1、(tb_1_.CODETYPE, tb_1_.CODECODE) = ('UserCode', '1100000187') 不行
2、(tb_1_.CODETYPE, tb_1_.CODECODE) in ('UserCode', '1100000187') 不行
3、(tb_1_.CODETYPE, tb_1_.CODECODE) in (('UserCode', '1100000187')) 可以
4、(tb_1_.CODETYPE, tb_1_.CODECODE) = (('UserCode', '1100000187')) 可以

> 无Oracle环境，请实验，是否支持Multiple Column In

**Comment by babyfish-ct** [comment]
Try `0.9.2`
