### ISSUE TITLE
Jimmer是否支持Solon框架、Hikaricp5、异步CompletableFuture

### ISSUE THREAD

**Issue by cnrainbing** [babyfish-ct/jimmer#732]
1. https://github.com/opensolon/solon
2. 是否可以跟Hikaricp5连接池一起使用
3. Jimmer是否支持Java CompletableFuture异步返回

**Comment by babyfish-ct** [comment]
1. Jimmer本身技术中立，可以在任何技术下使用，包括Solon
    但是是否有所基础至此，降低solon整合成本，未来有考虑，目前优先级顾不上。
2. 当然，惟一需要的就是DataSource， SpringBoot默认的就是Hikaricp5
3. 这是上层抽象，和ORM无关
