### ISSUE TITLE
能否增加对保存指令所依赖的数据库必要唯一约束的校验

### ISSUE THREAD

**Issue by SWQXDBA** [babyfish-ct/jimmer#736]
新版中 很多行为依赖数据库的唯一列约束提供的行为 如upset等
此时可以把运行保存指令所需要的唯一约束加入校验。以避免产生隐式的问题。
比如jimmer中保存短关联时 会使用一个delete not in (xx,xx)语句加一个insert ignore语句。
这个行为的正确性要求数据库中对这两个列有唯一约束，Jimmer文档中要求将中间表的两个外键作为主键。
如果忘记将这两个列添加唯一约束，可能导致在后续的关联查询中出现重复数据。

**Comment by babyfish-ct** [comment]
不能，开发人员添加`@KeyUniqueConstraint`注解时，需要明确地知道这其实是在向Jimmer承诺数据库中必然存在唯一约束/索引 
 *(这一点在@KeyUniqueContraint的doc注释上已经强调)*。那么为什么如此设计呢？

1. 一部分功能强大的数据库支持条件索引，以Postgres为例，https://www.postgresql.org/docs/current/indexes-partial.html

   可见，SQL条件被附加在了索引之上，只有满足SQL条件的数据才会被索引，而非所有数据都会被索引。如果条件索引是唯一的，那么就不再是简单的唯一约束和唯一索引可媲美的了。某些字段 *(被条件判断的字段)* 可以规定其他字段如何满足唯一行，分类讨论，当前数据满足一种唯一约束。其他数据则可能采用完全不同的唯一约束。
   
    支持条件索引的数据库有多种，但是SQL语法和元数据完全不同 *(这就是RDBMS目前最大的问题，只要功能稍微高级一丢丢，完全没用通用型)*，用数据库无关的方式提取数据的条件索引元数据都非常困难，更别说提取到SQL条件后解析条件语法这种复杂得没边的任务了。
    
2. 为了和某些数据库的条件索引呼应，目前Jimmer给了一个最基本的支持 *未来可能给予更强大的支持*，实体上静态配置的`@Key`可以被保存指令的`setKeyProps`方法动态地覆盖

所以，唯一性约束是可以一个可以深入的功能，复杂起来后，不支持非常高昂的成本，完全无法实现静态验证。目前只能在`@KeyUniqueConstraint`的文档注释中提醒开发人员：“注意，这是你许下的承诺”。

**Comment by babyfish-ct** [comment]
哦，你特指中间表，中间表可以

**Comment by babyfish-ct** [comment]
Try `0.9.9`
