### ISSUE TITLE
发现allReferenceFields()会出现要求加载的字段的加载标记位为false

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#737]
![企业微信截图_17303414319537](https://github.com/user-attachments/assets/da40ebcb-21c2-482c-9063-47aa6be4f439)

![image](https://github.com/user-attachments/assets/71a9ef09-9775-4d5a-a480-66663af4e6eb)

字段是有值的，但加载标记位为false

**Comment by sunshio** [comment]
群主自行决定该api的去留，我没意见

**Comment by babyfish-ct** [comment]
`allReferencesField`只查询所有给予外键的to-one的原始id

如果使用对象缓存，缓存的对象是完整的（有值），但是查询的形状属性更少，就会unload不需要的东西。
为了优化unloaded的性能，只设置了loaded标志，未清理数据的值。

所以，你看到了有值，但loaded为false。

所以，这不是BUG，但是迷惑。为了不迷惑，unload行为可以狠一点，把数据也干了

**Comment by babyfish-ct** [comment]
Try `0.9.9`
