### ISSUE TITLE
openapi不能正常显示

### ISSUE THREAD

**Issue by jiangdengke** [babyfish-ct/jimmer#739]
我看文档中只需要改下配置文件就行了
![image](https://github.com/user-attachments/assets/35748431-dcde-4b3c-8925-a77ebf3fd676)
然后controller这里是这样的
![image](https://github.com/user-attachments/assets/77435b7e-3660-406f-97ff-04ee0d803471)
这个是openapi的页面
![image](https://github.com/user-attachments/assets/36f3178e-470b-43bb-a369-98877db13292)

**Comment by babyfish-ct** [comment]
给出的就是提示这指引，也可以先跑官方例子（最好的学习方法，没有之一）
