### ISSUE TITLE
[Feature Request] DTO生成文件支持smart-doc

### ISSUE THREAD

**Issue by hywlzx** [babyfish-ct/jimmer#740]
smart-doc文档生成根据字段上面的注释和注解进行，而jimmer的dto文件生成之后的注释和注解在方法上面。导致无法生成对应的文档。

![image](https://github.com/user-attachments/assets/8254a738-0961-4327-b997-9f449b6d7415)
![image](https://github.com/user-attachments/assets/981fb4bf-f9c8-4aa5-b55b-797ee4ff31f5)

能否在生成dto文件的的时候，将注释和注解也在字段上面添加一下。

**Comment by babyfish-ct** [comment]
Try `0.9.6`

吐槽，真SB框架真JB拉，作为文档解析库居然总是假设文档在字段上，要别人各种插屁股

推荐时Jimmer的文档功能，一样的识别Java/Kotlin的文档注释。还支持直接返回被@FetchBy修饰的实体（如果查询仅仅对外暴露Web接口，Jimmer Output DTO不再是唯一的选择），因此和Jimmer适配更好。https://babyfish-ct.github.io/jimmer-doc/zh/docs/client/api
