### ISSUE TITLE
[BUG] Insert failed when boolean value is null

### ISSUE THREAD

**Issue by Madeoke** [babyfish-ct/jimmer#741]
Reproducer:

Entity:

`
@Entity
@Table(name = "TEST_ENTITY")
interface TestEntity{

    @Id
    val id: Long

    val booleanOk: Boolean?
}
`

Dao:
`class TestTestEntityDao(
    private val sql: KSqlClient
) {

    fun save(testEntity: TestEntity): Int {
        return sql.save(testEntity).totalAffectedRowCount
    }
}`

Test:
`    @Test
    public void saveTestEntityToDbJava() {
        TestEntity booleanOkIsNull = new TestEntityDraft.Builder()
                .id(1L)
                .booleanOk(null)
                .build();
        testTestEntityDaoV2.save(booleanOkIsNull);
    }`

EXPECTED: Successfully saved an entity
ACTUAL: org.postgresql.util.PSQLException: ERROR: column "boolean_ok" is of type boolean but expression is of type smallint

I am using testContainers postgres:15-alpine

bug is not reproducing when i'm using h2

**Comment by babyfish-ct** [comment]
If the type of pg column to boolean, is it OK?

BTW, don' tuse `TestEntityDraft.Builder` because it should only be used by mapstruct(Kotlin mapstruct is depcrecated), You should use 
```
val testEntity = TestEtntity {
    id = 1L
    bookeanOk = null
}
```

**Comment by Madeoke** [comment]
> If the type of pg column to boolean, is it OK?
> 
> BTW, don' tuse `TestEntityDraft.Builder` because it should only be used by mapstruct(Kotlin mapstruct is depcrecated), You should use
> 
> ```
> val testEntity = TestEtntity {
>     id = 1L
>     bookeanOk = null
> }
> ```

DB type is boolean (nullable) and if i insert true/false its fine. I think problem is somewhere/somehow  null is casting to smallint

**Comment by babyfish-ct** [comment]
Try `0.9.6`
