### ISSUE TITLE
oracle下使用saveEntities保存，一旦发生sql异常会导致org.babyfish.jimmer.sql.ast.impl.mutation.EntityInvestigator#investigate中出现数组越界问题，从而导致真正的错误无法被报出

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#745]
![image](https://github.com/user-attachments/assets/64825e2c-bf32-4957-a76d-1573ed41bbed)
最终导致报出Index 0 out of bounds for length 0，而真正的sqlException没有报出来

**Comment by babyfish-ct** [comment]
PG?

**Comment by babyfish-ct** [comment]
没有Oracle环境，盲猜原因，Oracle下`ex.getUpdateCounts()`返回的数组长度是成功执行的语句数量，而非初始语句数量。

**Comment by babyfish-ct** [comment]
尼玛，果然如此
> Retrieves the update count for each update statement in the batch update that executed successfully before this exception occurred. A driver that implements batch updates may or may not continue to process the remaining commands in a batch when one of the commands fails to execute properly. If the driver continues processing commands, the array returned by this method will have as many elements as there are commands in the batch; otherwise, it will contain an update count for each command that executed successfully before the BatchUpdateException was thrown.

**Comment by babyfish-ct** [comment]
Try `0.9.7`
