### ISSUE TITLE
生成的Typescript的接口请求参数不为可空

### ISSUE THREAD

**Issue by Enaium** [babyfish-ct/jimmer#75]
![图片](https://user-images.githubusercontent.com/32991121/234438778-a5dd9818-10c2-445d-ad44-6dca583fd84a.png)
参数不为可空
![图片](https://user-images.githubusercontent.com/32991121/234438850-3f51cfa8-bf7a-42fa-a61d-0d6ad4c6134d.png)
input内正常
![图片](https://user-images.githubusercontent.com/32991121/234438919-d76a3675-0f89-4af1-a7fd-dabf7113699b.png)

**Comment by babyfish-ct** [comment]
Try 0.7.50
