### ISSUE TITLE
[Feature Request] 支持多组 @Key 配置

### ISSUE THREAD

**Issue by dejavuhuh** [babyfish-ct/jimmer#750]
### 问题背景
假设一个场景：`User` 表存在 `username` 和 `email` 两个唯一约束字段，当 `@Key` 标注在 `username` 字段上时，如果 `email` 字段发生唯一性冲突，Jimmer 会抛出原始的 SQL 异常，而不是经过事后调查的 `SaveException.NotUnique` 异常

### 期望
Jimmer 支持多组 `@Key` 配置：
1. 不论哪一组 Key 发生唯一性冲突，都能正确抛出 `SaveException.NotUnique` 异常
2. `SaveCommand` 的 upsert 逻辑也能根据该配置进行动态的 Key 抉择

**Comment by SWQXDBA** [comment]
我认为这里实际上是@Id与@Key的一种扩充。其目的是提供一种更新Key字段的形式。

问题起因是我们需要一种 修改数据行中key字段的方法。虽然理论上key标识了一行数据在业务上的唯一性， 是业务主键。但是有的时候也有对其进行修改的需求。
当我们需要修改非业务主键字段时 需要标识出需要修改的数据是哪一行，再给出要修改的字段和值
update table set notKeyField= other where keyField = ?
这里的keyField就是@Key注解标注的字段，可能有多个。
update table set notKeyField= other where keyField1 = ? and keyField2 = ?

当我们需要对其进行修改时，意味着这个业务主键和这条数据的绑定关系被打破了，我们需要另一个办法来描述这一行唯一的数据。目前jimmer中的方式是通过ID。
打个比方，如果你指定了id和key字段，你就可以修改这条数据的key属性
update table set keyField = other where id = ?

以一组Key为基准、来更新其他Key组字段。
比如 在目前的版本中，如果指定了Id和所有Key字段。那么允许通过这种方法来修改数据库中那一行的Key字段。此时实际上是以Id group为基准。

我们把这种能力进行一种延伸，定义新的规则如下：
在保存时 如果指定了一组key中的某一个字段，则必须指定这组key中的全部字段。
必须选中一个或者几个Key Group作为参照基准。其中主键ID实际上是一种特殊的，强制包含的Key Group。

在保存时 我们会以座位参照基准的一个或几个Key Group的所有字段在数据库中判断是否存在数据 如果不存在则插入新的。
每个Key Group在数据库中必须有专门的唯一索引/唯一约束。保证根据一个Key Group中的所有字段 在数据库中只能找到唯一的行。

**Comment by SWQXDBA** [comment]
假设有
```
class Entity{
id
@Key(group1)
field1
@Key(group1)
field2
@Key(group2)
field3
@Key(group2)
field4
@Key(group3)
field5
@Key(group3)
field6
}
```
此时 存在四组Key
ID Group
Group1
Group2
Group3

假设我们想通过Group2中的字段作为基准来更新Group3中的字段
update(Entity{
field3
field4
field5
field6
}){
setKeyGroup("group2")
}
此时可能会有
update table set field5 = xxx ,field6 = xxx where field 3 = xxx and field 4 = xxx;
注意 由于这里的field5和field6是key 可能数据库中有其他列有这样的数据，这可能会导致更新违反唯一约束。
要不要在此直接根据field5和field6进行select一次进行报错取决于jimmer想怎么实现，这里只是给出概念

**Comment by SWQXDBA** [comment]
对于题主的问题，可以以另一个角度思考。
当数据库中因为非key字段检测报错时该如何处理？
假设我只在jimmer中指定了一部分字段的唯一性，然后在实际操作的时候因为其他约束报错了(不仅仅是唯一约束)。这个时候，我们只能相信用户给的数据是对的，直接抛出数据库的异常。

就算是现有的Id和key之间也会有这个问题
假设通过id把key改成另一个已有的重复值，也会有类似的报错。


假设数据库中已经有了
{
id:222
key:222
}
然后我们执行保存
{
id:111
key:222
}
会有这样的sql 
update table set key = 222 where id = 111
此时会造成key重复 在数据库层面报错。

**Comment by babyfish-ct** [comment]
Try `0.9.11`
