### ISSUE TITLE
[bug] 在生成客户端API时出现数字开头的属性名

### ISSUE THREAD

**Issue by shuTwT** [babyfish-ct/jimmer#757]
model/static/httpStatusCode
![image](https://github.com/user-attachments/assets/ae8a3f25-60f3-4e1b-8203-ebcb3e566e46)
org.springframework.http.HttpStatusCode
![image](https://github.com/user-attachments/assets/59092d86-056c-4e10-ae22-8e6ae87c62a9)
is没了

**Comment by Enaium** [comment]
看看接口代码

**Comment by babyfish-ct** [comment]
`is`是java属性的getter前缀。默认情况下下，要抹去（数据开头不能抹去，的确是新发现的问题）

如果不想抹去`is`，可以设置javac参数`jimmer.keepIsPrefix`，以gradle为例

```
tasks.withType<JavaCompile>().configureEach {
    options.compilerArgs.add("-Ajimmer.keepIsPrefix=true")
}
```

以maven为例
```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>3.13.0</version>
  <configuration>
    <compilerArgs>
      <arg>-Ajimmer.keepIsPrefix=true</arg>
    </compilerArgs>
  </configuration>
</plugin>
```
