### ISSUE TITLE
[Feature Request] Currently, the serialization of dynamic objects is completely covered by Jimmer. I hope to relax some restrictions and allow Jackson's PropertyNamingStrategy to take effect

### ISSUE THREAD

**Issue by ClearPlume** [babyfish-ct/jimmer#76]
As the title, I hope this configuration of Jackson's can take effect. Currently, the fields returned to the front end are all camelCase, which is not compatible with old projects.

```kotlin
jsonMapper {
    propertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE)
}
```

**Comment by babyfish-ct** [comment]
Try 0.7.50

**Comment by babyfish-ct** [comment]
Not only `PropertyNamingStrategy`, but also `@JsonProperty` and `@JsonAlias`
