### ISSUE TITLE
[BUG]配置多数据源会导致项目启动失败

### ISSUE THREAD

**Issue by wzszsw** [babyfish-ct/jimmer#769]
配置代码
![image](https://github.com/user-attachments/assets/9c73e25c-f828-4db4-8743-82dad023fa57)

现象：项目无法启动
![image](https://github.com/user-attachments/assets/37b51f71-c409-4384-a9cd-d57de9996c15)

分析：
debug发现，项目启动时，会去调用JTransactionalSqlClient的sqlClient方法
![image](https://github.com/user-attachments/assets/bb37f1b6-90ef-45b6-abd1-b717cfcd5de7)
![image](https://github.com/user-attachments/assets/2f12bea3-bf22-43f8-a37d-f7ca913b7823)
此报错应为没有事务上下文导致，然而项目启动时必然是没有aop事务上下文的，故推断此报错不应该在项目初始化阶段触发

**Comment by babyfish-ct** [comment]
Try `0.9.12`
