### ISSUE TITLE
[Bug] During deserialization, the @JsonProperty annotation on the properties cannot be recognized by the @Serialized annotation

### ISSUE THREAD

**Issue by ClearPlume** [babyfish-ct/jimmer#77]
```kotlin
interface Strategy {
    @Serialized
    val config: List<StrategyConfig>
}
```
![Serialized不识别JsonProperty注解](https://user-images.githubusercontent.com/18047536/235043320-b75e6d2f-5670-4994-ac51-16e78b972a14.png)

**Comment by babyfish-ct** [comment]
This is not bug, you used jackson in wrong way, the @JsonProperty must be used *TWICE*!

1. `@field:JsonPropety("...")`, for serialization
2. `@param:JsonProperty("...")`, for deserialization, all parameters must be decorated by that annotation when  **non-default** constructor is used to deserialize

**Comment by ClearPlume** [comment]
> This is not bug, you used jackson in wrong way, the @JsonProperty must be used **TWICE**!
> 
>     1. `@field:JsonPropety("...")`, for serialization
> 
>     2. `@param:JsonProperty("...")`, for deserialization, all parameters must be decorated by that annotation when  **non-default** constructor is used to deserialize

Okay, I got it...
