### ISSUE TITLE
长关联保存，抢夺其他父对象的子对象的行为仍然没有防御

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#770]
版本：0.9.11

![image](https://github.com/user-attachments/assets/ee08d4e1-7caf-40c0-9389-f8d59110e60c)

![image](https://github.com/user-attachments/assets/41706a10-3c9f-4914-a291-b2233902d082)

**Comment by babyfish-ct** [comment]
所有版本都没有这个问题，请参见单元测试: https://github.com/babyfish-ct/jimmer/blob/dev/project/jimmer-sql/src/test/java/org/babyfish/jimmer/sql/mutation/CascadeSaveTest.java 中的 `testTransferForbid`

如果save command级别没有明确制定是否抢夺，那么受sqlClient上全局配置影响。因此你很可能在save command官方例子的基础上修改代码得到了错误的结论，因为那个例子有全局配置。
