### ISSUE TITLE
[Feature Request] InputDTO 声明必填属性时，希望生成的代码中移除默认值

### ISSUE THREAD

**Issue by dejavuhuh** [babyfish-ct/jimmer#772]
### 问题描述
定义如下 `InputDTO`，指定 `id` 属性必填
![image](https://github.com/user-attachments/assets/c11e69cb-7fa5-4180-ba71-28611a76a3f9)
最终生成的代码中，`id` 属性会存在默认值
![image](https://github.com/user-attachments/assets/589f30f6-a9fb-4182-8d80-40a872e99a2f)
这样，当前端没有传递 `id` 属性时，就会给一个默认值 0，而预期是“前端没有传递 id 时，就报错”

### 预期行为
声明必填属性时，生成的代码中移除默认值

**Comment by babyfish-ct** [comment]
Try `0.8.14`
