### ISSUE TITLE
经过确认，子对象迁移的防御确实存在问题

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#775]
版本0.9.12

![image](https://github.com/user-attachments/assets/9e41f1e2-b1c5-4bee-a20e-5cdbb2e1428b)

![image](https://github.com/user-attachments/assets/595b94b3-b751-404d-8a04-910ca9cc8f59)
 仍然执行成功

**Comment by sunshio** [comment]
这是我单独抽取的工程，没有加过多配置

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jimmer?allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password:
jimmer:
  show-sql: true
  database-validation:
    mode: error
    catalog: jimmer

**Comment by sunshio** [comment]
org.babyfish.jimmer.sql.ast.impl.mutation.Operator#isChanged

![image](https://github.com/user-attachments/assets/afc9d377-a2f9-4e16-8c3e-daadab3118b5)

**Comment by sunshio** [comment]
![image](https://github.com/user-attachments/assets/840770f7-12b9-4f6d-b368-14674f824aa3)
这循环里的return是不是有点问题？

**Comment by babyfish-ct** [comment]
可能是DraftInterceptor内部逻辑的问题，是不是对BookProps.STORE进行了unload，让其无法比较，你先去掉DraftInterceptor试试

**Comment by babyfish-ct** [comment]
0.9.15对此问题进行了主动防御，有助于调查

**Comment by sunshio** [comment]
实测发现：去除BaseEntityDraftInterceptor，但手动设置createdTime和modifiedTime仍出现此问题，设置price还是出现此问题，似乎只有key only时能防御

以下是去除BaseEntityDraftInterceptor后的情况
![image](https://github.com/user-attachments/assets/3d459794-82f7-45e5-82e6-fa29746acfaa)
这个不行

![image](https://github.com/user-attachments/assets/ea1e22f1-20c9-4052-b90f-bf99d98a72aa)
这个可以

**Comment by sunshio** [comment]
![image](https://github.com/user-attachments/assets/f41a58d0-3bbe-46c8-a844-a19886afc5aa)

**Comment by babyfish-ct** [comment]
OK， 知道原因了。下班后处理

**Comment by babyfish-ct** [comment]
Try `0.9.16`
