### ISSUE TITLE
是否已支持软删除？

### ISSUE THREAD

**Issue by g770728y** [babyfish-ct/jimmer#78]
v0.7.47版的deleteById第2个参数为DeleteMode, 看起来应该支持了, 但没有找到具体用法示例

**Comment by babyfish-ct** [comment]
是的，这个细节老文档没同步。支持软删除的实体，需要一个字段，被`@LogicalDeleted`修饰

`@LocalDeleted`字段可以有很多类型，boolean, int, 枚举，日期（靠是否为null）

`@LocalDeleted`有两个参数，
- `value`: 当实体被软删除后应该设置的值
- `restoredValue`: 被软删除的实体重新被保存后的恢复值

`value`是必须指定的
`restoredValue`是可选的，如果该字段只有两个选项，比如boolean，只有两个常量的枚举，可以不给；否则必须给。一切以框架的验证异常为准

**Comment by g770728y** [comment]
已测可用，感谢 ^_^
