### ISSUE TITLE
@Nullable修饰的属性，使用isNull时报错

### ISSUE THREAD

**Issue by sunshio** [babyfish-ct/jimmer#781]
官方例子：
![image](https://github.com/user-attachments/assets/c3455cea-c2ef-4505-99f7-b7f24bafa776)
![image](https://github.com/user-attachments/assets/97b374f0-9452-4bfa-a44f-c1099fc09808)

**Comment by sunshio** [comment]
发现其实是leftJoin的问题：
![image](https://github.com/user-attachments/assets/11a9538a-a482-40ab-a9ee-77a8c9ca4fc3)
但是这个报错提示明显有问题，并且这是官方例子报出来的

Unable to instantiate the "is null" predicate, the path "TreeNode.parent" is non-null expression

**Comment by babyfish-ct** [comment]
Try `0.9.16`
