### ISSUE TITLE
使用spring的Page分页产生日志警告

### ISSUE THREAD

**Issue by zengyufei** [babyfish-ct/jimmer#787]
环境和版本描述：idea2024.1 + kotlin + springboot3.3 + jdk17

基础：基于 jimmer-sql-kt 

使用 spring 的 Page 对象 和 Pageable 对象进行分页查询：

Controller 层代码

![image](https://github.com/user-attachments/assets/18ded90b-a552-4cc4-b77a-9587b7ea9c09)

Service 层代码

![image](https://github.com/user-attachments/assets/26efc790-ce3d-4361-9875-3aa84720e263)

问题：

产生 spring 方面的警告

![image](https://github.com/user-attachments/assets/71d11bf6-7153-4193-a54b-a3375b0d266b)

经搜索查询解决版本如下：

但是产生两种截然不同的返回结构

![image](https://github.com/user-attachments/assets/5e23f1c0-b36d-4057-b874-08b56532eb54)

加了解决办法之后的结构：

![image](https://github.com/user-attachments/assets/08c47ba8-4602-47b1-84f1-5d87226ed613)

下面是原版，方便对比：

![image](https://github.com/user-attachments/assets/f354a319-e842-4890-b907-6b7089c02fe4)

**Comment by Enaium** [comment]
这是Spring Data的问题和jimmer无关，这是Spring Data新加的
