### ISSUE TITLE
not generate type for dto when use @Serialized on dto.

### ISSUE THREAD

**Issue by qifan777** [babyfish-ct/jimmer#789]
# 1. Entity
*BaseOrder*

```java
@Entity
public interface BaseOrder extends BaseEntity {
    /**
     * 地址详情
     */
    @Serialized
    @Null
    AddressView address();
}
```

*Address*

```java
@GenEntity
@Entity
public interface Address extends BaseEntity {

    /**
     * 维度
     */
    double latitude();

    /**
     * 经度
     */
    double longitude();

   /**
     * 省略...
     */
}
```
# 2. Dto

1. write AddressView in address.dto 
```text
input AddressInput {
    #allScalars(Address)
    id
    -province
    -district
    -city
}
//AdressView{
//    #allScalars(Address)
//}
specification AddressSpec {
    #allScalars
    associatedIdEq(creator)
}
```
2. copy AddressView from generated source to src
3. use AddressView in BaseOrder 
```java
@Serialized
@Null
AddressView address();
```

# 3. Generate Type 
![`FGDVRU}%U}@7B6GYQ_ROIM](https://github.com/user-attachments/assets/a69337f0-751f-4361-a49e-ef4c24cb7c57)

**Comment by babyfish-ct** [comment]
Add unit test: https://github.com/babyfish-ct/jimmer/blob/main/project/jimmer-client/src/test/kotlin/org/babyfish/jimmer/client/kotlin/ts/GisServiceTest.kt

Like this issuse, a generated file is moved into src manually: https://github.com/babyfish-ct/jimmer/blob/main/project/jimmer-client/src/test/kotlin/org/babyfish/jimmer/client/kotlin/model/GisRegionView.kt

No problem found

**Comment by qifan777** [comment]
> Add unit test: https://github.com/babyfish-ct/jimmer/blob/main/project/jimmer-client/src/test/kotlin/org/babyfish/jimmer/client/kotlin/ts/GisServiceTest.kt
> 
> Like this issuse, a generated file is moved into src manually: https://github.com/babyfish-ct/jimmer/blob/main/project/jimmer-client/src/test/kotlin/org/babyfish/jimmer/client/kotlin/model/GisRegionView.kt
> 
> No problem is found

please add a new Entity *ProductOrder* and only use ProductOrder in Controller. 

```java
@Entity
public interface ProductOrder {

    @Id
    @GeneratedValue(generatorType = UUIDIdGenerator.class)
    String id();

    /**
     * 基础订单
     */
    @ManyToOne
    BaseOrder baseOrder();
}
```

**Comment by babyfish-ct** [comment]
Try `0.9.22`
