### ISSUE TITLE
[Bug] deleteById(id) 生成的 SQL 在 MySQL 8 下执行报错

### ISSUE THREAD

**Issue by dejavuhuh** [babyfish-ct/jimmer#791]
### 问题描述
我有一个树形的菜单表(menu)，我调用 deleteById 方法去删除某个菜单的时候，Jimmer 生成了下面这个 SQL
![eaa715487038619295fc8cdd39a99e50](https://github.com/user-attachments/assets/d367fde3-bde9-4a1b-9c5e-d2ce07c61dc1)
SQL：delete from menu tb_1_ where exists(select * from menu tb_2_ where tb_1_.PARENT_ID = tb_2_.ID and tb_2_.PARENT_ID = ?)
这个 SQL 在 MySQL 8 版本下执行会报错，报错原因是：You can't specify target table 'tb_1_' for update in FROM clause
![436ef1adf873f85087779ad977b1660c](https://github.com/user-attachments/assets/2a70ef8b-5c61-4614-9808-b129c5cf89a2)
实体定义如下：
![image](https://github.com/user-attachments/assets/2fdaaa79-b840-4c28-8273-c90dc85136e2)

**Comment by SWQXDBA** [comment]
应该是因为 Mysql不允许修改子查询中出现的表。。。坑爹
这里exists中select了要delete表导致的
https://stackoverflow.com/questions/45494/mysql-error-1093-cant-specify-target-table-for-update-in-from-clause

**Comment by babyfish-ct** [comment]
Try `0.9.20`
