### ISSUE TITLE
[Feature Request] @JoinTable tableName Default Naming Strategy Optimization

### ISSUE THREAD

**Issue by zhanglolo** [babyfish-ct/jimmer#794]
使用中间表进行多对一关联时，`@JoinTable(name = "")` 中 `name` 是根据实体的类名进行拼接。

当给实体取了具体的表名后`@Table(name = "branch_info")`和`@Table(name = "user_info")`，希望可以优化默认命令逻辑，优先按照表名来拼接`name = "user_info_branch_info_mapping"`，目前还是按照类名拼接，虽然是可以自定义，但是这样会更加智能。

```kotlin
@Entity
@Table(name = "branch_info") //明确表名为 branch_info
interface Branch {

  @Id
  val id: Long

  val name: String

  @OneToMany(mappedBy = "branch")
  val users: List<User>
}

@Entity
@Table(name = "user_info") //明确表名为 user_info
interface User {
  @Id
  val id: Long

  val name: String

  @ManyToOne
  //希望是使用表名 user_info 和 branch_info 进行拼接
  //@JoinTable(name = "user_info_branch_info_mapping", joinColumnName = "user_id", inverseJoinColumnName = "branch_id")
  //目前的默认值是user_branch_mapping
  @JoinTable(name = "user_branch_mapping", joinColumnName = "user_id", inverseJoinColumnName = "branch_id")
  val branch: Branch?
}

```

---------

When using an intermediate table for a many-to-one association, the `name` in `@JoinTable(name = "")` is concatenated based on the entity's class name.

After specifying a specific table name for the entity like `@Table(name = "branch_info")`和`@Table(name = "user_info")`, it is desirable to optimize the default naming logic to prioritize concatenation based on the table name. Currently, it still concatenates based on the class name like `name = "user_info_branch_info_mapping"`, which would be more intelligent.

**Comment by babyfish-ct** [comment]
- When it is designed at first time, that design way cannot be used because of some special reasons, but now I forget these reasons.
- It cannot be changed because many users and projects depend on current strategy.
