### ISSUE TITLE
添加了ImmutableModule仍然无法进行序列化?

### ISSUE THREAD

**Issue by nyndyhx** [babyfish-ct/jimmer#795]
![image](https://github.com/user-attachments/assets/d66ae064-7dbc-4e09-b38b-6e7c15a97690)

报错:
```
DefaultHandlerExceptionResolver : Resolved [org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: Immutable object cannot be serialized by ordinary ObjectMapper, please register the "class org.babyfish.jimmer.jackson.ImmutableModule" into the ObjectMapper]
```

按照提示在ObjectMapper中添加了ImmutableModule，Bean也装配也执行了，但是依旧没有效果，请问是什么原因？

Jimmer和Sprintboot都使用的最新版

**Comment by Enaium** [comment]
你用SpringBoot默认就能序列化，可能你用了什么其他的东西把默认的给换掉了

**Comment by nyndyhx** [comment]
> 你用SpringBoot默认就能序列化，可能你用了什么其他的东西把默认的给换掉了

```
// @Configuration
class WebConfig : WebMvcConfigurationSupport()
```

注释之后就可以正常返回了😇(但里面的配置代码怎么办?..._(:> _||_)_ )

**Comment by babyfish-ct** [comment]
虽然Jimmer实体非POJO，所以，需要ImmutableModule。

但Jackson序列号化/反序列化已经稳定了数年，出错一定是上层配置让Spring世纪用户序列化的ObjectMapper并非注册了ImmutableModule的ObjectMapper.

生成`dummayPropForJacksonError`，就是为了诱导出有意义的报错信息。

只需要抛开spring的上层建筑，手动用注册了ImmutableModule的ObjectMapper既可验证这绝非Jimmer自身的问题

**Comment by nyndyhx** [comment]
> 虽然Jimmer实体非POJO，所以，需要ImmutableModule。
> 
> 但Jackson序列号化/反序列化已经稳定了数年，出错一定是上层配置让Spring世纪用户序列化的ObjectMapper并非注册了ImmutableModule的ObjectMapper.
> 
> 生成`dummayPropForJacksonError`，就是为了诱导出有意义的报错信息。
> 
> 只需要抛开spring的上层建筑，手动用注册了ImmutableModule的ObjectMapper既可验证这绝非Jimmer自身的问题

我的WebConfig里面什么都没写，注释之后就可以正常返回，请问大佬这是springboot的原因吗？

**Comment by babyfish-ct** [comment]
默认的web config可能就已经修改最终生效的ObjectMapper了

**Comment by xflcx1991** [comment]
感谢楼主思路，我已经在一个自定义 ObjectMapper的项目里集成成功了。
![图片](https://github.com/user-attachments/assets/8cba62e3-af2a-4941-a916-b301a57a16f2)
