### ISSUE TITLE
[Bug]save 关联对象时，若有多个关联对象的 key 相同时，发生错误: id unloaded

### ISSUE THREAD

**Issue by Arkmusn** [babyfish-ct/jimmer#798]
# 前提

- 聚合根：app_collection
- 关联对象：app_collection_item
    - key：app_collection_id, source, package_name
    - ![ee640f8904b2b6237563aa2a833d4004](https://github.com/user-attachments/assets/c96b3157-ef74-4c50-aa28-cb1b94b78e26)
- 其中 app_collection -> app_collection_item 的关联关系为一对多
![c718602258b89fee45e6bfa5bbcc7dcd](https://github.com/user-attachments/assets/edbfabdf-7dac-479a-9325-c486bf02a14f)

## save  command
![image](https://github.com/user-attachments/assets/500e87b1-010b-4cbb-b983-8649e46956b3)

# Exception
![fcbec3e60207aa0a3140b37df7cfb605](https://github.com/user-attachments/assets/c6834adb-4f12-4b63-af51-b81c72995032)

# Debug view

- 能够获取到 id 的关联对象 A
- ![image](https://github.com/user-attachments/assets/de4ce9a1-66d9-478e-8edb-77276efb5fed)
- 无法获取到 id 的关联对象 B
- ![image](https://github.com/user-attachments/assets/ee829aed-25a0-45d5-be76-e7ebcaa826db)

**Comment by Arkmusn** [comment]
update
原因是因为 save 的时候传入了两个 key 一样的关联对象。

以下示例可以复现
https://github.com/Arkmusn/jimmer-issue-report

**Comment by babyfish-ct** [comment]
Try `0.9.20`
