### ISSUE TITLE
Ts生成类型不包含null 只有undefined

### ISSUE THREAD

**Issue by SWQXDBA** [babyfish-ct/jimmer#804]
当前在生成typescript 可空属性时 会生成
property?:string | undefined
这样有两个问题
第一个 加了?的可选属性 默认类型已经包含undefined了 因此后面的|undefined是无意义的，应该可以去掉
第二个 可空熟悉应该允许为null 不然与input dto 的null能力不符
https://babyfish-ct.github.io/jimmer-doc/zh/docs/mutation/save-command/input-dto/null-handling?_highlight=null#%E6%95%B0%E6%8D%AE%E5%BD%95%E5%85%A5%E4%B8%ADnull%E7%9B%B8%E5%85%B3%E7%9A%84%E9%97%AE%E9%A2%98
建议修改为property?:string | null

**Comment by babyfish-ct** [comment]
和JS不同，TS下undefined的开发体验远胜null.

因此，默认情况下，只生成null，服务端要么不输出null，要么在客户端fetch中处理。

如果要改变默认行为: `jimmer.client.ts.null-reader-mode = NULL_OR_UNDEFINED` *(默认UNDEFINED)*

**Comment by SWQXDBA** [comment]
好的 application.properties中添加

jimmer.client.ts.null-render-mode=NULL_OR_UNDEFINED
