### ISSUE TITLE
input dto 无法使用jackson反序列化注

### ISSUE THREAD

**Issue by zengyufei** [babyfish-ct/jimmer#807]
![65T)TEGQK0 XEC5F2YLPNNF](https://github.com/user-attachments/assets/f9f16771-b88b-488a-8c66-639cfb24e8e8)

生成的 input dto实体类

![$R)GLJBXH2NZUW 51U1H@2I](https://github.com/user-attachments/assets/fc53519d-b1ec-4446-ae8e-9d4517870ed0)

加入下面参数也无效

ksp {
   arg("jimmer.dto.mutable", "true")
}

**Comment by babyfish-ct** [comment]
Try `0.9.23`
