### ISSUE TITLE
[Bug] 使用 @RequestHeader 注解时，如果参数名称带有“-”，会导致生成的 ts 客户端代码编译报错

### ISSUE THREAD

**Issue by dejavuhuh** [babyfish-ct/jimmer#808]
### 问题描述
如下图所示，使用 `@RequestHeader("Client-Code")`：
![image](https://github.com/user-attachments/assets/0651e215-4ae3-4c84-9bd1-aee8b5362e68)
最终产生的 ts 客户端代码如下：
![image](https://github.com/user-attachments/assets/eca87c76-5007-48a7-8918-cfe527793e9b)
很明显有一个语法错误：
```javascript
// 编译报错
const obj = { Client-Code: "xxx" }
// 正确语法
const obj = { "Client-Code": "xxx" }
```

**Comment by babyfish-ct** [comment]
Try `0.9.23`
