### ISSUE TITLE
[Feature Request] 支持 stars =  stars +1 这种增量更新操作

### ISSUE THREAD

**Issue by zhoulijun89** [babyfish-ct/jimmer#812]
例如：
需要记录接口的访问次数，又不想每次查询数据库。
希望能实现这种增量更新数据操作。upsert的也支持就更好

**Comment by pot-mot** [comment]
可以直接createUpdate中plus指定列，这个对应的数据库操作就是直接在数据库原基础上加一

**Comment by Enaium** [comment]
https://babyfish-ct.github.io/jimmer-doc/zh/docs/showcase/update-statement/

**Comment by babyfish-ct** [comment]
> https://babyfish-ct.github.io/jimmer-doc/zh/docs/showcase/update-statement/

如是，此功能有update语句提供

**Comment by zhoulijun89** [comment]
感谢解答，我再去仔细看看文档
