### ISSUE TITLE
[Feature Request] 希望 Super QBE 支持隐式子查询中使用 valueIn 等集合函数

### ISSUE THREAD

**Issue by dejavuhuh** [babyfish-ct/jimmer#813]
### 问题描述
隐式自查询的写法如下图所示：
<img width="212" alt="bb1aa05859a627fc3a187d4b064f2326" src="https://github.com/user-attachments/assets/b64480a1-f313-45f0-9be8-cc9d15678231">
尝试了 QBE 中的两个函数，都不能达到上面这种写法的效果：
1、associatedIdIn: 这种方式生成的 SQL 没有用到 exists，破坏了分页的正确性
<img width="271" alt="d41823fa54c760907be4c7982be9797c" src="https://github.com/user-attachments/assets/18aa54f9-63e4-469e-8cb4-6e40092a4267">
2、flat: 这种方式生成的 SQL 是 exists 子查询，但是生成的 DTO 属性不是集合，而是单个
<img width="146" alt="781038e8b73f44388b8d19f349a4af0f" src="https://github.com/user-attachments/assets/3b426f8d-8146-474d-9674-3b3b23a2d694">

**Comment by babyfish-ct** [comment]
```
flat(roles) {
    valueIn(id) as roleIds
}
```

specification只做查询规格，不表达数据，所以specification DTO得集合属性仍然生成对象，是最大特色
