### ISSUE TITLE
不支持拓展数据库方言

### ISSUE THREAD

**Issue by 1208709619** [babyfish-ct/jimmer#815]
在DialectDetector类中getDialectOrNullForDriver写死了数据库方言，无法进行拓展
![image](https://github.com/user-attachments/assets/e70a3239-9267-493f-9cea-a705007524a6)

**Comment by Enaium** [comment]
https://babyfish-ct.github.io/jimmer-doc/zh/docs/configuration/dialect/#%E8%AE%BE%E7%BD%AE%E6%96%B9%E8%A8%80

**Comment by babyfish-ct** [comment]
Try `0.9.24`
