### ISSUE TITLE
[Feature Request] 增加update与delete语句中对where非索引列的优化

### ISSUE THREAD

**Issue by onetiaoxianfish** [babyfish-ct/jimmer#816]
当表 user 存在 id，name，
name不加索引或不是唯一索引，再更新或删除时会导致间隙锁，存在死锁风险
能否优化成下面的样子，可以有效避免死锁问题，也能避免在业务层去手动先查询再更新
```sql
update user u1,(select id form user where name='u') u2 set u1.name='q' wher u1.id=u2.id
```
不过感觉这个只适合单表，连表更新可能并不好用。

**Comment by babyfish-ct** [comment]
此功能在计划中，这需要修改DSL，支持让sub query成为from, join甚至修改操作的基表。

这是是1.0版本需要实现的大功能。不会为普通issue执行如此大的动作。

这歌问题用jdbc规避，Jimmer不提供native AP，是因为采用的方案是让jimmer的spring事务的支持和spring-jdbc事务完全兼容，因此不需要Jimmer支持native API，直接spring jdbc即可。
