### ISSUE TITLE
[Feature Request] - ksp 支持 将 typealias 解析为 actual type

### ISSUE THREAD

**Issue by TrueNine** [babyfish-ct/jimmer#822]
### Reason

```bash
建议将 ksp 的 解析改为解析真实类型
```

### Description

```bash
有时字段的定义并非直接的类型，而是使用 kotlin 的 typealias 语法特性，这有助于代码的清晰程度。
但发现很多时候，ksp 插件并非将真实类型做处理，而是将其直接作为符号类型进行解析处理。
```

**Comment by Enaium** [comment]
别名早就支持了

**Comment by babyfish-ct** [comment]
It has been supported, but some bugs about jakarta validation was found and fixed.

Please try `0.9.27`

Here is the example: https://github.com/babyfish-ct/jimmer/blob/main/project/jimmer-sql-kotlin/src/test/kotlin/org/babyfish/jimmer/sql/kt/model/classic/book/Book.kt, all tests are passed.

If there are still some problems in your scenario, please describe reproducing steps clearly
