### ISSUE TITLE
[Feature Request] - Using jimmer to manage transactions in Ktor

### ISSUE THREAD

**Issue by QingMingKt** [babyfish-ct/jimmer#824]
### Reason

```bash
I found that I used the jimmer framework without using Spring, and it was very difficult to handle transactions.
```

### Description

I hope to provide a usage method similar to sqlClient.useTransaction {}

**Comment by Enaium** [comment]
Look this
https://github.com/babyfish-ct/jimmer/issues/771#issuecomment-2492717778

**Comment by babyfish-ct** [comment]
It is design for JDBC, and hope java virtual thread can be optimized as soon as possible.

For R2DBC, it is huge project(save command is super complex), so it will not be implement unless java virtual thread still disappoint everyone after 1~2 years.

If you programming mode is JDBC, please view https://github.com/babyfish-ct/jimmer/blob/main/project/jimmer-spring-boot-starter/src/main/java/org/babyfish/jimmer/spring/cfg/support/SpringConnectionManager.java. 

Don't simply open and close connections. You need to understand what data structures your technology stack uses to manage connections, and use them to borrow and return connections.

**Comment by babyfish-ct** [comment]
Close it because it duplicated with #771
