### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by qinarmy-zoro** [babyfish-ct/jimmer#83]
你自己的项目，你刷提交次数干嘛. 老的刷提交次数的优点，你一个中国人怎么学上了。

**Comment by babyfish-ct** [comment]
- 项目足够复杂，需要频繁发版，定期解决已有用户的问题或期望。

- 目前用爱发电，脱产开发，想为理想贡献一个优质项目，因为全职开发，而且还是每天都加班加点开发，所以每天的开发量都非常大，并不是闲暇时光做来玩的。

我不需要刷什么东西，以小人之心度君子之腹，你个傻逼！

**Comment by qinarmy-zoro** [comment]
<img width="1663" alt="Screen Shot 2023-05-04 at 06 33 56" src="https://user-images.githubusercontent.com/12522817/236065539-e1ed8e55-66ec-4aad-8fde-e6f623c49a87.png">

这不是吗

**Comment by qinarmy-zoro** [comment]
一个 readme 分钟之内你都能刷这么次，不要轻易叫别人傻逼。我提问，是因为我看了你的代码，而且是同行。

**Comment by qinarmy-zoro** [comment]
从同行的角度，我明白你说 的 项目足够复杂 ，但我认为你的复杂不是因为 mapping sql 世界造成的，是设计思想和方向的问题.
平心的建议你停一下，想一下思想和方向,也许你会想重构. 我的项目也重构多次，我知道这个过程.

**Comment by babyfish-ct** [comment]
我是正常批新戴月开发，我付出了多少你知道吗？你一上来的就定性我的恶心刷更新。这是和沟通的预期吗？

README更新了很多次，是因为github的Markdown排版总达不到要求，一些布局达不到我的要求，多排几次版本惹你生气了。

目前，有很多用户在沟通，提issue，提新需求，大家交流都很开心。但唯独你一上来就如此定型说我恶意更新，就算我排版失误，多更新几次咋了？

**Comment by babyfish-ct** [comment]
一上来就定性故意刷更新的帽子并质问，我不骂你骂谁？

**Comment by qinarmy-zoro** [comment]
这个我道歉，不过你的设计思想会让你的项目越来越复杂而且使用越来类似JPA,对于大规模application 项目是个麻烦.平心建议你停下来想一想。 我这几年停产研发总结出两条 1. 当越来越复杂时,你这一定忘了大道至简. 2. 当犹豫不决时，问一下为什么放弃之前的设计，回到叉路口。

**Comment by qinarmy-zoro** [comment]
你发布太早,我几年都没发布,就是因为思想不对。不过现在快了，因为相对成熟了。停下来，玩一玩，放松放松，林纳斯·本纳第克特·托瓦兹 也知道休息。思想错了只会越来越复杂.

**Comment by babyfish-ct** [comment]
你可以问我为什么某些非代码文件更新特别频繁，但是不能先恶意揣测并用“你一个中国人怎么学上了”这样的话来挖苦，真的很不礼貌。

不过道歉了，就没事了。

目前你接触的时间不长，Jimmer绝非JPA, 等下我把二维码更新了，你进入交流群和交流意见。一堆玩得贼6的老用户

**Comment by babyfish-ct** [comment]
二维码已经更新（五一假期脱更了），你应该能进群了。

**Comment by qinarmy-zoro** [comment]
我说的是思想类似 JPA, 任意对象树,多对多，一对多这些概念. 你应该这么想，sql 世界不存在多对多,一对多, 所有关系只业务上的 join 而已. MyBatis 这样的框架能 用这么多年，就是因为它的思想是 对接 sql 世界. 而 JPA 和 Hibernate 的思想是创建新世界屏蔽 sql 世界,但没有成功屏蔽，也不可能屏蔽,所以有了 native sql.

**Comment by qinarmy-zoro** [comment]
重要的是设计思想，你的这套思想会带你进入更复杂的世界.

**Comment by qinarmy-zoro** [comment]
你看过 JOOQ 代码吗，sql style 的思想是好的，但具体设计思想机械而僵硬 ,从三个方面 可证明:
1. org.jooq.DSLContext 方法数量
2.  方法重载逻辑
3. 一个方法居然有 22 个泛型.
这就是设计思想的重要性。

**Comment by babyfish-ct** [comment]
所有ORM都用过，对比各种ORM和DTOMapper(比如JOOQ, MyBatis)对比了很多年,  非Java的ORM也用过，日日夜夜思考这个ORM领域20年。

或许脱离JPA、MyBatis和JOOQ的固有认知，完全重新认识，方能海况天空。如果对此项目有兴趣，但是有很多疑问和不解（比如感觉有点像JPA），不妨进群，让一批jimmer老用户告诉你为什么他们什么既看不上JPA也看不上MyBatis。

**Comment by qinarmy-zoro** [comment]
我现在只能告诉你 sql 世界不存在多对多,一对多, 所有关系只是业务上的 join 而已，想清楚这一点你的项目将简洁很多。Hibernate 的作者是看 SQL 书后写的 Hibernate,SQL书中提到的 一对多，多对多这些概念使作者走错路。还有一些思想不便多说。等过一段时间我的项目发布了，我 at 你。你就明白了。我也脱产研发几年。我付出的决不比你少。看你走错路，有点感觉像自己走错路。你的视频中提到任意深度的对象树，会使你不够大道至简，你想过做过的这些对象树，我也想过走过。

**Comment by qinarmy-zoro** [comment]
就是说没有什么 多对多，对象树， sql 世界里只有 standard sql 的dialect sql, 记住 "sql 世界"这个关键词. 要把它当成一个世界，你会发现 一个 小小的 join 子句便是一片天地。当然我说的是 用java表达 sql 的情况下，如果用文本写 sql,那就什么都没有,就是 字符串。

**Comment by qinarmy-zoro** [comment]
停一停，玩一玩，乐一乐，宇宙爆了，也玩一玩。就像 电视剧中 于敏 团队搞氢弹，停一停思路就打开了。我不会加入群的，我目前只和同行聊，我走过的路没走过的人是不理解的。

**Comment by babyfish-ct** [comment]
> 这句是关键：Hibernate 的思想是创建新世界屏蔽 sql 世界,但没有成功屏蔽

这就是传统ORM傻逼的地方，想做这事又做不到，统一处理模式却不能灵活，于是人们不得不请出MyBatis。

而MyBatis的灵活是以重复劳动为代价的，直接面DTO爆炸问题，把众多雷同却不同的DTO分别做CRUD mapper。

Jimmer能做不到传统ORM想做却做不到的事，你信也罢不信也罢，都不重要了。项目完成后也不用at我，完全不同的派别，武断而缺乏包容，认定Hibernate办不到的事直接认定别人也办不到，相谈也不快，你不是我的同路人。

不用回复。

**Comment by qinarmy-zoro** [comment]
我错了，我们应该有不同路径，百家争鸣。
