### ISSUE TITLE
[BUG] - PostgreSQL updates fields using aliases and reports errors，更新字段使用别名报错

### ISSUE THREAD

**Issue by zengyufei** [babyfish-ct/jimmer#835]
### Jimmer Version

0.9.32

### JDK Version

JDK17

### Database

PostgreSQL

### OS

Windows

### Expected behavior

期望该sql执行成功！

```sql
SQL: update t_help_doc_relation tb_1_ set tb_1_.delete_flag = ? /* 1 */
where
        tb_1_.help_doc_id = ? /* 8962760602013401089 */
    and
        tb_1_.tenant_id = ? /* 1 */
    and
        tb_1_.delete_flag <> ? /* 1 */ 
```

### Actual behavior

实际情况报错了：

```java
Caused by: org.postgresql.util.PSQLException: ERROR: column "tb_1_" of relation "t_help_doc_relation" does not exist
```

### Description

生成的sql去postgresql执行，也是报错了，查阅资料后，发现postgresql并不支持set字段带别名。

即：

```sql
update  xxxx as 别名
   SET 别名.yyy = 1   // 不支持 "别名.yyy = 1"，只能是 "yyy = 1"
```

### Reproduction steps

1

### Generated SQL

UPDATE t_help_doc_relation AS tb_1_ 
SET tb_1_.delete_flag = '1' 
WHERE
	tb_1_.help_doc_id = '8737580617381519363' 
	AND tb_1_.tenant_id = '1' 
	AND tb_1_.delete_flag <> '1'

### Screenshots

![image](https://github.com/user-attachments/assets/bf38420a-1270-4c77-8667-3fa4bc65a6f6)

![5H`YFZR2W32Y4`~DS7EGM5E](https://github.com/user-attachments/assets/b8c044d4-24e8-4211-987e-bc618ea48862)

**Comment by luqiuzhi** [comment]
PostgreSQL确实不支持在`update`语句的`set`中使用别名。`set`的字段前面可以使用表的全称。没想到竟然在`delete`里面出现了`update`的错误😂

**Comment by zengyufei** [comment]
> PostgreSQL确实不支持在`update`语句的`set`中使用别名。`set`的字段前面可以使用表的全称。没想到竟然在`delete`里面出现了`update`的错误😂

？？？逻辑删除啊

**Comment by luqiuzhi** [comment]
> PostgreSQL确实不支持在`update`语句的`set`中使用别名。`set`的字段前面可以使用表的全称。没想到竟然在`delete`里面出现了`update`的错误😂

我知道是逻辑删除，只是觉得这个bug藏得还挺深。

**Comment by babyfish-ct** [comment]
> PostgreSQL确实不支持在`update`语句的`set`中使用别名。`set`的字段前面可以使用表的全称。没想到竟然在`delete`里面出现了`update`的错误😂

下级对象脱钩

**Comment by babyfish-ct** [comment]
Try `0.9.33`
