### ISSUE TITLE
[BUG] -  fetchSlice 错误的offset自增

### ISSUE THREAD

**Issue by LoptrX** [babyfish-ct/jimmer#836]
### Jimmer Version

0.9.3

### JDK Version

JDK 21

### Database

Postgres

### OS

Windows

### Expected behavior

![f534538a4713468ab1f2fa5cde1a4c16](https://github.com/user-attachments/assets/0740b7e8-17c4-4276-873f-678945df2c9f)

### Actual behavior

![image](https://github.com/user-attachments/assets/bf060570-6d7d-4905-95d4-7350ceb61372)

### Description

使用 fetchSlice 查询时会 jimmer 会给 offset + 1，导致结果和预期不一致

### Reproduction steps

org.babyfish.jimmer.sql.ast.impl.query.ConfigurableRootQueryImpl#fetchSlice(1,1)

### Generated SQL

select
	tb_1_.CONNECTION_NUM
from
	MEMBER_CONNECTION tb_1_
where
	tb_1_.MEMBER_ID = '1856604516602871808'
	and tb_1_.STARTED_AT <= '2024-12-16'
	and tb_1_.EXPIRED_AT >= '2024-12-16'
	and tb_1_.deleted is null
limit 1 offset 1

**Comment by babyfish-ct** [comment]
Try `0.9.33`
