### ISSUE TITLE
[BUG] - <文档介绍中Kotlin工具方法的fromString并不存在>

### ISSUE THREAD

**Issue by LanXa7** [babyfish-ct/jimmer#839]
### Jimmer Version

0.9.34

### JDK Version

JDK21

### Database

Mysql

### OS

Windows

### Expected behavior

可以使用fromString

### Actual behavior

使用fromString报错

### Description

![a6986c671c62e8202a2405fef8d58bf5](https://github.com/user-attachments/assets/c087c803-d64a-465a-8980-5932eb66eae7)
Kotlin：

![9b80ede395b7c2a2e47f21afa45ec0de](https://github.com/user-attachments/assets/901a7f48-4e00-4c7f-b221-f94f37ec45c7)

Java：
![345037141e18416085b2a8e782c00856_720](https://github.com/user-attachments/assets/1a0dd729-fd81-4c20-9fa3-637c2cbb9644)

### Reproduction steps

无

**Comment by babyfish-ct** [comment]
Try `0.9.35`
