### ISSUE TITLE
[BUG]  jimmer.error-translator.http-status is not working on swagger

### ISSUE THREAD

**Issue by bingo084** [babyfish-ct/jimmer#842]
### Jimmer Version

0.9.34

### JDK Version

JDK 22

### Database

PostgreSQL

### OS

Linux

### Expected behavior

Error response status code should be `jimmer.error-translator.http-status`

### Actual behavior

Error response status code is always 500

### Description

When `jimmer.error-translator.http-status` is set, the actual error response code is the set value, but the error response code in the generated swagger is always 500

### Reproduction steps

Change  `jimmer.error-translator.http-status` to some value except 500, thow `CodeBasedException` in code. Enable swagger generator, see the error response code.

**Comment by babyfish-ct** [comment]
Try `0.9.35`
