### ISSUE TITLE
[BUG] - 0.9.34版本下dto文件的JsonIgnore注解失效

### ISSUE THREAD

**Issue by llh4github** [babyfish-ct/jimmer#843]
### Jimmer Version

0.9.34

### JDK Version

21

### Database

h2

### OS

Windows

### Expected behavior

```
BookBaseView{
    id
    name
    @com.fasterxml.jackson.annotation.JsonIgnore
    edition
}
```

字段edition不应被json化。

### Actual behavior

0.9.34 会出现json中。0.9.15版本不会。

### Description

我从0.9.15升到0.9.34，dto文件中被JsonIgnore修饰的字段突然出现中响应体中了。

### Reproduction steps

[demo4jimmer.zip](https://github.com/user-attachments/files/18208372/demo4jimmer.zip)
```
 val jimmerVersion = "0.9.34"
//val jimmerVersion = "0.9.15"
```
修改版本号，调用接口就可以复现。

### Screenshots

![image](https://github.com/user-attachments/assets/1c53c4b5-5b74-49aa-96c9-1d80bd42f645)

**Comment by babyfish-ct** [comment]
Try `0.9.35`
