### ISSUE TITLE
[BUG] - <title>逻辑删除执行语句会导致死循环

### ISSUE THREAD

**Issue by zxzf1234** [babyfish-ct/jimmer#845]
### Jimmer Version

0.9.9

### JDK Version

jdk17

### Database

mysql

### OS

Windows

### Expected behavior

可以正常删除，上传了model层文件和error
([error.txt](https://github.com/user-attachments/files/18218765/error.txt))

### Actual behavior

一直在执行select和update语句 死循环

### Description

死循环

### Reproduction steps

执行的语句是 customerInfoRepository.deleteByIds(ids)

### Relation Model

`
package cn.iocoder.yudao.service.model.customer.info;

import cn.iocoder.yudao.service.model.base.BaseEntity;
import cn.iocoder.yudao.service.model.system.user.SystemUser;
import cn.iocoder.yudao.service.model.infra.data.DictCountry;
import cn.iocoder.yudao.service.model.infra.data.DictProvince;
import cn.iocoder.yudao.service.model.infra.data.DictCity;
import cn.iocoder.yudao.service.model.infra.data.DictDistrict;
import cn.iocoder.yudao.service.model.system.dept.SystemDept;
import cn.iocoder.yudao.service.model.customer.contact.CustomerContact;
import cn.iocoder.yudao.service.model.customer.contact.CustomerContact;
import cn.iocoder.yudao.service.model.customer.info.CustomerImage;
import cn.iocoder.yudao.service.model.customer.info.CustomerWebsite;
import org.babyfish.jimmer.sql.*;
import java.time.LocalDateTime;
import org.jetbrains.annotations.Nullable;
import java.util.List;

@Entity
public interface CustomerInfo extends BaseEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    long id();

    String customerNo();

    String name();

    String mainImageUrl();

    Long source();

    Long grade();

    Long stage();

    Long state();

    @IdView
    @Nullable
    Long ownerId();

    @ManyToOne
    @Nullable
    @OnDissociate(DissociateAction.DELETE)
    SystemUser owner();

    @IdView
    @Nullable
    Long countryId();

    @ManyToOne
    @Nullable
    @OnDissociate(DissociateAction.DELETE)
    DictCountry country();

    @IdView
    @Nullable
    Long provinceId();

    @ManyToOne
    @Nullable
    @OnDissociate(DissociateAction.DELETE)
    DictProvince province();

    @IdView
    @Nullable
    Long cityId();

    @ManyToOne
    @Nullable
    @OnDissociate(DissociateAction.DELETE)
    DictCity city();

    @IdView
    @Nullable
    Long districtId();

    @ManyToOne
    @Nullable
    @OnDissociate(DissociateAction.DELETE)
    DictDistrict district();

    String address();

    @IdView
    @Nullable
    Long deptId();

    @ManyToOne
    @Nullable
    @OnDissociate(DissociateAction.DELETE)
    SystemDept dept();

    String customField1();

    String customField2();

    String customField3();

    String customField4();

    String customField5();

    String customField6();

    String customField7();

    String customField8();

    String customField9();

    String customField10();

    String customField11();

    String customField12();

    String customField13();

    String customField14();

    String customField15();

    String customField16();

    String customField17();

    String customField18();

    String customField19();

    String customField20();

    @IdView
    @Nullable
    Long mainContactId();

    @ManyToOne
    @Nullable
    @OnDissociate(DissociateAction.DELETE)
    CustomerContact mainContact();

    Boolean isRecycle();

    @Nullable
    @LogicalDeleted("now")
    LocalDateTime deletedTime();

    @OneToMany(mappedBy = "customer")
    List<CustomerContact> contacts();

    @OneToMany(mappedBy = "customer")
    List<CustomerImage> images();

    @OneToMany(mappedBy = "customer")
    List<CustomerWebsite> websites();

}

package cn.iocoder.yudao.service.model.customer.info;

import cn.iocoder.yudao.service.model.base.BaseEntity;
import cn.iocoder.yudao.service.model.customer.info.CustomerInfo;
import org.babyfish.jimmer.sql.*;
import java.time.LocalDateTime;
import org.jetbrains.annotations.Nullable;

@Entity
public interface CustomerWebsite extends BaseEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    long id();

    @IdView
    @Nullable
    Long customerId();

    @ManyToOne
    @Nullable
    @OnDissociate(DissociateAction.DELETE)
    CustomerInfo customer();

    String website();

    @Nullable
    @LogicalDeleted("now")
    LocalDateTime deletedTime();

}

package cn.iocoder.yudao.service.model.customer.info;

import cn.iocoder.yudao.service.model.base.BaseEntity;
import cn.iocoder.yudao.service.model.customer.info.CustomerInfo;
import org.babyfish.jimmer.sql.*;
import java.time.LocalDateTime;
import org.jetbrains.annotations.Nullable;

@Entity
public interface CustomerImage extends BaseEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    long id();

    @IdView
    @Nullable
    Long customerId();

    @ManyToOne
    @Nullable
    @OnDissociate(DissociateAction.DELETE)
    CustomerInfo customer();

    String url();

    @Nullable
    @LogicalDeleted("now")
    LocalDateTime deletedTime();

}

package cn.iocoder.yudao.service.model.customer.contact;

import cn.iocoder.yudao.service.model.base.BaseEntity;
import cn.iocoder.yudao.service.model.customer.info.CustomerInfo;
import cn.iocoder.yudao.service.model.customer.contact.CustomerContactBusinessCard;
import cn.iocoder.yudao.service.model.customer.contact.CustomerContactMail;
import cn.iocoder.yudao.service.model.customer.contact.CustomerContactPhone;
import cn.iocoder.yudao.service.model.customer.contact.CustomerContactSocialMedia;
import org.babyfish.jimmer.sql.*;
import java.time.LocalDateTime;
import org.jetbrains.annotations.Nullable;
import java.util.List;

@Entity
public interface CustomerContact extends BaseEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    long id();

    String name();

    Long sex();

    String address();

    String position();

    Long decisionRole();

    Long workState();

    String customField1();

    String customField2();

    String customField3();

    String customField4();

    String customField5();

    String customField6();

    String customField7();

    String customField8();

    String customField9();

    String customField10();

    @IdView
    @Nullable
    Long customerId();

    @ManyToOne
    @Nullable
    @OnDissociate(DissociateAction.DELETE)
    CustomerInfo customer();

    Boolean isMain();

    @Nullable
    @LogicalDeleted("now")
    LocalDateTime deletedTime();

    @OneToMany(mappedBy = "contact")
    List<CustomerContactBusinessCard> businessCards();

    @OneToMany(mappedBy = "contact")
    List<CustomerContactMail> mails();

    @OneToMany(mappedBy = "contact")
    List<CustomerContactPhone> phones();

    @OneToMany(mappedBy = "contact")
    List<CustomerContactSocialMedia> socialMedias();

}

package cn.iocoder.yudao.service.model.customer.contact;

import cn.iocoder.yudao.service.model.base.BaseEntity;
import cn.iocoder.yudao.service.model.customer.contact.CustomerContact;
import org.babyfish.jimmer.sql.*;
import java.time.LocalDateTime;
import org.jetbrains.annotations.Nullable;

@Entity
public interface CustomerContactBusinessCard extends BaseEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    long id();

    @IdView
    @Nullable
    Long contactId();

    @ManyToOne
    @Nullable
    @OnDissociate(DissociateAction.DELETE)
    CustomerContact contact();

    String url();

    @Nullable
    @LogicalDeleted("now")
    LocalDateTime deletedTime();

}

package cn.iocoder.yudao.service.model.customer.contact;

import cn.iocoder.yudao.service.model.base.BaseEntity;
import cn.iocoder.yudao.service.model.customer.contact.CustomerContact;
import org.babyfish.jimmer.sql.*;
import java.time.LocalDateTime;
import org.jetbrains.annotations.Nullable;

@Entity
public interface CustomerContactMail extends BaseEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    long id();

    @IdView
    @Nullable
    Long contactId();

    @ManyToOne
    @Nullable
    @OnDissociate(DissociateAction.DELETE)
    CustomerContact contact();

    String mailAddress();

    @Nullable
    @LogicalDeleted("now")
    LocalDateTime deletedTime();

}

package cn.iocoder.yudao.service.model.customer.contact;

import cn.iocoder.yudao.service.model.base.BaseEntity;
import cn.iocoder.yudao.service.model.customer.contact.CustomerContact;
import org.babyfish.jimmer.sql.*;
import java.time.LocalDateTime;
import org.jetbrains.annotations.Nullable;

@Entity
public interface CustomerContactPhone extends BaseEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    long id();

    @IdView
    @Nullable
    Long contactId();

    @ManyToOne
    @Nullable
    @OnDissociate(DissociateAction.DELETE)
    CustomerContact contact();

    String phoneNo();

    @Nullable
    @LogicalDeleted("now")
    LocalDateTime deletedTime();

}

package cn.iocoder.yudao.service.model.customer.contact;

import cn.iocoder.yudao.service.model.base.BaseEntity;
import cn.iocoder.yudao.service.model.customer.contact.CustomerContact;
import org.babyfish.jimmer.sql.*;
import java.time.LocalDateTime;
import org.jetbrains.annotations.Nullable;

@Entity
public interface CustomerContactSocialMedia extends BaseEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    long id();

    @IdView
    @Nullable
    Long contactId();

    @ManyToOne
    @Nullable
    @OnDissociate(DissociateAction.DELETE)
    CustomerContact contact();

    Integer socialType();

    String socialAccount();

    @Nullable
    @LogicalDeleted("now")
    LocalDateTime deletedTime();

}
`

**Comment by babyfish-ct** [comment]
错误原因：`DissocateAction.DELETE`出现环路导致永远转圈，必须在适当位置通过`DissocateAction.SET_NULL`打破数据关联环

`0.9.35`版本提供诊断工具，抛出CircularDeletionException来报告发现的数据关联环，包括对象类型,id以及递归路径。

可以通过指令的`setMaxCommandJoinCount(0)`来让报告的递归路径尽可能短，降低问题排查难度
