### ISSUE TITLE
[Feature Request] - createDelete不支持逻辑删除的备忘

### ISSUE THREAD

**Issue by wzszsw** [babyfish-ct/jimmer#846]
### Reason

现在createDelete的不支持逻辑删除

### Description

现在createDelete的不支持逻辑删除，备忘

**Comment by babyfish-ct** [comment]
支持，升级即可

**Comment by babyfish-ct** [comment]
![0568af793f5d96e5d9e69cd7653ae694](https://github.com/user-attachments/assets/c920020e-38a1-46f9-a041-76dbd31949f2)

**Comment by babyfish-ct** [comment]
长时间无反馈，暂且关闭
