### ISSUE TITLE
[Feature Request] - 实体对象的Builder构造，建议增加基于已有实体创建builder的功能

### ISSUE THREAD

**Issue by wzszsw** [babyfish-ct/jimmer#850]
### Reason

Book book = BookDraft.$.produce(draft -> {
            draft.setName("111");
        });
        
new BookDraft.Builder(book); //现在不支持这种用法

### Description

希望能支持这种用法，增强Builder的体验

**Comment by babyfish-ct** [comment]
Try `0.9.38`
