### ISSUE TITLE
大佬   jimmer提供的 生成客户端API 能力暂时不支持添加字段描述,方法描述, 后期会怎加这样的功能吗?

### ISSUE THREAD

**Issue by lhl-github** [babyfish-ct/jimmer#852]
### Reason

![image](https://github.com/user-attachments/assets/8e985634-62a3-48b8-b1f5-10716400904d)

现在的效果图
![image](https://github.com/user-attachments/assets/cb24c456-6f92-4f86-b5f6-270f6867330f)

### Description

是否会增加  添加字段描述,方法描述,  以及入参的校验 这样的功能呢

**Comment by babyfish-ct** [comment]
Jaa/Kotlin文档注释 /** */
