### ISSUE TITLE
[BUG] - 逻辑删除注解应用在枚举字段ksp编译时报错

### ISSUE THREAD

**Issue by BraveAustin** [babyfish-ct/jimmer#853]
### Jimmer Version

0.9.37

### JDK Version

jdk21

### Database

MySQL

### OS

Windows

### Expected behavior

编译能成功通过

### Actual behavior

编译阶段发生错误
![pic](https://github.com/user-attachments/assets/03ba4c6e-7ee9-4cc6-9516-eda30d1f75c1)

### Description

枚举值代码：
```kotlin
@EnumType(EnumType.Strategy.NAME)
enum class DelFlag(var s: String) {
    /**
     * 存在
     */
    @EnumItem(name = "E")
    EXISTENCE("存在"),

    /**
     * 删除
     */
    @EnumItem(name = "D")
    DELETE("已删除"),
}
```

实体字段注解
```kotlin
@Default("EXISTENCE")
@LogicalDeleted("DELETE")
@Column(name ="del_flag")
val delFlag: DelFlag
```

### Reproduction steps

逻辑删除注解作用于val delFlag: DelFlag时应可以正常编译通过。

### Logs

> Task :genial-biz:kspKotlin FAILED
e: lkspl Illegal property "cn.genial.comon.code.domian.entity.sysUser.delflag", the property decorated by "@Logicaleleted" must be boolean
int, enum, UuID or LocalDateTime
e: Error occurred in Ksp, check log for detail

**Comment by babyfish-ct** [comment]
Try `0.9.38`

Cannot reproduce, maybe enum and entity are belong to different sub projects, just try to fix it
