### ISSUE TITLE
[BUG] - 文档注释@param后不写内容导致ksp报错

### ISSUE THREAD

**Issue by SparrowAndSnow** [babyfish-ct/jimmer#854]
### Jimmer Version

0.9.37

### JDK Version

JDK17

### Database

PostgreSQL

### OS

Windows

### Expected behavior

ksp编译通过

### Actual behavior

编译不通过ksp报错: [ksp] java.lang.StringIndexOutOfBoundsException: String index out of range: 6

### Description

ksp版本 2.1.0-1.0.29
spring版本 3.4.1

@param后不写内容导致报错，但是@return后依然不写可以运行。

### Reproduction steps

具体代码如下
```kotlin
@EnableImplicitApi
@RestController
class BookController(val sqlClient: KSqlClient) {

    /**
     * @param
     * @return Book
     */
    @GetMapping("/book")
    fun book(): Book? {
        return sqlClient.findById(Book::class, 1)
    }
}
```
使用@EnableImplicitApi注解生成客户端代码时@param后不写内容报错。

### Screenshots

![QQ_1735300848275](https://github.com/user-attachments/assets/a289a791-5508-4bdd-ae4d-25a4b88c3db5)

**Comment by babyfish-ct** [comment]
Try `0.9.38`
