### ISSUE TITLE
[Feature Request] - 能否支持其他序列化框架？例如fastjson2、kotlinx serialization

### ISSUE THREAD

**Issue by li-fcb1899** [babyfish-ct/jimmer#855]
### Reason

fastjson2拥有更高的性能，拥有广泛的受众群体。

### Description

提供序列化接口

**Comment by babyfish-ct** [comment]
No, 非POJO的实体本身(动态）仅支持jackson，要兼容现有生态，是使用Jimmer Output DTO（静态）
