### ISSUE TITLE
[Feature Request] - <title> : 大佬 使用dto作为api入参 , 数据表中不存在的字段,但业务中需要  怎么映射 

### ISSUE THREAD

**Issue by lhl-github** [babyfish-ct/jimmer#858]
### Reason

大佬 使用dto作为api入参 , 数据表中不存在的字段,但业务中需要  怎么映射 
有没有像mubatisfles 中这样的注解
![image](https://github.com/user-attachments/assets/3cf088e8-7713-4193-9e13-74916f5e6319)

### Description

1

**Comment by babyfish-ct** [comment]
DTO支持自定义字段。和ORM无关，定义在其中即可，用户自己处理。

Issue是为BUG或新功能请求。问题请disucsson或加群
