### ISSUE TITLE
有没有办法自定义扩展函数

### ISSUE THREAD

**Issue by weifengze** [babyfish-ct/jimmer#859]
### Reason

我在写项目的时候有一些SQL语句用到了数据库中自带的函数。

### Description

这些数据库自带的函数再jimmer中没有提供，我想问一下作者有没有实现扩展函数的功能接口。

**Comment by babyfish-ct** [comment]
NativeSQL表达式

**Comment by weifengze** [comment]
下午我用这个NativeSQL表达式写出来了，这个东西很强大。
