### ISSUE TITLE
使用spring-boot-devtools时，导致获取表名为null

### ISSUE THREAD

**Issue by Enaium** [babyfish-ct/jimmer#88]
DatabaseNamingStrategy无法工作与Multi-ClassLoader场景

![Snipaste_2023-05-06_12-35-09](https://user-images.githubusercontent.com/32991121/236600030-f214219e-cd89-40b7-b364-631bc20bc8fc.png)
![Snipaste_2023-05-06_12-35-29](https://user-images.githubusercontent.com/32991121/236600031-cc8a36bb-f745-4878-9c29-82fb7b63964f.png)

**Comment by babyfish-ct** [comment]
Try `0.7.53`
