### ISSUE TITLE
用到了List<long>的delete抽象方法报错

### ISSUE THREAD

**Issue by zxzf1234** [babyfish-ct/jimmer#94]
int deleteByUserIdAndPostIdIn(Long userId, List<Long> deletePostIds);
![image](https://github.com/babyfish-ct/jimmer/assets/11207139/413d1648-f26c-4c79-a986-a2e15f560d8e)

**Comment by babyfish-ct** [comment]
Try 0.7.57

**Comment by zxzf1234** [comment]
0.7.57已经没有问题
