### ISSUE TITLE
使用case时，导致生成sql时其他表丢失

### ISSUE THREAD

**Issue by Enaium** [babyfish-ct/jimmer#96]
![](https://github.com/babyfish-ct/jimmer/assets/32991121/181ee9c1-5ae9-4b3c-91c6-e617c2b6000a)
![](https://github.com/babyfish-ct/jimmer/assets/32991121/73625b8e-c263-439e-8d75-50e37bc6258a)

**Comment by babyfish-ct** [comment]
Try `0.7.59`
