### ISSUE TITLE
生成的Typescript中，如果请求参数全为可空，会使options变为可空，导致RequestOf报错

### ISSUE THREAD

**Issue by Enaium** [babyfish-ct/jimmer#97]
![](https://github.com/babyfish-ct/jimmer/assets/32991121/d6add7a2-6f3c-42b9-8316-edcc02d4cb72)

![](https://github.com/babyfish-ct/jimmer/assets/32991121/7bb379f5-8452-4cfe-bd85-f937297c76e6)

**Comment by babyfish-ct** [comment]
Try `0.7.59`

**Comment by Enaium** [comment]
options可为undefined也会报错

**Comment by babyfish-ct** [comment]
Try `0.7.60`, give up this feature
